-- View erstellen
drop view CALC.VIEW_CLIENT_IWHS_KUNDE_EBA;
create or replace view CALC.VIEW_CLIENT_IWHS_KUNDE_EBA as
with
-- CUT_OFF_DATE
COD as (
    select CUT_OFF_DATE
    from CALC.AUTO_TABLE_CUTOFFDATES
    where IS_ACTIVE
),
-- Quelldaten
KUNDE as (
    select *,
           CUTOFFDATE           as CUT_OFF_DATE,
           'NLB_' || BORROWERID as GNI_KUNDE
    from NLB.IWHS_KUNDE_CURRENT
    where CUTOFFDATE = (select CUT_OFF_DATE from COD)
),
KUNDE2 as (
    select *,
           'NLB_' || PERSONEN_NR as GNI_KUNDE
    from NLB.IWHS_KUNDE2_CURRENT
    where CUT_OFF_DATE = (select CUT_OFF_DATE from COD)
),
-- Alles zusammenführen
FINAL as (
    select NVL(A.CUT_OFF_DATE, B.CUT_OFF_DATE) as CUT_OFF_DATE,
           NVL(A.GNI_KUNDE, B.GNI_KUNDE)       as GNI_KUNDE,
           A.COUNTRY                           as LAND,
           A.LEGALFORM                         as ORG_RECHTSFORM,
           SM_PA.KURZBESCHREIBUNG              as PERSONEN_ART,
           SM_WZ.KURZBESCHREIBUNG              as WIRTSCH_ZWEIG,
           A.NACE                              as MWSN_NACE_CODE,
           A.KUSY_20                           as KUSY_DSGV_NEU,
           A.PLZ                               as POSTLEITZAHL,
           A.ORT,
           A.STRASSE,
           A.BIRTHDAY                          as GEBURTS_GRUENDUNGS_DAT,
           SM_BS.KURZBESCHREIBUNG              as BERUFL_STELLUNG,
           A.BERUF_BRANCHE,
           A.HAUSNR,
           B.FUEHRENDE_BONITAET,
           B.SCHUFA_AUSKUNFT,
           B.SCHUFA_NEGATIVMERKMAL,
           B.SCHUFA_SCORING_WERT,
           B.LETZTE_AENDERUNG,
           B.TREIBHAUSGASEMISSIONEN_KUNDEN_SCORE,
           B.TREIBHAUSGASEMISSIONEN_BRANCHEN_SCORE,
           B.WASSEREINSATZ_KUNDEN_SCORE,
           B.WASSEREINSATZ_BRANCHEN_SCORE,
           B.GERINGFUEGIGE_BESCHAEFTIGUNG_KUNDEN_SCORE,
           B.GERINGFUEGIGE_BESCHAEFTIGUNG_BRANCHEN_SCORE,
           B.LEIHARBEIT_KUNDEN_SCORE,
           B.LEIHARBEIT_BRANCHEN_SCORE,
           B.GENDER_PAY_GAP_KUNDEN_SCORE,
           B.GENDER_PAY_GAP_BRANCHEN_SCORE,
           B.AKUTE_PHYSISCHE_RISIKEN_HOCHWASSER_KUNDEN_SCORE,
           B.AKUTE_PHYSISCHE_RISIKEN_HOCHWASSER_BRANCHEN_SCORE,
           B.CHRONISCHE_PHYSISCHE_RISIKEN_BIODIVERSITAET_KUNDEN_SCORE,
           B.CHRONISCHE_PHYSISCHE_RISIKEN_BIODIVERSITAET_BRANCHEN_SCORE,
           B.WANDLUNGSFAEHIGKEIT_KLIMANEUTRALITAET_KUNDEN_SCORE,
           B.WANDLUNGSFAEHIGKEIT_KLIMANEUTRALITAET_BRANCHEN_SCORE,
           B.SOZIALE_STANDARDS_VERSTOESSE_GEGEN_MENSCHENRECHTE_ENTLANG_DER_WERTSCHOEPFUNGSKETTE_KUNDEN_SCORE,
           B.SOZIALE_STANDARDS_VERSTOESSE_GEGEN_MENSCHENRECHTE_ENTLANG_DER_WERTSCHOEPFUNGSKETTE_BRANCHEN_SCORE,
           B.ORGANISATORISCHE_INTEGRATION_VON_NACHHALTIGKEIT_KUNDEN_SCORE,
           B.ORGANISATORISCHE_INTEGRATION_VON_NACHHALTIGKEIT_BRANCHEN_SCORE,
           B.GEFAEHRLICHER_ABFALL_KUNDEN_SCORE,
           B.GEFAEHRLICHER_ABFALL_BRANCHEN_SCORE,
           B.VERSTOESSE_GEGEN_EINE_ORDNUNGSGEMAESSE_UNTERNEHMENSFUEHRUNG_KUNDEN_SCORE,
           B.VERSTOESSE_GEGEN_EINE_ORDNUNGSGEMAESSE_UNTERNEHMENSFUEHRUNG_BRANCHEN_SCORE,
           B.HAUPTLEGIMITATION,
           B.LEGITIMIERUNGSART,
           B.AUSSTELLUNGSDATUM,
           B.EINTRAGEDATUM_IN_OEFFENTL_REGISTER,
           B.ABLAUFDATUM_DER_LEGITIMATION,
           B.LEGITIMATIONSNUMMER,
           B.AUSSTELLENDE_BEHOERDE,
           B.AUSSTELLUNGSORT,
           B.STEUERLICH_ALS_AUSLAENDER_ZU_BEHANDELN,
           B.ROLLE_FINANZSSANKTIONEN,
           B.GWG_FALL,
           B.ABW_WIRT_BERECHTIGTER
    from KUNDE A
             full outer join KUNDE2 B
                             on B.GNI_KUNDE = A.GNI_KUNDE
             left join SMAP.IWHS_PERSONEN_ART SM_PA on SM_PA.S_KEY = A.PERSONTYPE
             left join SMAP.IWHS_BERUFLICHE_STELLUNG SM_BS on SM_BS.S_KEY = A.BERUFL_STELLUNG
             left join SMAP.IWHS_WIRTSCHAFTS_ZWEIG SM_WZ on SM_WZ.S_KEY = A.CUSTOMERSEGMENT
),
-- Gefiltert nach noetigen Datenfeldern
FINAL_FILTERED as (
    select
        -- Defaults
        CUT_OFF_DATE,
-- Columns
        GNI_KUNDE,
        ORG_RECHTSFORM,
        PERSONEN_ART,
        WIRTSCH_ZWEIG,
        MWSN_NACE_CODE,
        KUSY_DSGV_NEU,
        GEBURTS_GRUENDUNGS_DAT,
        BERUFL_STELLUNG,
        BERUF_BRANCHE,
        STRASSE,
        HAUSNR,
        POSTLEITZAHL,
        ORT,
        LAND,
        FUEHRENDE_BONITAET,
        SCHUFA_AUSKUNFT,
        SCHUFA_NEGATIVMERKMAL,
        SCHUFA_SCORING_WERT,
        LETZTE_AENDERUNG,
        TREIBHAUSGASEMISSIONEN_KUNDEN_SCORE,
        TREIBHAUSGASEMISSIONEN_BRANCHEN_SCORE,
        WASSEREINSATZ_KUNDEN_SCORE,
        WASSEREINSATZ_BRANCHEN_SCORE,
        GERINGFUEGIGE_BESCHAEFTIGUNG_KUNDEN_SCORE,
        GERINGFUEGIGE_BESCHAEFTIGUNG_BRANCHEN_SCORE,
        LEIHARBEIT_KUNDEN_SCORE,
        LEIHARBEIT_BRANCHEN_SCORE,
        GENDER_PAY_GAP_KUNDEN_SCORE,
        GENDER_PAY_GAP_BRANCHEN_SCORE,
        AKUTE_PHYSISCHE_RISIKEN_HOCHWASSER_KUNDEN_SCORE,
        AKUTE_PHYSISCHE_RISIKEN_HOCHWASSER_BRANCHEN_SCORE,
        CHRONISCHE_PHYSISCHE_RISIKEN_BIODIVERSITAET_KUNDEN_SCORE,
        CHRONISCHE_PHYSISCHE_RISIKEN_BIODIVERSITAET_BRANCHEN_SCORE,
        WANDLUNGSFAEHIGKEIT_KLIMANEUTRALITAET_KUNDEN_SCORE,
        WANDLUNGSFAEHIGKEIT_KLIMANEUTRALITAET_BRANCHEN_SCORE,
        SOZIALE_STANDARDS_VERSTOESSE_GEGEN_MENSCHENRECHTE_ENTLANG_DER_WERTSCHOEPFUNGSKETTE_KUNDEN_SCORE,
        SOZIALE_STANDARDS_VERSTOESSE_GEGEN_MENSCHENRECHTE_ENTLANG_DER_WERTSCHOEPFUNGSKETTE_BRANCHEN_SCORE,
        ORGANISATORISCHE_INTEGRATION_VON_NACHHALTIGKEIT_KUNDEN_SCORE,
        ORGANISATORISCHE_INTEGRATION_VON_NACHHALTIGKEIT_BRANCHEN_SCORE,
        GEFAEHRLICHER_ABFALL_KUNDEN_SCORE,
        GEFAEHRLICHER_ABFALL_BRANCHEN_SCORE,
        VERSTOESSE_GEGEN_EINE_ORDNUNGSGEMAESSE_UNTERNEHMENSFUEHRUNG_KUNDEN_SCORE,
        VERSTOESSE_GEGEN_EINE_ORDNUNGSGEMAESSE_UNTERNEHMENSFUEHRUNG_BRANCHEN_SCORE,
        HAUPTLEGIMITATION,
        LEGITIMIERUNGSART,
        AUSSTELLUNGSDATUM,
        EINTRAGEDATUM_IN_OEFFENTL_REGISTER,
        ABLAUFDATUM_DER_LEGITIMATION,
        LEGITIMATIONSNUMMER,
        AUSSTELLENDE_BEHOERDE,
        AUSSTELLUNGSORT,
        STEUERLICH_ALS_AUSLAENDER_ZU_BEHANDELN,
        ROLLE_FINANZSSANKTIONEN,
        GWG_FALL,
        ABW_WIRT_BERECHTIGTER,
        -- Defaults
        CURRENT_USER      as USER,
        CURRENT_TIMESTAMP as TIMESTAMP_LOAD
    from FINAL
)
select *
from FINAL_FILTERED;

-- CI START FOR ALL TAPES

-- Current-Tabelle erstellen
------------------------------------------------------------------------------------------------------------------------
call STG.TEST_PROC_BACKUP_AND_DROP('AMC', 'TABLE_CLIENT_IWHS_KUNDE_EBA_CURRENT');
create table AMC.TABLE_CLIENT_IWHS_KUNDE_EBA_CURRENT like CALC.VIEW_CLIENT_IWHS_KUNDE_EBA distribute by hash (GNI_KUNDE) in SPACE_AMC_A,SPACE_AMC_B,SPACE_AMC_C,SPACE_AMC_D,SPACE_AMC_E,SPACE_AMC_F;
create index AMC.INDEX_CLIENT_IWHS_KUNDE_EBA_CURRENT_GNI_KUNDE on AMC.TABLE_CLIENT_IWHS_KUNDE_EBA_CURRENT (GNI_KUNDE);
call STG.TEST_PROC_LOAD_AND_DROP_BACKUP_FOR('AMC', 'TABLE_CLIENT_IWHS_KUNDE_EBA_CURRENT');
------------------------------------------------------------------------------------------------------------------------

-- CI END FOR ALL TAPES

-- SWITCH Views erstellen
------------------------------------------------------------------------------------------------------------------------
call STG.TEST_PROC_DROP_AND_CREATE_SWITCH('AMC', 'TABLE_CLIENT_IWHS_KUNDE_EBA_CURRENT');
------------------------------------------------------------------------------------------------------------------------

