drop view CALC.VIEW_PRE_GUARANTOR_NLB;
create or replace view CALC.VIEW_PRE_GUARANTOR_NLB as
with
     GF as (
    select * from (
        select *, row_number() over (partition by KUNDENNUMMER order by BILANZSTICHTAG desc) as NBR from NLB.GLOBAL_FORMAT_KUNDENDATEN
                  )  AS A
    where NBR = 1
), ab_03_2019 as (
    select distinct
        KREDITNEHMER.Branch || '_' ||KREDITNEHMER.PARTNER_ID  as Kreditnehmer
        ,NULL as PORTFOLIO
        ,NULL as Borrower_NAME
        ,NULL as RECOURCE
        ,NULL as REASON
        ,BUERGE.PARTNER_ID as Buerge
        ,GF.WAEHRUNG as BILANZWAEHRUNG_GARANT
        ,GF.EBITDA_8200 as EBITDA_GARANT
        ,GF.UMSATZERLOESE_4000_1 as GESAMTUMSATZ_GARANT
        ,BILANZSTICHTAG as BILANZSTICHTAG_GARANT
        ,GEZEICHNETES_KAPITAL_VORZUGSAKTIEN_2420 as STAMMKAPITAL
        ,KK.COUNTRY  as COUNTRY_GARANT
        ,SV_ART as Kommentar
        --,B.CMS_ID
        --,B.CMS_SYS
        --,SV.SV_ART
        --,SV_BESCHREIBUNG
        ,KREDITNEHMER.CUTOFFDATE
        ,COLLATERAL.TIMESTAMP_LOAD
        ,NULL as ETL_NR
        ,KREDITNEHMER.QUELLE
        ,KREDITNEHMER.BRANCH
    from NLB.CMS_GP_CURRENT as KREDITNEHMER
    inner join NLB.CMS_GP_CURRENT as BUERGE on KREDITNEHMER.CUTOFFDATE=BUERGE.CUTOFFDATE and KREDITNEHMER.CMS_ID = BUERGE.CMS_ID
    inner join NLB.CMS_SV_CURRENT as COLLATERAL on COLLATERAL.CUTOFFDATE = KREDITNEHMER.CUTOFFDATE and BUERGE.CMS_ID=COLLATERAL.SV_ID
    inner join CALC.SWITCH_PORTFOLIO_CURRENT as PORTFOLIO on PORTFOLIO.CUT_OFF_DATE = KREDITNEHMER.CUTOFFDATE and left(PORTFOLIO.CLIENT_NO,10) = left(KREDITNEHMER.PARTNER_ID,10) and PORTFOLIO.BRANCH_SYSTEM = 'NLB'
    left join GF on GF.KUNDENNUMMER=BUERGE.PARTNER_ID
    left join NLB.IWHS_KUNDE_CURRENT as KK on KK.BORROWERID=BUERGE.PARTNER_ID and BUERGE.CUTOFFDATE=KK.CUTOFFDATE
    where KREDITNEHMER.PARTNER_FKT = 'Kreditnehmer'
      and BUERGE.PARTNER_FKT = 'Bürge/Garant'
      and COLLATERAL.SV_STATUS = 'Rechtlich aktiv'
      and KREDITNEHMER.CUTOFFDATE  > '31.12.2018'
)
select * from NLB.MI_GUARANTOR_INFORMATION where CUTOFFDATE <= '01.01.2019'
    union all
select * from ab_03_2019;