
-- VIEW erstellen
------------------------------------------------------------------------------------------------------------------------
drop view CALC.VIEW_AIRLINES;
create or replace view CALC.VIEW_AIRLINES as
with
-- Flugzeuge Assets und zugehörige Konten und Kunden
    AIRCRAFT_REC_BASIS as (
        select AIRCRAFT_RECOURCE.*
        from STG.T_VIEW_AIRCRAFT_RECOURCE as AIRCRAFT_RECOURCE
    ),AIRLINE_NAMES_MAPPING as (
        select * from SMAP.AIRLINE_AIRCRAFT_OWNER_NAME_TO_CLIENT_ID
    ),ACASA_EINDEUTIG as (
        select *
                    from (
                             select A.*,
                                    row_number()
                                            over (partition by trim(L '0' from MSN),CUTOFFDATE order by DATUM_GUELTIG desc nulls last) as NBR
                             from NLB.ACASA_FLUGZEUG_GUTACHTEN as A
                         ) AS GUTACHTEN
                    where NBR = 1
    )
    ,AIRLINE_BASIS as (
        select distinct
                    GES_OPERATOR as ACASA_AIRLINE_NAME,OPERATOR_ID,FOCS_AIRLINE_NAME,
                    GES_OWNER as ACASA_OWNER_NAME,OWNER_ID,FOCS_OWNER_NAME,
                    GES_MANAGER as ACASA_MANAGER_NAME,MANAGER_ID,FOCS_MANAGER_NAME
        from (
            select distinct
                        ACASA.KUNDENNR
                        ,ACASA.CMS_ID
                        ,ACASA.GES_OPERATOR,ANM_OP.CLIENT_ID as OPERATOR_ID,ANM_OP.NAME_NORMALIZED as FOCS_AIRLINE_NAME
                        ,ACASA.GES_OWNER,ANM_OW.CLIENT_ID as OWNER_ID,ANM_OW.NAME_NORMALIZED as FOCS_OWNER_NAME
                        ,ACASA.GES_MANAGER ,ANM_MA.CLIENT_ID as MANAGER_ID,ANM_MA.NAME_NORMALIZED as FOCS_MANAGER_NAME
            from ACASA_EINDEUTIG as ACASA
            inner join CALC.SWITCH_PORTFOLIO_CURRENT as PORTFOLIO on PORTFOLIO.CUT_OFF_DATE = ACASA.CUTOFFDATE
            left join AIRLINE_NAMES_MAPPING as ANM_OP on ANM_OP.NAME_ACASA_RAW=ACASA.GES_OPERATOR
            left join AIRLINE_NAMES_MAPPING as ANM_OW on ANM_OW.NAME_ACASA_RAW=ACASA.GES_OWNER
            left join AIRLINE_NAMES_MAPPING as ANM_MA on ANM_MA.NAME_ACASA_RAW=ACASA.GES_MANAGER
            where 1=1
                and GES_MANAGER is not null
                --and IWHS_MA.BORROWERID is null
                      )
        --order by GES_OWNER
    )
     ,AIRCRAFT_REC_DATA as (
        select * from (
            select distinct R.KD_NR, R.AIRLINE_CUSTOMER_NUMBER, R.CUTOFFDATE,
                            KUNDENDATEN.KUNDENNUMMER, KUNDENDATEN.KUNDENNAME, KUNDENDATEN.BILANZSTICHTAG, KUNDENDATEN.KONSOLIDIERUNGSEINHEIT, KUNDENDATEN.BILANZSTANDARD, KUNDENDATEN.WAEHRUNG, KUNDENDATEN.BILANZSUMME_1000_1, KUNDENDATEN.SUMME_KFR_AKTIVA_1100_1, KUNDENDATEN.FLUESSIGE_MITTEL_KASSE_BANK_SCHECKS_1110_1, KUNDENDATEN.WERTPAPIERE_1120_1,
                            FREI_VERFUEGBAR_1125_1, KFR_FORDERUNGEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_1140_1, KFR_STEUERERSTATTUNGEN_1151, KFR_LATENTE_STEUERN_1152, KFR_RECHNUNGSABGRENZUNGSPOSTEN_1160, SONSTIGE_KFR_FORDERUNGEN_VGG_1170,
                            FREI_VERFUEGBAR_1175, ROH_HILFS_UND_BETRIEBSSTOFFE_1180, UNFERTIGE_ERZEUGNISSE_1181, FERTIGE_ERZEUGNISSE_1183, HANDELSWARE_1184,
                            FREI_VERFUEGBAR_1185, SUMME_VORRAETE_1190, GELEISTETE_ANZAHLUNGEN_AUF_VORRAETE_1191,
                            FREI_VERFUEGBAR_1195, IN_DEN_VORRAETEN_ABGESETZTE_ANZAHLUNGEN_1198, SUMME_SACHANLAGEN_1200_1, GRUNDSTUECKE_UND_BAUTEN_1210,
                            FREI_VERFUEGBAR_1215, TECHNISCHE_ANLAGEN_MASCHINEN_1230,
                            FREI_VERFUEGBAR_1235, ANDERE_ANLAGEN_BETRIEBS_U_GESCHAEFTSAUSSTATTUNG_1250,
                            FREI_VERFUEGBAR_1255, ANZAHLUNGEN_UND_ANLAGEN_IM_BAU_1270,
                            FREI_VERFUEGBAR_1275, AKKUMULIERTE_ABSCHREIBUNGEN_1290, SUMME_MFR_LFR_AKTIVA_1300, KONZESSIONEN_RECHTE_LIZENZEN_1310, DAVON_NUTZUNGSRECHTE_FUER_LEASES_1311, BETEILIGUNGEN_VERBUNDENE_UNTERNEHMEN_1320,
                            FREI_VERFUEGBAR_1325, ANDERE_FINANZANLAGEN_AUSLEIHUNGEN_1330, DAVON_BOERSENGAENGIGE_FINANZANLAGEN_AUSLEIHUNGEN_1331,
                            FREI_VERFUEGBAR_1335, MFR_LFR_FORDERUNGEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_1340, DISAGIO_1350, MFR_LFR_RECHNUNGSABGRENZUNGSPOSTEN_1360, SONSTIGE_MFR_LFR_FORDERUNGEN_VGG_1370,
                            FREI_VERFUEGBAR_1375, SONSTIGE_MFR_LFR_AKTIVA_1380,
                            FREI_VERFUEGBAR_1385, AKTIVER_UNTERSCHIEDSBETRAG_AUS_DER_VERMOEGENSVERRECHNUNG_1390, SUMME_GOODWILL_KONZERN_GESELLSCHAFTERFORDERUNGEN_1400, KFR_KONZERNFORDERUNGEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_1410, MFR_LFR_KONZERNFORDERUNGEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_1420, SONSTIGE_KFR_KONZERNFORDERUNGEN_1430, SONSTIGE_MFR_LFR_KONZERNFORDERUNGEN_AUSLEIHUNGEN_1440, FORDERUNGEN_AN_KOMMANDITISTEN_1450, FORDERUNGEN_AN_GMBH_GESELLSCHAFTER_AKTIONAERE_1460, GOODWILL_GESCHAEFTS_ODER_FIRMENWERT_1470, MFR_LFR_LATENTE_STEUERN_1480, SELBST_ERSTELLTE_IMMATERIELLE_VERMOEGENSGEGENSTAENDE_1490, DIFFERENZ_IN_DER_BILANZ_AKTIVA_PASSIVA_1610, BILANZSUMME_2000, SUMME_KFR_FREMDKAPITAL_2100, KFR_BANKVERBINDLICHKEITEN_2110, KFR_BANKVERBINDLICHKEITEN_GGUE_NORD_LB_2111, SONSTIGE_KFR_FINANZVERBINDLICHKEITEN_IBD_2120,
                            FREI_VERFUEGBAR_2125, KFR_ANLEIHEN_2131, KFR_TILGUNGSANTEIL_MFR_LFR_VERBINDLICHKEITEN_2132, KFR_LEASINGVERBINDLICHKEITEN_2133, KFR_VERBINDLICHKEITEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_2140, AKZEPTE_2145, STEUERVERBINDLICHKEITEN_2151, KFR_LATENTE_STEUERN_2152, KFR_RECHNUNGSABGRENZUNGSPOSTEN_2160, ERHALTENE_ANZAHLUNGEN_KFR_2163,
                            FREI_VERFUEGBAR_2165, SONSTIGE_KFR_VERBINDLICHKEITEN_2170, NACHR_KFR_VERBINDLICHKEITEN_GGUE_BETEILIGUNGSUNTERNEHMEN_2171,
                            FREI_VERFUEGBAR_2175, VERBINDLICHKEITEN_AUS_POC_2176, STEUERRUECKSTELLUNGEN_2180, SONSTIGE_KFR_RUECKSTELLUNGEN_2185, ZUR_AUSSCHUETTUNG_VORGESEHENER_GEWINN_2190, SUMME_KONZERN_GESELLSCHAFTERVERBINDLICHKEITEN_2200, KFR_KONZERNVERBINDLICHKEITEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_2210, MFR_LFR_KONZERNVERBINDLICHKEITEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_2220, SONSTIGE_KFR_KONZERNVERBINDLICHKEITEN_2230, DAVON_VERZINSLICHE_KFR_KONZERNVERBINDLICHKEITEN_IBD_KONZERN_2231, SONSTIGE_MFR_LFR_KONZERNVERBINDLICHKEITEN_2240, DAVON_VERZINSLICHE_MFR_LFR_KONZERNVERBINDLICHKEITEN_IBD_KONZERN_2241, KFR_VERBINDLICHKEITEN_GGUE_GMBH_GESELLSCHAFTER_AKTIONAERE_2250, MFR_LFR_VERBINDLICHKEITEN_GGUE_GMBH_GESELLSCHAFTER_AKTIONAERE_2260, KFR_KOMMANDITISTENGUTHABEN_2270, MFR_LFR_KOMMANDITISTENGUTHABEN_STILLE_EINLAGEN_2280, SUMME_MFR_LFR_FREMDKAPITAL_2300, MFR_LFR_BANKVERBINDLICHKEITEN_2310, MFR_LFR_BANKVERBINDLICHKEITEN_GGUE_NORD_LB_2311, SONSTIGE_MFR_LFR_FINANZVERBINDLICHKEITEN_IBD_2312,
                            FREI_VERFUEGBAR_2315, MFR_LFR_LEASINGVERBINDLICHKEITEN_2316, MFR_LFR_ANLEIHEN_2320, NACHRANGIGE_BANKVERBINDLICHKEITEN_2331, SONSTIGE_NACHRANGIGE_VERBINDLICHKEITEN_2332, MFR_LFR_VERBINDLICHKEITEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_2340, MFR_LFR_RECHNUNGSABGRENZUNGSPOSTEN_2360, ERHALTENE_ANZAHLUNGEN_MFR_LFR_2365, SONSTIGE_MFR_LFR_VERBINDLICHKEITEN_2370,
                            FREI_VERFUEGBAR_2375, PENSIONSVERPFLICHTUNGEN_2380, SONSTIGE_MFR_LFR_RUECKSTELLUNGEN_2383,
                            FREI_VERFUEGBAR_2385, MFR_LFR_LATENTE_STEUERN_2390, SOPO_INVESTITIONSZUSCHUESSE_2393, BRUTTO_HAFTKAPITAL_2400, MINDERHEITSANTEILE_2410, GEZEICHNETES_KAPITAL_VORZUGSAKTIEN_2420,
                            FREI_VERFUEGBAR_2430, SONSTIGES_HAFTKAPITAL_KAPITALRUECKLAGEN_2440, GEWINNRUECKLAGEN_GEWINN_VERLUSTVORTRAG_2450, KUM_ERFOLGSNEUTRALE_EIGENKAPITALVERAENDERUNGEN_2460, DAVON_WAEHRUNGSUMRECHNUNGSDIFFERENZ_KUMULIERT_2461, DAVON_NEUBEWERTUNGSRUECKLAGE_2462, DAVON_RUECKLAGE_AUS_SICHERUNGSGESCHAEFT_2463, DAVON_MINDESTPENSIONSVERPFLICHTUNG_2464, AUSSTEHENDE_EINLAGEN_AKTIVIERTE_INGANGS_ERWEITERUNGSAUFWENDUNGEN_2470, EIGENE_ANTEILE_ANTEILE_AN_HERRSCHENDEN_UNTERNEHMEN_BZW_MIT_MEHRHEIT_BETEILIGTER_GES_2480,
                            FREI_VERFUEGBAR_2490, GRUNDSTUECKE_GEBAEUDE_BRUTTO_5140, DAVON_BUCHWERT_IN_PERC_5149, MASCHINEN_TECHNISCHE_ANLAGEN_BRUTTO_5150, DAVON_BUCHWERT_IN_PERC_5159, SUMME_EVENTUALVERB_FINANZIELLE_VERPFLICHT_5500, GIRO_AKZEPTOBLIGO_5510, EVENTUALVERBINDLICHKEITEN_KONZERN_5520, SONSTIGE_EVENTUALVERB_FINANZIELLE_VERPFLICHT_5530, LEASINGVERBINDLICHKEITEN_NICHT_BILANZIERT_BARWERT_5541, LEASINGVERBINDLICHKEITEN_NICHT_BILANZIERT_NOMINALWERT_5542, PENSIONSVERPFLICHTUNGEN_NICHT_BILANZIERT_5550,
                            FREI_VERFUEGBAR_5560, BESICHERTE_VERBINDLICHKEITEN_5610, BILANZSUMME_1000_2, SUMME_KFR_AKTIVA_1100_2, FLUESSIGE_MITTEL_KASSE_BANK_SCHECKS_1110_2, WERTPAPIERE_1120_2,
                            FREI_VERFUEGBAR_1125_2, KFR_FORDERUNGEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_1140_2, KFR_STEUERERSTATTUNGEN_1151_2, KFR_LATENTE_STEUERN_1152_2, KFR_RECHNUNGSABGRENZUNGSPOSTEN_1160_2, SONSTIGE_KFR_FORDERUNGEN_VGG_1170_2,
                            FREI_VERFUEGBAR_1175_2, ROH_HILFS_UND_BETRIEBSSTOFFE_1180_2, UNFERTIGE_ERZEUGNISSE_1181_2, FERTIGE_ERZEUGNISSE_1183_2, HANDELSWARE_1184_2,
                            FREI_VERFUEGBAR_1185_2, SUMME_VORRAETE_1190_2, GELEISTETE_ANZAHLUNGEN_AUF_VORRAETE_1191_2,
                            FREI_VERFUEGBAR_1195_2, IN_DEN_VORRAETEN_ABGESETZTE_ANZAHLUNGEN_1198_2, SUMME_SACHANLAGEN_1200_2, SEESCHIFFE_1205_13_01, GRUNDSTUECKE_UND_BAUTEN_1210_2,
                            FREI_VERFUEGBAR_1215_2, TECHNISCHE_ANLAGEN_MASCHINEN_1230_2,
                            FREI_VERFUEGBAR_1235_2, ANDERE_ANLAGEN_BETRIEBS_U_GESCHAEFTSAUSSTATTUNG_1250_2,
                            FREI_VERFUEGBAR_1255_2, ANZAHLUNGEN_UND_ANLAGEN_IM_BAU_1270_2,
                            FREI_VERFUEGBAR_1275_2, AKKUMULIERTE_ABSCHREIBUNGEN_1290_2, SUMME_MFR_LFR_AKTIVA_1300_2, KONZESSIONEN_RECHTE_LIZENZEN_1310_2, DAVON_NUTZUNGSRECHTE_FUER_LEASES_1311_2, BETEILIGUNGEN_VERBUNDENE_UNTERNEHMEN_1320_2,
                            FREI_VERFUEGBAR_1325_2, ANDERE_FINANZANLAGEN_AUSLEIHUNGEN_1330_2, DAVON_BOERSENGAENGIGE_FINANZANLAGEN_AUSLEIHUNGEN_1331_2,
                            FREI_VERFUEGBAR_1335_2, MFR_LFR_FORDERUNGEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_1340_2, DAVON_MFR_LFR_FORDERUNGEN_AUS_REEDEREIBETRIEB_1340_13_01, DISAGIO_1350_2, MFR_LFR_RECHNUNGSABGRENZUNGSPOSTEN_1360_2, SONSTIGE_MFR_LFR_FORDERUNGEN_VGG_1370_2,
                            FREI_VERFUEGBAR_1375_2, SONSTIGE_MFR_LFR_AKTIVA_1380_2,
                            FREI_VERFUEGBAR_1385_2, AKTIVER_UNTERSCHIEDSBETRAG_AUS_DER_VERMOEGENSVERRECHNUNG_1390_2, SUMME_GOODWILL_KONZERN_GESELLSCHAFTERFORDERUNGEN_1400_2, KFR_KONZERNFORDERUNGEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_1410_2, MFR_LFR_KONZERNFORDERUNGEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_1420_2, SONSTIGE_KFR_KONZERNFORDERUNGEN_1430_2, SONSTIGE_MFR_LFR_KONZERNFORDERUNGEN_AUSLEIHUNGEN_1440_2, FORDERUNGEN_AN_KOMMANDITISTEN_1450_2, FORDERUNGEN_AN_GMBH_GESELLSCHAFTER_AKTIONAERE_1460_2, GOODWILL_GESCHAEFTS_ODER_FIRMENWERT_1470_2, MFR_LFR_LATENTE_STEUERN_1480_2, SELBST_ERSTELLTE_IMMATERIELLE_VERMOEGENSGEGENSTAENDE_1490_2, DIFFERENZ_IN_DER_BILANZ_AKTIVA_PASSIVA_1610_2, BILANZSUMME_2000_2, SUMME_KFR_FREMDKAPITAL_2100_2, KFR_BANKVERBINDLICHKEITEN_2110_2, KFR_BANKVERBINDLICHKEITEN_GGUE_NORD_LB_2111_2, SONSTIGE_KFR_FINANZVERBINDLICHKEITEN_IBD_2120_2,
                            FREI_VERFUEGBAR_2125_2, KFR_ANLEIHEN_2131_2, KFR_TILGUNGSANTEIL_MFR_LFR_VERBINDLICHKEITEN_2132_2, KFR_LEASINGVERBINDLICHKEITEN_2133_2, KFR_VERBINDLICHKEITEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_2140_2, AKZEPTE_2145_2, STEUERVERBINDLICHKEITEN_2151_2, KFR_LATENTE_STEUERN_2152_2, KFR_RECHNUNGSABGRENZUNGSPOSTEN_2160_2, ERHALTENE_ANZAHLUNGEN_KFR_2163_2,
                            FREI_VERFUEGBAR_2165_2, SONSTIGE_KFR_VERBINDLICHKEITEN_2170_2,
                            FREI_VERFUEGBAR_2175_2, VERBINDLICHKEITEN_AUS_POC_2176_2, STEUERRUECKSTELLUNGEN_2180_2, SONSTIGE_KFR_RUECKSTELLUNGEN_2185_2, ZUR_AUSSCHUETTUNG_VORGESEHENER_GEWINN_2190_2, SUMME_KONZERN_GESELLSCHAFTERVERBINDLICHKEITEN_2200_2, KFR_KONZERNVERBINDLICHKEITEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_2210_2, MFR_LFR_KONZERNVERBINDLICHKEITEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_2220_2, SONSTIGE_KFR_KONZERNVERBINDLICHKEITEN_2230_2, DAVON_VERZINSLICHE_KFR_KONZERNVERBINDLICHKEITEN_IBD_KONZERN_2231_2, SONSTIGE_MFR_LFR_KONZERNVERBINDLICHKEITEN_2240_2, DAVON_VERZINSLICHE_MFR_LFR_KONZERNVERBINDLICHKEITEN_IBD_KONZERN_2241_2, KFR_VERBINDLICHKEITEN_GGUE_GMBH_GESELLSCHAFTER_AKTIONAERE_2250_2, MFR_LFR_VERBINDLICHKEITEN_GGUE_GMBH_GESELLSCHAFTER_AKTIONAERE_2260_2, KFR_KOMMANDITISTENGUTHABEN_2270_2, MFR_LFR_KOMMANDITISTENGUTHABEN_STILLE_EINLAGEN_2280_2, SUMME_MFR_LFR_FREMDKAPITAL_2300_2, MFR_LFR_BANKVERBINDLICHKEITEN_2310_2, MFR_LFR_BANKVERBINDLICHKEITEN_GGUE_NORD_LB_2311_2, SONSTIGE_MFR_LFR_FINANZVERBINDLICHKEITEN_IBD_2312_2,
                            FREI_VERFUEGBAR_2315_2, MFR_LFR_LEASINGVERBINDLICHKEITEN_2316_2, MFR_LFR_ANLEIHEN_2320_2, NACHRANGIGE_BANKVERBINDLICHKEITEN_2331_2, SONSTIGE_NACHRANGIGE_VERBINDLICHKEITEN_2332_2, MFR_LFR_VERBINDLICHKEITEN_AUS_LIEFERUNGEN_U_LEISTUNGEN_2340_2, MFR_LFR_RECHNUNGSABGRENZUNGSPOSTEN_2360_2, ERHALTENE_ANZAHLUNGEN_MFR_LFR_2365_2, SONSTIGE_MFR_LFR_VERBINDLICHKEITEN_2370_2,
                            FREI_VERFUEGBAR_2375_2, PENSIONSVERPFLICHTUNGEN_2380_2, SONSTIGE_MFR_LFR_RUECKSTELLUNGEN_2383_2,
                            FREI_VERFUEGBAR_2385_2, MFR_LFR_LATENTE_STEUERN_2390_2, SOPO_INVESTITIONSZUSCHUESSE_2393_2, BRUTTO_HAFTKAPITAL_2400_2, MINDERHEITSANTEILE_2410_2, GEZEICHNETES_KAPITAL_VORZUGSAKTIEN_2420_2, DAVON_FESTKAPITAL_PFLICHTEINLAGE_2420_13_01, DAVON_KAPITALANTEIL_DER_KOMPLEMENTAERE_2420_13_02, DAVON_KAPITALANTEIL_DER_KOMMANDITISTEN_2420_13_03,
                            FREI_VERFUEGBAR_2430_2, SONSTIGES_HAFTKAPITAL_KAPITALRUECKLAGEN_2440_2, GEWINNRUECKLAGEN_GEWINN_VERLUSTVORTRAG_2450_2, KUM_ERFOLGSNEUTRALE_EIGENKAPITALVERAENDERUNGEN_2460_2, DAVON_WAEHRUNGSUMRECHNUNGSDIFFERENZ_KUMULIERT_2461_2, DAVON_NEUBEWERTUNGSRUECKLAGE_2462_2, DAVON_RUECKLAGE_AUS_SICHERUNGSGESCHAEFT_2463_2, DAVON_MINDESTPENSIONSVERPFLICHTUNG_2464_2, AUSSTEHENDE_EINLAGEN_AKTIVIERTE_INGANGS_ERWEITERUNGSAUFWENDUNGEN_2470_2, EIGENE_ANTEILE_ANTEILE_AN_HERRSCHENDEN_UNTERNEHMEN_BZW_MIT_MEHRHEIT_BETEILIGTER_GES_2480_2,
                            FREI_VERFUEGBAR_2490_2, SEESCHIFFE_BRUTTO_5135_13_01, DAVON_BUCHWERT_IN_PERC_5139_13_01, GRUNDSTUECKE_GEBAEUDE_BRUTTO_5140_2, DAVON_BUCHWERT_IN_PERC_5149_13_01, MASCHINEN_TECHNISCHE_ANLAGEN_BRUTTO_5150_2, DAVON_BUCHWERT_IN_PERC_5159_2, SUMME_EVENTUALVERB_FINANZIELLE_VERPFLICHT_5500_2, GIRO_AKZEPTOBLIGO_5510_2, EVENTUALVERBINDLICHKEITEN_KONZERN_5520_2, SONSTIGE_EVENTUALVERB_FINANZIELLE_VERPFLICHT_5530_2, LEASINGVERBINDLICHKEITEN_NICHT_BILANZIERT_BARWERT_5541_2, LEASINGVERBINDLICHKEITEN_NICHT_BILANZIERT_NOMINALWERT_5542_2, PENSIONSVERPFLICHTUNGEN_NICHT_BILANZIERT_5550_2,
                            FREI_VERFUEGBAR_5560_2, BESICHERTE_VERBINDLICHKEITEN_5610_2, BESTANDSVERMINDERUNG_3010, MATERIALAUFWAND_3110, BEZOGENE_LEISTUNGEN_3120, MIETE_LEASING_3125, PERSONALAUFWAND_3210, DAVON_GEHAELTER_FUER_GESELLSCHAFTER_GESCHAEFTSFUEHRER_3220, SONSTIGER_AUFWAND_LEASING_3230, DAVON_MIETE_LEASING_3231,
                            FREI_VERFUEGBAR_3234, SONSTIGER_AUFWAND_3240,
                            FREI_VERFUEGBAR_3241, ABSCHREIBUNGEN_WERTBERICHTIGUNGEN_AUF_FORDERUNGEN_3245, SONSTIGE_STEUERN_3250, ABSCHREIBUNGEN_AUF_SACHANLAGEN_3260, DAVON_ABSCHREIBUNGEN_AUF_NUTZUNGSRECHTE_IM_SACH_AV_3261, ABSCHREIBUNGEN_AUF_IMMATERIELLE_VERMOEGENSGEGENSTAENDE_3270, DAVON_ABSCHREIBUNGEN_AUF_NUTZUNGSRECHTE_IM_IMMAT_AV_3271, ABSCHREIBUNGEN_AUF_GOODWILL_3275, WAEHRUNGSVERLUSTE_3290, HERSTELLUNGSKOSTEN_DES_UMSATZES_3295, VERTRIEBS_VERWALTUNGSKOSTEN_3299, ZINSAUFWAND_3410, NACHR_ZINSEN_FUER_GMBH_GESELLSCHAFTERDARLEHEN_3411, DAVON_ZINSEN_FUER_PENSIONSVERPFLICHTUNGEN_3412, DAVON_ZINSEN_FUER_SONSTIGE_MFR_LFR_RUECKSTELLUNGEN_3413, DAVON_PIK_ZINSEN_3414, DAVON_ZINSEN_FUER_NEU_BEWERTUNG_VON_FINANZVERBINDLICHKEITEN_3415, DAVON_ZINSEN_FUER_LEASINGVERBINDLICHKEITEN_3416, SONSTIGE_FINANZAUFWENDUNGEN_3420, NETTO_ZINSERGEBNIS_FALLS_NEGATIV_3450, VERLUSTE_AUS_BETEILIGUNGEN_3510,
                            FREI_VERFUEGBAR_3520, A_O_ABSCHREIBUNGEN_WERTBERICHTIGUNGEN_AUF_FORDERUNGEN_3611, ABSCHREIBUNGEN_AUF_FINANZANLAGEN_3612, SONSTIGE_A_O_RUECKSTELLUNGEN_3614, SONSTIGER_KFR_BEWERTUNGSAUFWAND_3615, SONSTIGER_MFR_LFR_BEWERTUNGSAUFWAND_3616, A_O_ABSCHREIBUNGEN_AUF_SACHANLAGEN_3651, A_O_ABSCHREIBUNGEN_AUF_IMMATERIELLES_ANLAGEVERMOEGEN_3652, A_O_AUFWAND_3670,
                            FREI_VERFUEGBAR_3680, AUFWAND_AUS_NICHT_FORTGEFUEHRTEN_AKTIVITAETEN_3685, VERLUSTE_AUS_ANLAGEABGAENGEN_3690, ZUFUEHRUNG_SOPO_INVESTITIONSZUSCHUESSE_3696, AUFWAND_LATENTE_STEUERN_3710, STEUERN_AUF_EINKOMMEN_ERTRAG_3720, ANTEIL_MINDERHEITSGESELLSCHAFTER_AM_JUE_JF_3810, UMSATZERLOESE_4000_1, BESTANDSERHOEHUNG_4010, DIFFERENZ_IN_DER_GUV_RECHNUNG_4013, ANDERE_AKTIVIERTE_EIGENLEISTUNGEN_4030, GESAMTLEISTUNG_4100, ROHERTRAG_4200, SONSTIGE_BETRIEBLICHE_ERTRAEGE_4240, NACHR_ERTRAEGE_OHNE_ANGABEN_ZUR_AUFGLIEDERUNG_4240_SR_01,
                            FREI_VERFUEGBAR_4241, WAEHRUNGSGEWINNE_4290, BRUTTOERGEBNIS_VOM_UMSATZ_4300, TEILBETRIEBSERGEBNIS_4400, ZINS_U_ZINSAEHNLICHE_ERTRAEGE_4410, DAVON_ZINSEN_FUER_PENSIONSVERPFLICHTUNGEN_4412, DAVON_ZINSEN_FUER_SONSTIGE_MFR_LFR_RUECKSTELLUNGEN_4413, SONSTIGE_FINANZERTRAEGE_4420, NETTO_ZINSERGEBNIS_FALLS_POSITIV_4450, BETRIEBSERGEBNIS_4500, BETEILIGUNGSERTRAEGE_4510,
                            FREI_VERFUEGBAR_4520, AS, ERGEBNIS_VOR_STEUERN_UND_A_O_BEREICH_4600, ZUSCHREIBUNGEN_AUF_SACHANLAGEN_4620, SONSTIGE_KFR_BEWERTUNGSERTRAEGE_4641, SONSTIGE_MFR_LFR_BEWERTUNGSERTRAEGE_4642,
                            FREI_VERFUEGBAR_4660, A_O_ERTRAG_4671,
                            FREI_VERFUEGBAR_4675, ERTRAG_AUS_A_O_UMSATZBESTANDTEILEN_4683, ERTRAG_AUS_NICHT_FORTGEFUEHRTEN_AKTIVITAETEN_4685, ERTRAG_AUS_ANLAGEABGAENGEN_4690, AUFLOESUNG_SOPO_INVESTITIONSZUSCHUESSE_4696, ERGEBNIS_VOR_STEUERN_EBT_4700, ERTRAG_LATENTE_STEUERN_4710, JAHRESUEBERSCHUSS_FEHLBETRAG_4800, EXPORTANTEIL_BZGL_UMSATZ_7012, IMPORTANTEIL_BZGL_MAT_EINKAUF_BEZ_LEISTUNGEN_7013, ZINSAUFWAND_8140D, ZINS_U_ZINSAEHNLICHE_ERTRAEGE_8141D, PLANMAESIGE_ABSCHREIBUNGEN_AUF_SELBST_ERSTELLTE_IMMATERIELLE_ANLAGEN_92187, PLANMAESIGE_ABSCHREIBUNGEN_AUF_SELBST_ERSTELLTE_IMMATERIELLE_ANLAGEN_92287, PLANMAESIGE_ABSCHREIBUNGEN_AUF_SELBST_ERSTELLTE_IMMATERIELLE_ANLAGEN_92352, DAVON_ABSCHREIBUNGEN_AUF_SELBST_ERSTELLTE_IMMATERIELLE_ANLAGEN_92400, ABSCHREIBUNGEN_AUF_SELBST_ERSTELLTE_IMMATERIELLE_ANLAGEN_92600, BILANZSUMME_1000_3, SUMME_SACHANLAGEN_1200_3, UMSATZERLOESE_4000_2, GESAMTLEISTUNGSZUWACHS_4109, ERGEBNIS_VOR_STEUERN_UND_A_O_BEREICH_4600_2, JAHRESUEBERSCHUSS_FEHLBETRAG_4800_2, INVESTITIONSQUOTE_NETTOZUGAENGE_BUCHWERT_SACHANLAGEN_VORJAHR_6104, BESCHAEFTIGTENZAHL_7011, EXPORTANTEIL_BZGL_UMSATZ_7012_2, IMPORTANTEIL_BZGL_MAT_EINKAUF_BEZ_LEISTUNGEN_7013_2, FUNDS_FROM_OPERATIONS_8871, CASH_FLOW_FROM_OPERATIONS_8873, FREE_CASH_FLOW_8876, NETTO_FINANZSCHULDEN_NET_IBD_9047, NETTO_FINANZSCHULDEN_NET_IBD_EBITDA_9048, GESAMT_FINANZSCHULDEN_IBD_LEASING_9056, MFR_LFR_AKTIVA_OHNE_MFR_LFR_FORD_AUS_LUL_UMSATZ_9104, SONSTIGE_KONZERN_U_GESELLSCH_FORD_GOODWILL_UMSATZ_9105, EIGENKAPITALRENDITE_VOR_STEUERN_P_A_9110_1, EIGENKAPITALRENDITE_VOR_STEUERN_P_A_9110_2, EIGENKAPITALRENDITE_VOR_STEUERN_P_A_9110_3, EIGENKAPITALRENDITE_VOR_STEUERN_P_A_9110_4, GESAMTKAPITALRENDITE_VOR_STEUERN_P_A_9120_1, GESAMTKAPITALRENDITE_VOR_STEUERN_P_A_9120_2, GESAMTKAPITALRENDITE_VOR_STEUERN_P_A_9120_3, GESAMTKAPITALRENDITE_VOR_STEUERN_P_A_9120_4, NETTO_UMSATZRENDITE_ERGEBNIS_NACH_STEUERN_UMSATZ_9130, KAPITALUMSCHLAG_9140, ASSET_LEVERAGE_9150, RETURN_ON_INVESTMENT_P_A_9160_1, RETURN_ON_INVESTMENT_P_A_9160_2, RETURN_ON_INVESTMENT_P_A_9160_3, RETURN_ON_INVESTMENT_P_A_9160_4, RETURN_ON_CAPITAL_EMPLOYED_9170, VERAENDERUNG_UMSATZ_GGUE_VORJAHR_9210, ROHERTRAGSQUOTE_ROHERTRAG_GESAMTLEISTUNG_9220, BRUTTOMARGE_BRUTTOERGEBNIS_UMSATZ_9221, OPERATIVE_MARGE_TEILBETRIEBSERGEBNIS_GESAMTLEISTUNG_9230, OPERATIVE_MARGE_TEILBETRIEBSERGEBNIS_UMSATZ_9231, ERGEBNIS_VOR_STEUER_A_O_GESAMTL_9240, ERGEBNIS_VOR_STEUER_A_O_UMSATZ_9241, ERGEBNIS_VOR_STEUERN_GESAMTLEISTUNG_9250, ERGEBNIS_VOR_STEUERN_UMSATZ_9251, NETTOMARGE_JUE_GESAMTLEISTUNG_9260, NETTOMARGE_JUE_UMSATZ_9261, STEUERQUOTE_9270, DIVIDEND_PAY_OUT_RATIO_AUSSCHUETTUNGSQUOTE_9280, EBIT_9310, EBIT_ZINSAUFWAND_9311, EBITDA_9320, EBITDA_ZINSAUFWAND_9321, EBITDA_ZINSAUFWAND_KFR_TILGUNGSANTEIL_MFR_LFR_VERB_9322, EBITDA_SUMME_AKTIVA_9323, EBITDA_MARGE_EBITDA_UMSATZ_9324, GESAMT_FINANZSCHULDEN_IBD_9330, GESAMT_FINANZSCHULDEN_IBD_EBITDA_9331, GESAMT_FINANZSCHULDEN_IN_PERC_DER_BILANZSUMME_9332, GESAMT_FINANZSCHULDEN_IBD_SUMME_EVENTUALVERB_EBITDA_9333, EBITDAR_9335, GESAMT_FINANZSCHULDEN_IBD_LEASING_EBITDAR_9336, EBITDAR_MARGE_EBITDAR_UMSATZ_9337, IBD_CASH_LEASINGVERBINDL_EBITDAR_9338, EBIDA_9340, VERSCHULD_KAP_MANUELL_9398, VERSCHULD_KAP_STANDARD_9399, CASH_RATIO_LIQUIDITAET_I_9410, QUICK_RATIO_LIQUIDITAET_II_9420, CURRENT_RATIO_LIQUIDITAET_III_9430, UMLAUFVERMOEGEN_I_S_INTERNATIONALER_RECHNUNGSLEGUNG_9510, BEREINIGTES_NETTO_UMLAUFVERMOEGEN_BNUV_9520, BEREINIGTES_NETTO_UMLAUFVERMOEGEN_BNUV_UMSATZ_9530, ZIELINANSPRUCHNAHME_ABNEHMER_IN_TAGEN_DEBITORENZIEL_9540, LAGERDAUER_IN_TAGEN_9550, EIGENES_ZAHLUNGSZIEL_IN_TAGEN_KREDITORENZIEL_9560, MFR_LFR_AKTIVA_INKL_KONZERN_GOODWILL_OHNE_SAV_UMSATZ_9610, SACHANLAGEVERMOEGEN_UMSATZ_9620, CAPEX_QUOTE_ZUGAENGE_SAV_UMSATZ_9630, HAFTENDE_EIGENKAPITAL_QUOTE_BRUTTO_9710, NETTO_HAFTKAPITAL_QUOTE_OHNE_GOODWILL_ETC_9720, BRUTTO_VERSCHULDUNGSGRAD_IBD_BRUTTO_HAFTKAPITAL_9730, NETTO_VERSCHULDUNGSGRAD_NET_IBD_BRUTTO_HAFTKAPITAL_9740, VERSCHULDUNG_III_9750, LEVERAGE_RATIO_9760, MFR_LFR_PASSIVA_MFR_LFR_AKTIVA_9770, GESAMTLEISTUNG_PRO_MITARBEITER_IN_T_CURRENCY_9810, UMSATZ_PRO_MITARBEITER_IN_T_CURRENCY_9811, ROHERTRAG_PRO_MITARBEITER_IN_T_CURRENCY_9820, BRUTTOERGEBNIS_PRO_MITARBEITER_IN_T_CURRENCY_9821, BETRIEBSERGEBNIS_PRO_MITARBEITER_IN_T_CURRENCY_9830, PERSONALAUFWAND_PRO_MITARBEITER_IN_T_CURRENCY_9835, BEREINIGTE_EK_QUOTE_6712, EBITDA_M2_AV_U_UV_CURRENCY_M2_6750, BUCHWERT_IMMOBILIEN_M2_DES_AV_U_UV_CURRENCY_M2_6751, FINANZVERSCHULDUNG_M2_DES_AV_U_UV_CURRENCY_M2_6752, INSTANDHALTUNGSAUFWAND_PRO_M2_AV_CURRENCY_M2_6754, NETTOKALTMIETEN_PRO_M2_AV_CURRENCY_M2_MTL_6755, LOAN_TO_VALUE_RATIO_6756, BEWERTUNGSFAKTOR_6757, ERGEBNIS_VOR_STEUERN_EBT_8100, ZUSCHREIBUNGEN_AUF_SACHANLAGEN_8111, ERTRAG_AUS_ANLAGEABGAENGEN_8113, BETEILIGUNGSERTRAEGE_8114, ANDERE_BEWERTUNGSERTRAEGE_8116, AUFLOESUNG_SOPO_INVESTITIONSZUSCHUESSE_8117, A_O_ERTRAG_NICHT_FORTGEFUEHRTE_AKTIVITAETEN_8118, ZINS_UND_ZINSAEHNLICHE_ERTRAEGE_8119, ABSCHREIBUNGEN_AUF_SACHANLAGEN_INCL_A_O_8131, ABSCHR_AUF_IMMATERIELLE_GUETER_INCL_GOFW_A_O_8132, VERLUST_AUS_ANLAGEABGAENGEN_8133, VERLUSTE_AUS_BETEILIGUNGEN_8134, CASH_WIRKSAMES_BETEILIGUNGSERGEBNIS_8135, SONSTIGE_ABSCHREIBUNGEN_BEWERTUNGSAUFWAND_8136, ZUFUEHRUNG_SOPO_INVESTITIONSZUSCHUESSE_8137, A_O_AUFWAND_NICHT_FORTGEFUEHRTE_AKTIVITAETEN_8138, ZINSAUFWAND_8139, EBITDA_8200, IN_PERC_VOM_UMSATZ_8209, STEUERN_AUF_EINKOMMEN_ERTRAG_8211, ABBAU_STEUERRUECKST_VERBINDL_ERHOEH_STEUERFORD_8212, ERHOEH_STEUERRUECKST_VERBINDL_ABBAU_STEUERFORD_8232, EBIDA_8300, IN_PERC_VOM_UMSATZ_8309, ZAHLUNG_KFR_TILGUNGSANTEIL_AUS_VORJAHR_8312, ABBAU_PENSIONSVERPFLICHTUNGEN_8313, ANDERE_MFR_LFR_RUECKSTELLUNGEN_8314, SOPO_INVESTITIONSZUSCHUESSE_8315, ZINSAUFWAND_CASH_WIRKSAM_8316, ZINS_UND_ZINSAEHNLICHE_ERTRAEGE_8331, ERHOEHUNG_PENSIONSVERPFLICHTUNGEN_8333, ANDERE_MFR_LFR_RUECKSTELLUNGEN_8334, SOPO_INVESTITIONSZUSCHUESSE_8335, CF_FUER_WC_CAPEX_KONZERN_8402, ERHOEHUNG_KFR_FORDERUNGEN_AUS_LUL_8411, VORRAETE_8412, SONSTIGE_KFR_FORDERUNGEN_RAP_8413, ABBAU_KFR_VERBINDLICHKEITEN_AUS_LUL_AKZEPTE_8414, SONSTIGE_KFR_VERBINDLICHKEITEN_POC_RAP_8415, ERHALTENE_ANZAHLUNGEN_KFR_8416, SONSTIGE_KFR_RUECKSTELLUNGEN_8417, ABBAU_KFR_FORDERUNGEN_AUS_LUL_8431, VORRAETE_8432, SONSTIGE_KFR_FORDERUNGEN_RAP_8433, ERHOEHUNG_KFR_VERBINDLICHKEITEN_AUS_LUL_AKZEPTE_8434, SONSTIGE_KFR_VERBINDLICHKEITEN_POC_RAP_8435, ERHALTENE_ANZAHLUNGEN_KFR_8436, SONSTIGE_KFR_RUECKSTELLUNGEN_8437, CF_FUER_CAPEX_KONZERN_8502, ZUGAENGE_SACHANLAGEN_8511, ERHOEHUNG_BETEILIGUNGEN_8513, IMMATERIELLES_ANLAGEVERMOEGEN_8514, MFR_LFR_FORDERUNGEN_AUS_LUL_8515, ANDERE_FINANZANLAGEN_8516, SONSTIGE_MFR_LFR_FORD_RAP_8517, SONSTIGE_MFR_LFR_AKTIVA_8518, ABBAU_MFR_LFR_VERBINDLICHKEITEN_AUS_LUL_8519, SONSTIGE_MFR_LFR_VERBINDLICHKEITEN_RAP_8520, ERHALTENE_ANZAHLUNGEN_MFR_LFR_8521, ERLOESE_SACHANLAGENABGANG_8531, ANSCHLUSSDIFFERENZ_SACHANLAGEN_8532, ABBAU_BETEILIGUNGEN_8533, IMMATERIELLES_ANLAGEVERMOEGEN_8534, MFR_LFR_FORDERUNGEN_AUS_LUL_8535, ANDERE_FINANZANLAGEN_8536, SONSTIGE_MFR_LFR_FORD_RAP_8537, SONSTIGE_MFR_LFR_AKTIVA_8538, ERHOEHUNG_MFR_LFR_VERBINDLICHKEITEN_AUS_LUL_8539, SONSTIGE_MFR_LFR_VERBINDLICHKEITEN_RAP_8540, ERHALTENE_ANZAHLUNGEN_MFR_LFR_8541, KORREKTUR_W_WAEHRUNGSANPASSUNGEN_SONSTIGES_AV_8542, KORREKTUR_W_NEUBEWERTUNG_DERIVATE_U_A_8543, KORREKTUR_W_LATENTE_STEUERN_ERFOLGSNEUTRAL_8544, KORREKTUR_W_BEWERT_AEND_SONST_ABSCHR_WERTBER_8545, CF_FUER_KONZERN_8602, ERHOEHUNG_KONZERNFORDERUNGEN_AUS_LUL_8611, SONSTIGE_KONZERNFORDERUNGEN_8612, GESELLSCHAFTERFORDERUNGEN_8613, ABBAU_KONZERNVERBINDLICHK_L_L_8614, SONSTIGE_KONZERNVERBINDLICHK_8615, GESELLSCHAFTERVERBINDLICHKEITEN_8616, ABBAU_KONZERNFORDERUNGEN_AUS_LUL_8631, SONSTIGE_KONZERNFORDERUNGEN_8632, GESELLSCHAFTERFORDERUNGEN_8633, ERHOEHUNG_KONZERNVERBINDLICHKEITEN_AUS_LUL_8634, SONSTIGE_KONZERNVERBINDLICHKEITEN_8635, GESELLSCHAFTERVERBINDLICHKEITEN_8636, CASH_FLOW_VOR_ENTNAHMEN_8702, DIVIDENDEN_ENTNAHMEN_8711, ERHOEHUNG_EIGENE_ANTEILE_8713, EINLAGEN_EINZAHLUNGEN_BEI_PERSONENGESELLSCH_8731, VERMINDERUNG_EIGENE_ANTEILE_8733, FINANZBEDARF_UEBERSCHUSS_8802, ERHOEHUNG_FLUESSIGE_MITTEL_8811, WERTPAPIERE_8812, ABBAU_KFR_BANKVERBINDLICHKEITEN_8813, KFR_VERBINDLICHKEITEN_GGUE_EIGENEM_INSTITUT_8814, KFR_FINANZVERBINDLICHKEITEN_8815, MFR_LFR_FINANZVERBINDLICHKEITEN_8818, ABBAU_FLUESSIGE_MITTEL_8831, WERTPAPIERE_8832, ERHOEHUNG_KFR_BANKVERBINDLICHKEITEN_8833, KFR_VERBINDLICHKEITEN_GGUE_EIGENEM_INSTITUT_8834, KFR_FINANZVERBINDLICHKEITEN_8835, MFR_LFR_FINANZVERBINDLICHKEITEN_8838, ERHOEHUNG_FINANZVERBINDLICHKEITEN_W_PIK_ZINSEN_8839, KORREKTUR_W_CASH_NEUTRALER_VERAENDERUNGEN_8840, CASH_NACH_FREMDFINANZIERUNG_8900, VERLUSTUEBERNAHME_DURCH_GESELLSCHAFTER_8931, KAPITALERHOEHUNG_HERABSETZUNG_8932, SONSTIGE_VERAENDERUNGEN_IM_EIGENKAPITAL_8933, ANSCHLUSSDIFFERENZ_EIGENKAPITAL_8934, KORREKTUR_W_KFR_BEWERTUNGSAEND_ABSCHREIB_8935, CASH_NACH_FINANZIERUNG_8950, ANSCHLUSSDIFFERENZ_SACHANLAGEN_1606, VERAENDERUNG_SACHANLAGEN_LT_BILANZ_1620, VERAENDERUNG_HAFTENDES_EIGENKAPITAL_LT_BILANZ_2610, ANSCHLUSSDIFFERENZ_EIGENKAPITAL_2611, VERAENDERUNG_LT_ANSCHLUSSRECHNUNG_3023, IM_LFD_GESCHAEFTSJAHR_GEZAHLTE_DIVIDENDE_3830, GEWINN_VERLUSTANTEIL_KOMMANDITISTEN_3895, GEWINN_VERLUSTANTEIL_HAFTENDER_GESELLSCHAFTER_3896, DIFFERENZ_IN_DER_GUV_RECHNUNG_4013_2, GESAMTERGEBNIS_JUE_JF_SONSTIGES_ERGEBNIS_4820, WAEHRUNGSUMRECHNUNG_4821, NEUBEWERTUNG_ZUR_VERAEUSERUNG_BESTIMMTE_VERMOEGENSWERTE_4822, CASH_FLOW_HEDGES_DERIVATE_4823, PENSIONSVERPFL_VERSICHERUNGSMATH_GEWINNE_VERLUSTE_4824, LATENTE_STEUERN_AUF_DAS_SONSTIGE_ERGEBNIS_4825, SONSTIGES_ERGEBNIS_OCI_4829, VERAENDERUNG_KAPITAL_RUECKLAGEN_AUSSTEHENDE_EINLAGEN_4831, VERAENDERUNG_EIGENE_ANTEILE_4832, AENDERUNG_DES_KONSOLIDIERUNGSKREISES_4835, SONSTIGE_UEBRIGE_VERAENDERUNGEN_4836, VERLUSTUEBERN_DURCH_GESELLSCHAFTER_BEI_KAP_GES_4840, VERAENDERUNG_HAFTENDES_EK_LT_ANSCHLUSSRECHNUNG_4999, ZUGAENGE_SACHANLAGEN_5110, NETTOABGAENGE_SACHANLAGEN_5120, ERFOLGSNEUTRALE_WAEHRUNGSANPASSUNGEN_5125, ERFOLGSNEUTRALE_NEUBEWERTUNGEN_5126, WAEHRUNGSANPASSUNGEN_ANLAGEVERMOEGEN_INKL_SACHANLAGEN_5132, CASH_NACH_FINANZIERUNG_8950_2, SUMME_8951, PLAUSIBILITAETSPRUEFUNG_CASH_NACH_FINANZIERUNG_8952, ZUGANG_SELBST_ERSTELLTE_IMMATERIELLE_ANLAGEN_92188, ZUGANG_SELBST_ERSTELLTE_IMMATERIELLE_ANLAGEN_92288, ZUGANG_SELBST_ERSTELLTE_IMMATERIELLE_ANLAGEN_92353, ZUGANG_SELBST_ERSTELLTE_IMMATERIELLE_ANLAGEN_92402, ZUGANG_SELBST_ERSTELLTE_IMMATERIELLE_ANLAGEN_92602, SUMME_SACHANLAGEN_AKTUELLES_JAHR_AR_1200, SUMME_SACHANLAGEN_VORJAHR_AR_1200LAS, HAFTENDES_EIGENKAPITAL_INKL_AUSZUSCHUETTENDER_GEWINN_AR_2499, HAFTENDES_EIGENKAPITAL_VORJ_INKL_AUSZUSCHUETTENDER_GEWINN_AR_2499LAS, ABSCHREIBUNGEN_AUF_SACHANLAGEN_AR_3260, A_O_ABSCHREIBUNGEN_AUF_SACHANLAGEN_AR_3651, A_O_AUFWAND_AR_3670, AUFWAND_AUS_NICHT_FORTGEFUEHRTEN_AKTIVITAETEN_AR_3685, JAHRESUEBERSCHUSS_FEHLBETRAG_AR_3895_1, ABZGL_MINDERHEITENANTEILE_AKTUELLES_JAHR_AR_3895_2, ZZGL_MINDERHEITENANTEILE_VORJAHR_AR_3895_3, ZZGL_WAEHRUNGSUMRECHNUNG_AR_3895_4, ZZGL_AENDERUNG_DES_KONSOLIDIERUNGSKREISES__AR_3895_5, BERECHNETER_WERT_FUER_POSITION_3895_AR_3895_6, ZUSCHREIBUNGEN_AUF_SACHANLAGEN_AR_4620, A_O_ERTRAG_AR_4670, ERTRAG_AUS_NICHT_FORTGEFUEHRTEN_AKTIVITAETEN_AR_4685, JAHRESUEBERSCHUSS_FEHLBETRAG_AR_4800,
                            KUNDENDATEN.TIMESTAMP_LOAD, KUNDENDATEN.ETL_NR, KUNDENDATEN.QUELLE, KUNDENDATEN.BRANCH,
                            row_number() over (partition by AIRLINE_CUSTOMER_NUMBER, R.CUTOFFDATE order by BILANZSTICHTAG desc, KONSOLIDIERUNGSEINHEIT desc)  as BALANCESHEET_CUTOFFDATE_ORDER_NUMBER
            from AIRCRAFT_REC_BASIS as R
            left join NLB.GLOBAL_FORMAT_KUNDENDATEN AS KUNDENDATEN on 'NLB_' || KUNDENDATEN.KUNDENNUMMER = R.AIRLINE_CUSTOMER_NUMBER
            where R.AIRLINE_CUSTOMER_NUMBER is not NULL
                  ) where BALANCESHEET_CUTOFFDATE_ORDER_NUMBER = 1 -- nur den neuesten Bilanzstichtag
    ),
    CLIENT_TO_AIRLINE as (
        select * from (
            select distinct
                            CLIENT_ID,
                            CLIENT_ID_PARTNER,
                            CLIENT_DATA.*,
                            row_number() over (partition by CLIENT_ID_PARTNER,B.CUTOFFDATE order by BILANZSTICHTAG desc, KONSOLIDIERUNGSEINHEIT desc) as ORDER_NUMBER
            from NLB.ZO_KUNDE_CURRENT               as ZO_KUNDE_A
            left join NLB.GLOBAL_FORMAT_KUNDENDATEN as CLIENT_DATA  on KUNDENNUMMER = PARTNER_C072 and CLIENT_DATA.CUTOFFDATE = ZO_KUNDE_A.CUTOFFDATE
            inner join (
                select distinct ZO_KUNDE_B.CUTOFFDATE, CLIENT_ID,KREDITNEHMEREINHEIT_SAP,'NLB_' || PARTNER_C072 as CLIENT_ID_PARTNER
                from NLB.ZO_KUNDE_CURRENT   as ZO_KUNDE_B
                inner join (
                    select KD_NR as CLIENT_ID,AIRLINE_CUSTOMER_NUMBER,AIRCRAFT_DATA_C.CUTOFFDATE from AIRCRAFT_REC_DATA as AIRCRAFT_DATA_C where AIRCRAFT_DATA_C.KUNDENNUMMER is NULL
                    )                       as AIRCRAFT_DATA_B  on AIRCRAFT_DATA_B.AIRLINE_CUSTOMER_NUMBER = 'NLB_' || PARTNER_C072 and AIRCRAFT_DATA_B.CUTOFFDATE=ZO_KUNDE_B.CUTOFFDATE
                )                                   as B            on B.KREDITNEHMEREINHEIT_SAP = ZO_KUNDE_A.KREDITNEHMEREINHEIT_SAP and ZO_KUNDE_A.CUTOFFDATE = B.CUTOFFDATE
            where CLIENT_DATA.KUNDENNUMMER is not NULL
        ) where ORDER_NUMBER = 1
    ),
    PRE_AA_REC as (
        select distinct
            KD_NR,
            BB.CUTOFFDATE,
            AIRLINE_CUSTOMER_NUMBER,
            BILANZSTICHTAG,
            WAEHRUNG as CURRENCY,
            EBITDA_9320,
            FLOAT(UMSATZERLOESE_4000_1) as TRANSACTION_VOLUME,
            Float(HAFTENDES_EIGENKAPITAL_INKL_AUSZUSCHUETTENDER_GEWINN_AR_2499) as CAPITAL_STOCK,
            case
                when COUNTRY = '001 FRANKREICH' then 'FR'
                when COUNTRY = '003 NIEDERLANDE' then 'NL'
                when COUNTRY = '005 ITALIEN' then 'IT'
                when COUNTRY = '018 LUXEMBURG' then 'LU'
                when COUNTRY = '028 NORWEGEN' then 'NO'
                when COUNTRY = '030 SCHWEDEN' then 'SE'
                when COUNTRY = '052 TÜRKEI' then 'TR'
                when COUNTRY = '106 GROSSBRITANNIEN' then 'GB'
                when COUNTRY = '334 ÄTHIOPIEN' then 'ET'
                when COUNTRY = '400 VEREINIGTE STAATEN VON AMERIKA' then 'US'
                when COUNTRY = '404 KANADA' then 'CA'
                when COUNTRY = '412 MEXIKO' then 'MX'
                when COUNTRY = '442 PANAMA' then 'PA'
                when COUNTRY = '480 KOLUMBIEN' then 'CO'
                when COUNTRY = '508 BRASILIEN' then 'BR'
                when COUNTRY = '512 CHILE' then 'CL'
                when COUNTRY = '624 ISRAEL' then 'IL'
                when COUNTRY = '647 VEREINIGTE ARABISCHE EMIRATE' then 'AE'
                when COUNTRY = '701 MALAYSIA' then 'MY'
                when COUNTRY = '720 CHINA' then 'CN'
                when COUNTRY = '728 SÜDKOREA' then 'KR'
                when COUNTRY = '004 DEUTSCHLAND' then 'DE'
                when COUNTRY = '075 RUSSLAND' then 'RU'
                when COUNTRY = '413 BERMUDA' then 'BM'
                when COUNTRY = '708 PHILIPPINEN' then 'PH'
                when COUNTRY = '007 IRLAND' then 'IE'
                else COUNTRY
            end as COUNTRY,
            row_number() over (partition by AIRLINE_CUSTOMER_NUMBER order by BILANZSTICHTAG desc nulls last) as NBR
        from (
                select * from AIRCRAFT_REC_DATA
                    union all
                select * from CLIENT_TO_AIRLINE
              ) as BB
        left join NLB.IWHS_KUNDE_CURRENT as CLIENT_DATA_IWHS on 'NLB_' || BORROWERID =  AIRLINE_CUSTOMER_NUMBER and BB.CUTOFFDATE= CLIENT_DATA_IWHS.CUTOFFDATE
        where CLIENT_DATA_IWHS.CUTOFFDATE is not NULL
    ),
    AIRCRAFT_PRE_FINISH as (
        select
            KD_NR
            ,CUTOFFDATE                                                          as CUT_OFF_DATE
            ,AIRLINE_CUSTOMER_NUMBER                                             as AIRLINE_ID
            , CURRENCY                                                           as AIRLINE_BALANCESHEET_CURRENCY_ISO
            ,EBITDA_9320                                                         as AIRLINE_BALANCESHEET_EBITDA
            ,BILANZSTICHTAG                                                      as AIRLINE_BALANCESHEET_DATE
            , TRANSACTION_VOLUME                                                 as AIRLINE_BALANCESHEET_UMSATZ
            ,COUNTRY                                                             as AIRLINE_COUNTRY
            , CAPITAL_STOCK                                                      as AIRLINE_BALANCESHEET_SHARE_CAPITAL
            ,ROW_NUMBER() over (PARTITION BY KD_NR order by BILANZSTICHTAG desc) as NBR
        from PRE_AA_REC as PAP where NBR = 1  -- row_number() over (partition by AIRLINE_CUSTOMER_NUMBER order by BILANZSTICHTAG desc nulls last)
    ),
    GUARANTOR_INFORMATION as (
        select DISTINCT CUTOFFDATE, KUNDENNUMMER, RECOURSE
        from NLB.MI_GUARANTOR_INFORMATION
        union all
        select DISTINCT CUTOFFDATE, KUNDENNUMMER, RECOURSE
        from BLB.MI_GUARANTOR_INFORMATION
        union all
        select DISTINCT CUTOFFDATE, KUNDENNUMMER, RECOURSE
        from ANL.MI_GUARANTOR_INFORMATION
        union all
        select distinct CUTOFFDATE, KD_NR, RECOURSE
        from AIRCRAFT_REC_BASIS
    ),
    AIRLINES_PRE as (
        select AIRCRAFT_PRE_FINISH.*,
               CASE
                   when lower(RECOURSE) = 'ja' then 1
                   when lower(RECOURSE) = 'nein' then 0
                   else RECOURSE
                end         as RECOURSE
        from AIRCRAFT_PRE_FINISH
        left join GUARANTOR_INFORMATION as RECC on RECC.KUNDENNUMMER = AIRCRAFT_PRE_FINISH.KD_NR and RECC.CUTOFFDATE = AIRCRAFT_PRE_FINISH.CUT_OFF_DATE
    ),
    -- Distinkte Fluggesellschaften + Informationen
    AIRLINES as (
        select distinct
            CUT_OFF_DATE                                    AS CUT_OFF_DATE,                -- Stichtag
            LEFT(KD_NR,3)                                   AS CLIENT_BRANCH,        -- Institut des Schuldners/Kreditnehmers
            SUBSTRING(KD_NR,5,LENGTH(KD_NR)-4)              AS CLIENT_ID,     -- Kundennummer des Schuldners/Kreditnehmers
            LEFT(AIRLINE_ID,3)                              AS AIRLINE_BRANCH,      -- Institut des Bürgen
            SUBSTRING(AIRLINE_ID,5,LENGTH(AIRLINE_ID)-4)    AS AIRLINE_CLIENT_ID,   -- Kundennummer des Bürgen
            AIRLINE_BALANCESHEET_CURRENCY_ISO               AS AIRLINE_BALANCESHEET_CURRENCY_ISO,   -- Währung der Geld-Felder
            AIRLINE_BALANCESHEET_EBITDA                     AS AIRLINE_BALANCESHEET_EBITDA,         -- EBITDA
            AIRLINE_BALANCESHEET_DATE                       AS AIRLINE_BALANCESHEET_DATE,           -- Bilanzstichtag
            AIRLINE_BALANCESHEET_UMSATZ                     AS AIRLINE_BALANCESHEET_TURNOVER_TOTAL, -- Gesammtumsatz
            AIRLINE_COUNTRY                                 AS AIRLINE_BALANCESHEET_COUNTRY_ALPHA2, -- 2-stelliger Ländercode
            AIRLINE_BALANCESHEET_SHARE_CAPITAL              AS AIRLINE_BALANCESHEET_SHARE_CAPITAL,  -- Stammkapital
            RECOURSE                                        AS RECOURSE,                    -- Risikorückbehalt?
            NULL                                            AS RECOURSE_REASON,             -- N.A. (Grund für Risikorückbehalt)
            NBR                                             AS ORDER_NUMBER,                -- Nummer um Einträge (nach Wichtigkeit?) zu sortieren
            'AIRLINE'                                       AS ROLE,                        -- Dies ist eine Fluggesellschaft
            NULL                                            AS COMMENT                      -- N.A. (Kommentar)
        from AIRLINES_PRE
    )
select * from AIRLINES;
------------------------------------------------------------------------------------------------------------------------
