--TABELLEN FUER DIE CI ERSTELLEN, DA DIESE IN FACILITY_11_INSTRUMENT GEBRAUCHT WERDEN, ABER ERST IN 07_COLLATERALIZATION angelegt

call STG.TEST_PROC_BACKUP_AND_DROP('AMC','TABLE_ASSET_CURRENT');
create table AMC.TABLE_ASSET_CURRENT (
    CUT_OFF_DATE DATE,
    ASSET_ID VARCHAR(64),
    ASSET_TYPE VARCHAR(500),
    ASSET_DESCRIPTION VARCHAR(500),
    BRANCH VARCHAR(50),
    NOMINAL_VALUE_EUR DOUBLE,
    NOMINAL_VALUE_OC DOUBLE,
    NOMINAL_VALUE_CURRENCY VARCHAR(50),
    ASSET_VALUE_EUR DOUBLE,
    ASSET_VALUE_OC DOUBLE,
    ASSET_VALUE_CURRENCY VARCHAR(50),
    LTV_RATIO_DENOMINATOR DOUBLE,
    LTV_LIMIT_1_PERCENT DOUBLE,
    LTV_LIMIT_1 VARCHAR(50),
    LTV_LIMIT_REAL_PERCENT DOUBLE,
    LTV_LIMIT_REAL DOUBLE,
    LTV_LIMIT_PERS_PERCENT DOUBLE,
    LTV_LIMIT_PERS DOUBLE,
    LTV_LIMIT_ECON_PERCENT DOUBLE,
    LTV_LIMIT_ECON DOUBLE,
    VO_KUST BIGINT,
    VO_VOE BIGINT,
    VO_CRR_KZ VARCHAR(500),
    BUILDING_TYPE VARCHAR(32),
    COVER_STOCK_RELEVANCE VARCHAR(500),
    SOURCE VARCHAR(50),
    CREATED_USER VARCHAR(128) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP NOT NULL
);
call STG.TEST_PROC_LOAD_AND_DROP_BACKUP_FOR('AMC','TABLE_ASSET_CURRENT');
------------------------------------------------------------------------------------------------------------------------

-- SWITCH erstellen
------------------------------------------------------------------------------------------------------------------------
call STG.TEST_PROC_DROP_AND_CREATE_SWITCH('AMC','TABLE_ASSET_CURRENT');
------------------------------------------------------------------------------------------------------------------------


