-- View erstellen
drop view CALC.VIEW_CUSTOMER_EBA;
-- Haupttabelle Customer EBA
create or replace view CALC.VIEW_CUSTOMER_EBA as
with
-- CUT_OFF_DATE
COD as (
    select CUT_OFF_DATE
    from CALC.AUTO_TABLE_CUTOFFDATES
    where IS_ACTIVE
),
---- Quelldaten
PWC_CUST as (
    select *, CLIENT_ID_TXT as GNI_KUNDE
    from CALC.SWITCH_CLIENT_ACCOUNTHOLDER_CURRENT
    where CUT_OFF_DATE = (select CUT_OFF_DATE from COD)
),
SCRM_CUST as (
    select *
    from CALC.SWITCH_CLIENT_SAP_CRM_CUSTOMER_EBA_CURRENT
    where CUT_OFF_DATE = (select CUT_OFF_DATE from COD)
),
EBIL_GF_CUST as (
    select *
    from CALC.SWITCH_CLIENT_EBIL_GLOBAL_FORMAT_EBA_CURRENT
    where CUT_OFF_DATE = (select CUT_OFF_DATE from COD)
),
LBRT_CUST as (
    select *
    from CALC.SWITCH_CLIENT_LBRATING_EBA_CURRENT
    where CUT_OFF_DATE = (select CUT_OFF_DATE from COD)
),
IWHS_CUST as (
    select *
    from CALC.SWITCH_CLIENT_IWHS_KUNDE_EBA_CURRENT
    where CUT_OFF_DATE = (select CUT_OFF_DATE from COD)
),
-- Alles zusammenführen
FINAL as (
    select distinct PWC.CUT_OFF_DATE,
                    PWC.GNI_KUNDE,
                    SCRM.GUID_EINES_GESCHAEFTSPARTNERS                                                                     as SAP_CRM_GUID_EINES_GESCHAEFTSPARTNERS,
                    SCRM.PARTNERTYP                                                                                        as SAP_CRM_PARTNERTYP,
                    SCRM.PARTNERART                                                                                        as SAP_CRM_PARTNERART,
                    SCRM.KUNDE_NAME                                                                                        as SAP_CRM_KUNDE_NAME,
                    SCRM.KUNDE_NAME_KWG_PARAGRAPH24                                                                        as SAP_CRM_KUNDE_NAME_KWG_PARAGRAPH24,
                    SCRM.LAND_DER_RECHTSFORM                                                                               as SAP_CRM_LAND_DER_RECHTSFORM,
                    SCRM.RECHTSFORM_SCHLUESSEL                                                                             as SAP_CRM_RECHTSFORM_SCHLUESSEL,
                    SCRM.BUBA_WIRTSCHAFTSZWEIG                                                                             as SAP_CRM_BUBA_WIRTSCHAFTSZWEIG,
                    SCRM.KONSOLIDIERUNGSEINHEIT                                                                            as SAP_CRM_KONSOLIDIERUNGSEINHEIT,
                    SCRM.BILANZTYP                                                                                         as SAP_CRM_BILANZTYP,
                    SCRM.QUELLE                                                                                            as SAP_CRM_QUELLE,
                    SCRM.ENDE_GESCHAEFTSJAHR                                                                               as SAP_CRM_ENDE_GESCHAEFTSJAHR,
                    SCRM.MITARBEITERANZAHL                                                                                 as SAP_CRM_MITARBEITERANZAHL,
                    SCRM.BILANZSUMME                                                                                       as SAP_CRM_BILANZSUMME,
                    SCRM.JAHRESUMSATZ                                                                                      as SAP_CRM_JAHRESUMSATZ,
                    SCRM.CURRENCY_OC                                                                                       as SAP_CRM_CURRENCY_OC,
                    SCRM.CURRENCY                                                                                          as SAP_CRM_CURRENCY,
                    SCRM.LTA_RELEVANZ                                                                                      as SAP_CRM_LTA_RELEVANZ,
                    SCRM.LTA_BEGRUENDUNG                                                                                   as SAP_CRM_LTA_BEGRUENDUNG,
                    SCRM.LTA_ERMITTLUNGSDATUM                                                                              as SAP_CRM_LTA_ERMITTLUNGSDATUM,
                    SCRM.LTA_RATIO                                                                                         as SAP_CRM_LTA_RATIO,
                    SCRM.LTA_CONDITIONS_NOT_FULFILLED                                                                      as SAP_CRM_LTA_CONDITIONS_NOT_FULFILLED,
                    SCRM.LTA_RESULT_TYPE                                                                                   as SAP_CRM_LTA_RESULT_TYPE,
                    SCRM.LTA_FC_LEVE_RATIO                                                                                 as SAP_CRM_LTA_FC_LEVE_RATIO,
                    SCRM.LTA_FC_INT_COVER                                                                                  as SAP_CRM_LTA_FC_INT_COVER,
                    SCRM.LTA_FC_DEBTSERVCR                                                                                 as SAP_CRM_LTA_FC_DEBTSERVCR,
                    SCRM.LTA_FC_CAP_EXPLIM                                                                                 as SAP_CRM_LTA_FC_CAP_EXPLIM,
                    SCRM.LTA_INC_STYLE_COV                                                                                 as SAP_CRM_LTA_INC_STYLE_COV,
                    SCRM.GVK_FLAG                                                                                          as SAP_CRM_GVK_FLAG,
                    SCRM.GVK                                                                                               as SAP_CRM_GVK,
                    EBGF.AKTUELLER_STICHTAG_KB                                                                             as GF_EBIL_AKTUELLER_STICHTAG_KB,
                    EBGF.AKTUELLER_STICHTAG_EB                                                                             as GF_EBIL_AKTUELLER_STICHTAG_EB,
                    EBGF.SOURCE                                                                                            as GF_EBIL_SOURCE,
                    EBGF.KB_VON_PARENTCUSTOMER                                                                             as GF_EBIL_KB_VON_PARENTCUSTOMER,
                    EBGF.CURRENCY_OC_KB                                                                                    as GF_EBIL_CURRENCY_OC_KB,
                    EBGF.CURRENCY_OC_EB                                                                                    as GF_EBIL_CURRENCY_OC_EB,
                    EBGF.CURRENCY                                                                                          as GF_EBIL_CURRENCY,
                    EBGF.BRUTTO_HAFTKAPITAL                                                                                as GF_EBIL_BRUTTO_HAFTKAPITAL,
                    EBGF.GRP_BRUTTO_HAFTKAPITAL                                                                            as GF_EBIL_GRP_BRUTTO_HAFTKAPITAL,
                    EBGF.EIGENKAPITAL                                                                                      as GF_EBIL_EIGENKAPITAL,
                    EBGF.GRP_EIGENKAPITAL                                                                                  as GF_EBIL_GRP_EIGENKAPITAL,
                    EBGF.JAHRESUMSATZ                                                                                      as GF_EBIL_JAHRESUMSATZ,
                    EBGF.GRP_JAHRESUMSATZ                                                                                  as GF_EBIL_GRP_JAHRESUMSATZ,
                    EBGF.RECHTSFORM                                                                                        as GF_EBIL_RECHTSFORM,
                    EBGF.GRP_RECHTSFORM                                                                                    as GF_EBIL_GRP_RECHTSFORM,
                    EBGF.SACHANLAGEN                                                                                       as GF_EBIL_SACHANLAGEN,
                    EBGF.GRP_SACHANLAGEN                                                                                   as GF_EBIL_GRP_SACHANLAGEN,
                    EBGF.EBITDA                                                                                            as GF_EBIL_EBITDA,
                    EBGF.GRP_EBITDA                                                                                        as GF_EBIL_GRP_EBITDA,
                    EBGF.GOODWILL                                                                                          as GF_EBIL_GOODWILL,
                    EBGF.GRP_GOODWILL                                                                                      as GF_EBIL_GRP_GOODWILL,
                    EBGF.NETTO_FINANZSCHULDEN_EBITDA                                                                       as GF_EBIL_NETTO_FINANZSCHULDEN_EBITDA,
                    EBGF.GRP_NETTO_FINANZSCHULDEN_EBITDA                                                                   as GF_EBIL_GRP_NETTO_FINANZSCHULDEN_EBITDA,
                    EBGF.ZINSAUFWAND                                                                                       as GF_EBIL_ZINSAUFWAND,
                    EBGF.GRP_ZINSAUFWAND                                                                                   as GF_EBIL_GRP_ZINSAUFWAND,
                    EBGF.DSCR                                                                                              as GF_EBIL_DSCR,
                    EBGF.GRP_DSCR                                                                                          as GF_EBIL_GRP_DSCR,
                    EBGF.ANLAGEVERMOEGEN_BRUTTOHAFTKAPITAL                                                                 as GF_EBIL_ANLAGEVERMOEGEN_BRUTTOHAFTKAPITAL,
                    EBGF.GRP_ANLAGEVERMOEGEN_BRUTTOHAFTKAPITAL                                                             as GF_EBIL_GRP_ANLAGEVERMOEGEN_BRUTTOHAFTKAPITAL,
                    EBGF.BELEGUNGSRATE                                                                                     as GF_EBIL_BELEGUNGSRATE,
                    EBGF.GRP_BELEGUNGSRATE                                                                                 as GF_EBIL_GRP_BELEGUNGSRATE,
                    EBGF.DSCR_GEWERBEIMMOBILIEN                                                                            as GF_EBIL_DSCR_GEWERBEIMMOBILIEN,
                    EBGF.GRP_DSCR_GEWERBEIMMOBILIEN                                                                        as GF_EBIL_GRP_DSCR_GEWERBEIMMOBILIEN,
                    EBGF.DECKUNGSQUOTE                                                                                     as GF_EBIL_DECKUNGSQUOTE,
                    EBGF.GRP_DECKUNGSQUOTE                                                                                 as GF_EBIL_GRP_DECKUNGSQUOTE,
                    EBGF.DYNAMISCHER_VERSCHULDUNGSGRAD                                                                     as GF_EBIL_DYNAMISCHER_VERSCHULDUNGSGRAD,
                    EBGF.GRP_DYNAMISCHER_VERSCHULDUNGSGRAD                                                                 as GF_EBIL_GRP_DYNAMISCHER_VERSCHULDUNGSGRAD,
                    EBGF.GELDUMSCHLAGSDAUER_TAGE                                                                           as GF_EBIL_GELDUMSCHLAGSDAUER_TAGE,
                    EBGF.GRP_GELDUMSCHLAGSDAUER_TAGE                                                                       as GF_EBIL_GRP_GELDUMSCHLAGSDAUER_TAGE,
                    EBGF.KAPITALDIENST                                                                                     as GF_EBIL_KAPITALDIENST,
                    EBGF.GRP_KAPITALDIENST                                                                                 as GF_EBIL_GRP_KAPITALDIENST,
                    EBGF.SCHULDENRENDITE                                                                                   as GF_EBIL_SCHULDENRENDITE,
                    EBGF.GRP_SCHULDENRENDITE                                                                               as GF_EBIL_GRP_SCHULDENRENDITE,
                    EBGF.ANZAHL_MITARBEITER                                                                                as GF_EBIL_ANZAHL_MITARBEITER,
                    EBGF.GRP_ANZAHL_MITARBEITER                                                                            as GF_EBIL_GRP_ANZAHL_MITARBEITER,
                    EBGF.BETRIEBSERGEBNIS                                                                                  as GF_EBIL_BETRIEBSERGEBNIS,
                    EBGF.GRP_BETRIEBSERGEBNIS                                                                              as GF_EBIL_GRP_BETRIEBSERGEBNIS,
                    EBGF.BILANZSUMME                                                                                       as GF_EBIL_BILANZSUMME,
                    EBGF.GRP_BILANZSUMME                                                                                   as GF_EBIL_GRP_BILANZSUMME,
                    EBGF.BRUTTOVERSCHULDUNGSGRAD                                                                           as GF_EBIL_BRUTTOVERSCHULDUNGSGRAD,
                    EBGF.GRP_BRUTTOVERSCHULDUNGSGRAD                                                                       as GF_EBIL_GRP_BRUTTOVERSCHULDUNGSGRAD,
                    EBGF.EBIT                                                                                              as GF_EBIL_EBIT,
                    EBGF.GRP_EBIT                                                                                          as GF_EBIL_GRP_EBIT,
                    EBGF.LEVERAGE_RATIO                                                                                    as GF_EBIL_LEVERAGE_RATIO,
                    EBGF.GRP_LEVERAGE_RATIO                                                                                as GF_EBIL_GRP_LEVERAGE_RATIO,
                    EBGF.EIGENKAPITAL_QUOTE                                                                                as GF_EBIL_EIGENKAPITAL_QUOTE,
                    EBGF.GRP_EIGENKAPITAL_QUOTE                                                                            as GF_EBIL_GRP_EIGENKAPITAL_QUOTE,
                    EBGF.EKRENTABILITAET                                                                                   as GF_EBIL_EKRENTABILITAET,
                    EBGF.GRP_EKRENTABILITAET                                                                               as GF_EBIL_GRP_EKRENTABILITAET,
                    EBGF.EVENTUALVERBINDLICHKEITEN                                                                         as GF_EBIL_EVENTUALVERBINDLICHKEITEN,
                    EBGF.GRP_EVENTUALVERBINDLICHKEITEN                                                                     as GF_EBIL_GRP_EVENTUALVERBINDLICHKEITEN,
                    EBGF.GESAMTFINANZSCHULDEN                                                                              as GF_EBIL_GESAMTFINANZSCHULDEN,
                    EBGF.GRP_GESAMTFINANZSCHULDEN                                                                          as GF_EBIL_GRP_GESAMTFINANZSCHULDEN,
                    EBGF.GESAMTKAPITALRENDITE_VOR_STEUERN                                                                  as GF_EBIL_GESAMTKAPITALRENDITE_VOR_STEUERN,
                    EBGF.GRP_GESAMTKAPITALRENDITE_VOR_STEUERN                                                              as GF_EBIL_GRP_GESAMTKAPITALRENDITE_VOR_STEUERN,
                    EBGF.SACHANLAGEVERMOEGEN_UMSATZ                                                                        as GF_EBIL_SACHANLAGEVERMOEGEN_UMSATZ,
                    EBGF.GRP_SACHANLAGEVERMOEGEN_UMSATZ                                                                    as GF_EBIL_GRP_SACHANLAGEVERMOEGEN_UMSATZ,
                    EBGF.NETTO_HAFTKAPITAL_QUOTE                                                                           as GF_EBIL_NETTO_HAFTKAPITAL_QUOTE,
                    EBGF.GRP_NETTO_HAFTKAPITAL_QUOTE                                                                       as GF_EBIL_GRP_NETTO_HAFTKAPITAL_QUOTE,
                    EBGF.UMSATZRENTABILITAET                                                                               as GF_EBIL_UMSATZRENTABILITAET,
                    EBGF.GRP_UMSATZRENTABILITAET                                                                           as GF_EBIL_GRP_UMSATZRENTABILITAET,
                    EBGF.NETTO_VERSCHULDUNGSGRAD                                                                           as GF_EBIL_NETTO_VERSCHULDUNGSGRAD,
                    EBGF.GRP_NETTO_VERSCHULDUNGSGRAD                                                                       as GF_EBIL_GRP_NETTO_VERSCHULDUNGSGRAD,
                    EBGF.SUMME_MFR_LFR_FREMDKAPITAL                                                                        as GF_EBIL_SUMME_MFR_LFR_FREMDKAPITAL,
                    EBGF.GRP_SUMME_MFR_LFR_FREMDKAPITAL                                                                    as GF_EBIL_GRP_SUMME_MFR_LFR_FREMDKAPITAL,
                    EBGF.UMSATZENTWICKLUNG                                                                                 as GF_EBIL_UMSATZENTWICKLUNG,
                    EBGF.GRP_UMSATZENTWICKLUNG                                                                             as GF_EBIL_GRP_UMSATZENTWICKLUNG,
                    EBGF.ZINSDECKUNGSQUOTE                                                                                 as GF_EBIL_ZINSDECKUNGSQUOTE,
                    EBGF.GRP_ZINSDECKUNGSQUOTE                                                                             as GF_EBIL_GRP_ZINSDECKUNGSQUOTE,
                    EBGF.AUSSCHUETTUNG                                                                                     as GF_EBIL_AUSSCHUETTUNG,
                    EBGF.GRP_AUSSCHUETTUNG                                                                                 as GF_EBIL_GRP_AUSSCHUETTUNG,
                    EBGF.NETTO_FINANZSCHULDEN                                                                              as GF_EBIL_NETTO_FINANZSCHULDEN,
                    EBGF.GRP_NETTO_FINANZSCHULDEN                                                                          as GF_EBIL_GRP_NETTO_FINANZSCHULDEN,
                    EBGF.CASHFLOWKENNZAHL1                                                                                 as GF_EBIL_CASHFLOWKENNZAHL1,
                    EBGF.GRP_CASHFLOWKENNZAHL1                                                                             as GF_EBIL_GRP_CASHFLOWKENNZAHL1,
                    EBGF.CASHFLOWERFOLGSWIRKSERWEITERT                                                                     as GF_EBIL_CASHFLOWERFOLGSWIRKSERWEITERT,
                    EBGF.GRP_CASHFLOWERFOLGSWIRKSERWEITERT                                                                 as GF_EBIL_GRP_CASHFLOWERFOLGSWIRKSERWEITERT,
                    EBGF.SENSITIVIERTGESAMTSCHULDENDIENSTDECKUNGSQUOTE                                                     as GF_EBIL_SENSITIVIERTGESAMTSCHULDENDIENSTDECKUNGSQUOTE,
                    EBGF.GRP_SENSITIVIERTGESAMTSCHULDENDIENSTDECKUNGSQUOTE                                                 as GF_EBIL_GRP_SENSITIVIERTGESAMTSCHULDENDIENSTDECKUNGSQUOTE,
                    EBGF.KAPITALDIENSTGRENZEVORERSATZINVEST                                                                as GF_EBIL_KAPITALDIENSTGRENZEVORERSATZINVEST,
                    EBGF.GRP_KAPITALDIENSTGRENZEVORERSATZINVEST                                                            as GF_EBIL_GRP_KAPITALDIENSTGRENZEVORERSATZINVEST,
                    EBGF.TESTATART                                                                                         as GF_EBIL_TESTATART,
                    EBGF.GRP_TESTATART                                                                                     as GF_EBIL_GRP_TESTATART,
                    EBGF.RETURNONCAPITALEMPLOYED                                                                           as GF_EBIL_RETURNONCAPITALEMPLOYED,
                    EBGF.GRP_RETURNONCAPITALEMPLOYED                                                                       as GF_EBIL_GRP_RETURNONCAPITALEMPLOYED,
                    LBRT.RAT_BUS_ID                                                                                        as LBRATING_RAT_BUS_ID,
                    LBRT.SOURCE                                                                                            as LBRATING_SOURCE,
                    LBRT.PRESUM_STRAT_TXT                                                                                  as LBRATING_PRESUM_STRAT_TXT,
                    LBRT.PRESUM_STRAT_STATE                                                                                as LBRATING_PRESUM_STRAT_STATE,
                    LBRT.NEG_DIV_TXT                                                                                       as LBRATING_NEG_DIV_TXT,
                    LBRT.NEG_DIV_STATE                                                                                     as LBRATING_NEG_DIV_STATE,
                    LBRT.COMP_EXPECT_TXT                                                                                   as LBRATING_COMP_EXPECT_TXT,
                    LBRT.EXPECT_STATE                                                                                      as LBRATING_EXPECT_STATE,
                    LBRT.BANK_EXPECT_TXT                                                                                   as LBRATING_BANK_EXPECT_TXT,
                    LBRT.INFLUENCE_TXT                                                                                     as LBRATING_INFLUENCE_TXT,
                    LBRT.INFLUENCE_STATE                                                                                   as LBRATING_INFLUENCE_STATE,
                    LBRT.SENSITIV_TXT                                                                                      as LBRATING_SENSITIV_TXT,
                    LBRT.SENSITIV_STATE                                                                                    as LBRATING_SENSITIV_STATE,
                    LBRT.INFO_TXT                                                                                          as LBRATING_INFO_TXT,
                    LBRT.INFO_STATE                                                                                        as LBRATING_INFO_STATE,
                    LBRT.DEPENDENCY_TXT                                                                                    as LBRATING_DEPENDENCY_TXT,
                    LBRT.DEPENDENCY_STATE                                                                                  as LBRATING_DEPENDENCY_STATE,
                    LBRT.CURRENCYRISK_TXT                                                                                  as LBRATING_CURRENCYRISK_TXT,
                    LBRT.CURRENCYRISK_STATE                                                                                as LBRATING_CURRENCYRISK_STATE,
                    LBRT.ORIENTATION_TXT                                                                                   as LBRATING_ORIENTATION_TXT,
                    LBRT.ORIENTATION_STATE                                                                                 as LBRATING_ORIENTATION_STATE,
                    LBRT.IN_PROFESSIONALISM_TXT                                                                            as LBRATING_IN_PROFESSIONALISM_TXT,
                    LBRT.DEBTOR_ASSETS_TXT                                                                                 as LBRATING_DEBTOR_ASSETS_TXT,
                    LBRT.FINANCE_SITUATION_TXT                                                                             as LBRATING_FINANCE_SITUATION_TXT,
                    LBRT.INVEST_ACTIVITY_TXT                                                                               as LBRATING_INVEST_ACTIVITY_TXT,
                    LBRT.LIQUID_SITUATION_TXT                                                                              as LBRATING_LIQUID_SITUATION_TXT,
                    LBRT.SUPPORT_PROVIDED_TXT                                                                              as LBRATING_SUPPORT_PROVIDED_TXT,
                    LBRT.DEBTOR_SUPPORT_TXT                                                                                as LBRATING_DEBTOR_SUPPORT_TXT,
                    LBRT.CUST_QUAL_STATE                                                                                   as LBRATING_CUST_QUAL_STATE,
                    LBRT.HQF_DAUKUNBEZ_695                                                                                 as LBRATING_HQF_DAUKUNBEZ_695,
                    LBRT.WQF_ZUVERLAESSIGKEIT_2763_TXT                                                                     as LBRATING_WQF_ZUVERLAESSIGKEIT_2763_TXT,
                    LBRT.WQF_INFOBEREITSCH_2758_TXT                                                                        as LBRATING_WQF_INFOBEREITSCH_2758_TXT,
                    LBRT.WQF_UNTERNEHMENTW_2748_TXT                                                                        as LBRATING_WQF_UNTERNEHMENTW_2748_TXT,
                    LBRT.WQF_MANAGEMENT_SIR_2743_TXT                                                                       as LBRATING_WQF_MANAGEMENT_SIR_2743_TXT,
                    LBRT.HQF_VERKAUFSSTAND_2792_TXT                                                                        as LBRATING_HQF_VERKAUFSSTAND_2792_TXT,
                    LBRT.WQF_FINANZBEREICH_2778_TXT                                                                        as LBRATING_WQF_FINANZBEREICH_2778_TXT,
                    LBRT.WQF_VRTRBVRMRKTNG_2773_TXT                                                                        as LBRATING_WQF_VRTRBVRMRKTNG_2773_TXT,
                    LBRT.WQF_BAUQUALITAET_2768_TXT                                                                         as LBRATING_WQF_BAUQUALITAET_2768_TXT,
                    LBRT.WQF_LIQUIDITAET_5511_TXT                                                                          as LBRATING_WQF_LIQUIDITAET_5511_TXT,
                    IWHS.ORG_RECHTSFORM                                                                                    as IWHS_ORG_RECHTSFORM,
                    IWHS.PERSONEN_ART                                                                                      as IWHS_PERSONEN_ART,
                    IWHS.WIRTSCH_ZWEIG                                                                                     as IWHS_WIRTSCH_ZWEIG,
                    IWHS.MWSN_NACE_CODE                                                                                    as IWHS_MWSN_NACE_CODE,
                    IWHS.KUSY_DSGV_NEU                                                                                     as IWHS_KUSY_DSGV_NEU,
                    IWHS.GEBURTS_GRUENDUNGS_DAT                                                                            as IWHS_GEBURTS_GRUENDUNGS_DAT,
                    IWHS.BERUFL_STELLUNG                                                                                   as IWHS_BERUFL_STELLUNG,
                    IWHS.BERUF_BRANCHE                                                                                     as IWHS_BERUF_BRANCHE,
                    IWHS.STRASSE                                                                                           as IWHS_STRASSE,
                    IWHS.HAUSNR                                                                                            as IWHS_HAUSNR,
                    IWHS.POSTLEITZAHL                                                                                      as IWHS_POSTLEITZAHL,
                    IWHS.ORT                                                                                               as IWHS_ORT,
                    IWHS.LAND                                                                                              as IWHS_LAND,
                    IWHS.FUEHRENDE_BONITAET                                                                                as IWHS_FUEHRENDE_BONITAET,
                    IWHS.SCHUFA_AUSKUNFT                                                                                   as IWHS_SCHUFA_AUSKUNFT,
                    IWHS.SCHUFA_NEGATIVMERKMAL                                                                             as IWHS_SCHUFA_NEGATIVMERKMAL,
                    IWHS.SCHUFA_SCORING_WERT                                                                               as IWHS_SCHUFA_SCORING_WERT,
                    IWHS.LETZTE_AENDERUNG                                                                                  as IWHS_LETZTE_AENDERUNG,
                    IWHS.TREIBHAUSGASEMISSIONEN_KUNDEN_SCORE                                                               as IWHS_TREIBHAUSGASEMISSIONEN_KUNDEN_SCORE,
                    IWHS.TREIBHAUSGASEMISSIONEN_BRANCHEN_SCORE                                                             as IWHS_TREIBHAUSGASEMISSIONEN_BRANCHEN_SCORE,
                    IWHS.WASSEREINSATZ_KUNDEN_SCORE                                                                        as IWHS_WASSEREINSATZ_KUNDEN_SCORE,
                    IWHS.WASSEREINSATZ_BRANCHEN_SCORE                                                                      as IWHS_WASSEREINSATZ_BRANCHEN_SCORE,
                    IWHS.GERINGFUEGIGE_BESCHAEFTIGUNG_KUNDEN_SCORE                                                         as IWHS_GERINGFUEGIGE_BESCHAEFTIGUNG_KUNDEN_SCORE,
                    IWHS.GERINGFUEGIGE_BESCHAEFTIGUNG_BRANCHEN_SCORE                                                       as IWHS_GERINGFUEGIGE_BESCHAEFTIGUNG_BRANCHEN_SCORE,
                    IWHS.LEIHARBEIT_KUNDEN_SCORE                                                                           as IWHS_LEIHARBEIT_KUNDEN_SCORE,
                    IWHS.LEIHARBEIT_BRANCHEN_SCORE                                                                         as IWHS_LEIHARBEIT_BRANCHEN_SCORE,
                    IWHS.GENDER_PAY_GAP_KUNDEN_SCORE                                                                       as IWHS_GENDER_PAY_GAP_KUNDEN_SCORE,
                    IWHS.GENDER_PAY_GAP_BRANCHEN_SCORE                                                                     as IWHS_GENDER_PAY_GAP_BRANCHEN_SCORE,
                    IWHS.AKUTE_PHYSISCHE_RISIKEN_HOCHWASSER_KUNDEN_SCORE                                                   as IWHS_AKUTE_PHYSISCHE_RISIKEN_HOCHWASSER_KUNDEN_SCORE,
                    IWHS.AKUTE_PHYSISCHE_RISIKEN_HOCHWASSER_BRANCHEN_SCORE                                                 as IWHS_AKUTE_PHYSISCHE_RISIKEN_HOCHWASSER_BRANCHEN_SCORE,
                    IWHS.CHRONISCHE_PHYSISCHE_RISIKEN_BIODIVERSITAET_KUNDEN_SCORE                                          as IWHS_CHRONISCHE_PHYSISCHE_RISIKEN_BIODIVERSITAET_KUNDEN_SCORE,
                    IWHS.CHRONISCHE_PHYSISCHE_RISIKEN_BIODIVERSITAET_BRANCHEN_SCORE                                        as IWHS_CHRONISCHE_PHYSISCHE_RISIKEN_BIODIVERSITAET_BRANCHEN_SCORE,
                    IWHS.WANDLUNGSFAEHIGKEIT_KLIMANEUTRALITAET_KUNDEN_SCORE                                                as IWHS_WANDLUNGSFAEHIGKEIT_KLIMANEUTRALITAET_KUNDEN_SCORE,
                    IWHS.WANDLUNGSFAEHIGKEIT_KLIMANEUTRALITAET_BRANCHEN_SCORE                                              as IWHS_WANDLUNGSFAEHIGKEIT_KLIMANEUTRALITAET_BRANCHEN_SCORE,
                    IWHS.SOZIALE_STANDARDS_VERSTOESSE_GEGEN_MENSCHENRECHTE_ENTLANG_DER_WERTSCHOEPFUNGSKETTE_KUNDEN_SCORE   as IWHS_SOZIALE_STANDARDS_VERSTOESSE_GEGEN_MENSCHENRECHTE_ENTLANG_DER_WERTSCHOEPFUNGSKETTE_KUNDEN_SCORE,
                    IWHS.SOZIALE_STANDARDS_VERSTOESSE_GEGEN_MENSCHENRECHTE_ENTLANG_DER_WERTSCHOEPFUNGSKETTE_BRANCHEN_SCORE as IWHS_SOZIALE_STANDARDS_VERSTOESSE_GEGEN_MENSCHENRECHTE_ENTLANG_DER_WERTSCHOEPFUNGSKETTE_BRANCHEN_SCORE,
                    IWHS.ORGANISATORISCHE_INTEGRATION_VON_NACHHALTIGKEIT_KUNDEN_SCORE                                      as IWHS_ORGANISATORISCHE_INTEGRATION_VON_NACHHALTIGKEIT_KUNDEN_SCORE,
                    IWHS.ORGANISATORISCHE_INTEGRATION_VON_NACHHALTIGKEIT_BRANCHEN_SCORE                                    as IWHS_ORGANISATORISCHE_INTEGRATION_VON_NACHHALTIGKEIT_BRANCHEN_SCORE,
                    IWHS.GEFAEHRLICHER_ABFALL_KUNDEN_SCORE                                                                 as IWHS_GEFAEHRLICHER_ABFALL_KUNDEN_SCORE,
                    IWHS.GEFAEHRLICHER_ABFALL_BRANCHEN_SCORE                                                               as IWHS_GEFAEHRLICHER_ABFALL_BRANCHEN_SCORE,
                    IWHS.VERSTOESSE_GEGEN_EINE_ORDNUNGSGEMAESSE_UNTERNEHMENSFUEHRUNG_KUNDEN_SCORE                          as IWHS_VERSTOESSE_GEGEN_EINE_ORDNUNGSGEMAESSE_UNTERNEHMENSFUEHRUNG_KUNDEN_SCORE,
                    IWHS.VERSTOESSE_GEGEN_EINE_ORDNUNGSGEMAESSE_UNTERNEHMENSFUEHRUNG_BRANCHEN_SCORE                        as IWHS_VERSTOESSE_GEGEN_EINE_ORDNUNGSGEMAESSE_UNTERNEHMENSFUEHRUNG_BRANCHEN_SCORE,
                    IWHS.HAUPTLEGIMITATION                                                                                 as IWHS_HAUPTLEGIMITATION,
                    IWHS.LEGITIMIERUNGSART                                                                                 as IWHS_LEGITIMIERUNGSART,
                    IWHS.AUSSTELLUNGSDATUM                                                                                 as IWHS_AUSSTELLUNGSDATUM,
                    IWHS.EINTRAGEDATUM_IN_OEFFENTL_REGISTER                                                                as IWHS_EINTRAGEDATUM_IN_OEFFENTL_REGISTER,
                    IWHS.ABLAUFDATUM_DER_LEGITIMATION                                                                      as IWHS_ABLAUFDATUM_DER_LEGITIMATION,
                    IWHS.LEGITIMATIONSNUMMER                                                                               as IWHS_LEGITIMATIONSNUMMER,
                    IWHS.AUSSTELLENDE_BEHOERDE                                                                             as IWHS_AUSSTELLENDE_BEHOERDE,
                    IWHS.AUSSTELLUNGSORT                                                                                   as IWHS_AUSSTELLUNGSORT,
                    IWHS.STEUERLICH_ALS_AUSLAENDER_ZU_BEHANDELN                                                            as IWHS_STEUERLICH_ALS_AUSLAENDER_ZU_BEHANDELN,
                    IWHS.ROLLE_FINANZSSANKTIONEN                                                                           as IWHS_ROLLE_FINANZSSANKTIONEN,
                    IWHS.GWG_FALL                                                                                          as IWHS_GWG_FALL,
                    IWHS.ABW_WIRT_BERECHTIGTER                                                                             as IWHS_ABW_WIRT_BERECHTIGTER
    from PWC_CUST PWC
             left join SCRM_CUST SCRM on PWC.GNI_KUNDE = SCRM.GNI_KUNDE
             left join EBIL_GF_CUST EBGF on PWC.GNI_KUNDE = EBGF.GNI_KUNDE
             left join LBRT_CUST LBRT on PWC.GNI_KUNDE = LBRT.GNI_KUNDE
             left join IWHS_CUST IWHS on PWC.GNI_KUNDE = IWHS.GNI_KUNDE
),
-- Gefiltert nach noetigen Datenfeldern
FINAL_FILTERED as (
    select
        -- Defaults
        CUT_OFF_DATE,
        -- Columns
        NULLIF(GNI_KUNDE, null)                                                                                              as GNI_KUNDE,
        NULLIF(SAP_CRM_GUID_EINES_GESCHAEFTSPARTNERS, null)                                                                  as SAP_CRM_GUID_EINES_GESCHAEFTSPARTNERS,
        NULLIF(SAP_CRM_PARTNERTYP, null)                                                                                     as SAP_CRM_PARTNERTYP,
        NULLIF(SAP_CRM_PARTNERART, null)                                                                                     as SAP_CRM_PARTNERART,
        NULLIF(SAP_CRM_KUNDE_NAME, null)                                                                                     as SAP_CRM_KUNDE_NAME,
        NULLIF(SAP_CRM_KUNDE_NAME_KWG_PARAGRAPH24, null)                                                                     as SAP_CRM_KUNDE_NAME_KWG_PARAGRAPH24,
        NULLIF(SAP_CRM_LAND_DER_RECHTSFORM, null)                                                                            as SAP_CRM_LAND_DER_RECHTSFORM,
        NULLIF(SAP_CRM_RECHTSFORM_SCHLUESSEL, null)                                                                          as SAP_CRM_RECHTSFORM_SCHLUESSEL,
        NULLIF(SAP_CRM_BUBA_WIRTSCHAFTSZWEIG, null)                                                                          as SAP_CRM_BUBA_WIRTSCHAFTSZWEIG,
        NULLIF(SAP_CRM_KONSOLIDIERUNGSEINHEIT, null)                                                                         as SAP_CRM_KONSOLIDIERUNGSEINHEIT,
        NULLIF(SAP_CRM_BILANZTYP, null)                                                                                      as SAP_CRM_BILANZTYP,
        NULLIF(SAP_CRM_QUELLE, null)                                                                                         as SAP_CRM_QUELLE,
        NULLIF(SAP_CRM_ENDE_GESCHAEFTSJAHR, null)                                                                            as SAP_CRM_ENDE_GESCHAEFTSJAHR,
        NULLIF(SAP_CRM_MITARBEITERANZAHL, null)                                                                              as SAP_CRM_MITARBEITERANZAHL,
        NULLIF(SAP_CRM_BILANZSUMME, null)                                                                                    as SAP_CRM_BILANZSUMME,
        NULLIF(SAP_CRM_JAHRESUMSATZ, null)                                                                                   as SAP_CRM_JAHRESUMSATZ,
        NULLIF(SAP_CRM_CURRENCY_OC, null)                                                                                    as SAP_CRM_CURRENCY_OC,
        NULLIF(SAP_CRM_CURRENCY, null)                                                                                       as SAP_CRM_CURRENCY,
        NULLIF(SAP_CRM_LTA_RELEVANZ, null)                                                                                   as SAP_CRM_LTA_RELEVANZ,
        NULLIF(SAP_CRM_LTA_BEGRUENDUNG, null)                                                                                as SAP_CRM_LTA_BEGRUENDUNG,
        NULLIF(SAP_CRM_LTA_ERMITTLUNGSDATUM, null)                                                                           as SAP_CRM_LTA_ERMITTLUNGSDATUM,
        NULLIF(SAP_CRM_LTA_RATIO, null)                                                                                      as SAP_CRM_LTA_RATIO,
        NULLIF(SAP_CRM_LTA_CONDITIONS_NOT_FULFILLED, null)                                                                   as SAP_CRM_LTA_CONDITIONS_NOT_FULFILLED,
        NULLIF(SAP_CRM_LTA_RESULT_TYPE, null)                                                                                as SAP_CRM_LTA_RESULT_TYPE,
        NULLIF(SAP_CRM_LTA_FC_LEVE_RATIO, null)                                                                              as SAP_CRM_LTA_FC_LEVE_RATIO,
        NULLIF(SAP_CRM_LTA_FC_INT_COVER, null)                                                                               as SAP_CRM_LTA_FC_INT_COVER,
        NULLIF(SAP_CRM_LTA_FC_DEBTSERVCR, null)                                                                              as SAP_CRM_LTA_FC_DEBTSERVCR,
        NULLIF(SAP_CRM_LTA_FC_CAP_EXPLIM, null)                                                                              as SAP_CRM_LTA_FC_CAP_EXPLIM,
        NULLIF(SAP_CRM_LTA_INC_STYLE_COV, null)                                                                              as SAP_CRM_LTA_INC_STYLE_COV,
        NULLIF(SAP_CRM_GVK_FLAG, null)                                                                                       as SAP_CRM_GVK_FLAG,
        NULLIF(SAP_CRM_GVK, null)                                                                                            as SAP_CRM_GVK,
        NULLIF(GF_EBIL_AKTUELLER_STICHTAG_KB, null)                                                                          as GF_EBIL_AKTUELLER_STICHTAG_KB,
        NULLIF(GF_EBIL_AKTUELLER_STICHTAG_EB, null)                                                                          as GF_EBIL_AKTUELLER_STICHTAG_EB,
        NULLIF(GF_EBIL_SOURCE, null)                                                                                         as GF_EBIL_SOURCE,
        NULLIF(GF_EBIL_KB_VON_PARENTCUSTOMER, null)                                                                          as GF_EBIL_KB_VON_PARENTCUSTOMER,
        NULLIF(GF_EBIL_CURRENCY_OC_KB, null)                                                                                 as GF_EBIL_CURRENCY_OC_KB,
        NULLIF(GF_EBIL_CURRENCY_OC_EB, null)                                                                                 as GF_EBIL_CURRENCY_OC_EB,
        NULLIF(GF_EBIL_CURRENCY, null)                                                                                       as GF_EBIL_CURRENCY,
        NULLIF(GF_EBIL_BRUTTO_HAFTKAPITAL, null)                                                                             as GF_EBIL_BRUTTO_HAFTKAPITAL,
        NULLIF(GF_EBIL_GRP_BRUTTO_HAFTKAPITAL, null)                                                                         as GF_EBIL_GRP_BRUTTO_HAFTKAPITAL,
        NULLIF(GF_EBIL_EIGENKAPITAL, null)                                                                                   as GF_EBIL_EIGENKAPITAL,
        NULLIF(GF_EBIL_GRP_EIGENKAPITAL, null)                                                                               as GF_EBIL_GRP_EIGENKAPITAL,
        NULLIF(GF_EBIL_JAHRESUMSATZ, null)                                                                                   as GF_EBIL_JAHRESUMSATZ,
        NULLIF(GF_EBIL_GRP_JAHRESUMSATZ, null)                                                                               as GF_EBIL_GRP_JAHRESUMSATZ,
        NULLIF(GF_EBIL_RECHTSFORM, null)                                                                                     as GF_EBIL_RECHTSFORM,
        NULLIF(GF_EBIL_GRP_RECHTSFORM, null)                                                                                 as GF_EBIL_GRP_RECHTSFORM,
        NULLIF(GF_EBIL_SACHANLAGEN, null)                                                                                    as GF_EBIL_SACHANLAGEN,
        NULLIF(GF_EBIL_GRP_SACHANLAGEN, null)                                                                                as GF_EBIL_GRP_SACHANLAGEN,
        NULLIF(GF_EBIL_EBITDA, null)                                                                                         as GF_EBIL_EBITDA,
        NULLIF(GF_EBIL_GRP_EBITDA, null)                                                                                     as GF_EBIL_GRP_EBITDA,
        NULLIF(GF_EBIL_GOODWILL, null)                                                                                       as GF_EBIL_GOODWILL,
        NULLIF(GF_EBIL_GRP_GOODWILL, null)                                                                                   as GF_EBIL_GRP_GOODWILL,
        NULLIF(GF_EBIL_NETTO_FINANZSCHULDEN_EBITDA, null)                                                                    as GF_EBIL_NETTO_FINANZSCHULDEN_EBITDA,
        NULLIF(GF_EBIL_GRP_NETTO_FINANZSCHULDEN_EBITDA, null)                                                                as GF_EBIL_GRP_NETTO_FINANZSCHULDEN_EBITDA,
        NULLIF(GF_EBIL_ZINSAUFWAND, null)                                                                                    as GF_EBIL_ZINSAUFWAND,
        NULLIF(GF_EBIL_GRP_ZINSAUFWAND, null)                                                                                as GF_EBIL_GRP_ZINSAUFWAND,
        NULLIF(GF_EBIL_DSCR, null)                                                                                           as GF_EBIL_DSCR,
        NULLIF(GF_EBIL_GRP_DSCR, null)                                                                                       as GF_EBIL_GRP_DSCR,
        NULLIF(GF_EBIL_ANLAGEVERMOEGEN_BRUTTOHAFTKAPITAL, null)                                                              as GF_EBIL_ANLAGEVERMOEGEN_BRUTTOHAFTKAPITAL,
        NULLIF(GF_EBIL_GRP_ANLAGEVERMOEGEN_BRUTTOHAFTKAPITAL, null)                                                          as GF_EBIL_GRP_ANLAGEVERMOEGEN_BRUTTOHAFTKAPITAL,
        NULLIF(GF_EBIL_BELEGUNGSRATE, null)                                                                                  as GF_EBIL_BELEGUNGSRATE,
        NULLIF(GF_EBIL_GRP_BELEGUNGSRATE, null)                                                                              as GF_EBIL_GRP_BELEGUNGSRATE,
        NULLIF(GF_EBIL_DSCR_GEWERBEIMMOBILIEN, null)                                                                         as GF_EBIL_DSCR_GEWERBEIMMOBILIEN,
        NULLIF(GF_EBIL_GRP_DSCR_GEWERBEIMMOBILIEN, null)                                                                     as GF_EBIL_GRP_DSCR_GEWERBEIMMOBILIEN,
        NULLIF(GF_EBIL_DECKUNGSQUOTE, null)                                                                                  as GF_EBIL_DECKUNGSQUOTE,
        NULLIF(GF_EBIL_GRP_DECKUNGSQUOTE, null)                                                                              as GF_EBIL_GRP_DECKUNGSQUOTE,
        NULLIF(GF_EBIL_DYNAMISCHER_VERSCHULDUNGSGRAD, null)                                                                  as GF_EBIL_DYNAMISCHER_VERSCHULDUNGSGRAD,
        NULLIF(GF_EBIL_GRP_DYNAMISCHER_VERSCHULDUNGSGRAD, null)                                                              as GF_EBIL_GRP_DYNAMISCHER_VERSCHULDUNGSGRAD,
        NULLIF(GF_EBIL_GELDUMSCHLAGSDAUER_TAGE, null)                                                                        as GF_EBIL_GELDUMSCHLAGSDAUER_TAGE,
        NULLIF(GF_EBIL_GRP_GELDUMSCHLAGSDAUER_TAGE, null)                                                                    as GF_EBIL_GRP_GELDUMSCHLAGSDAUER_TAGE,
        NULLIF(GF_EBIL_KAPITALDIENST, null)                                                                                  as GF_EBIL_KAPITALDIENST,
        NULLIF(GF_EBIL_GRP_KAPITALDIENST, null)                                                                              as GF_EBIL_GRP_KAPITALDIENST,
        NULLIF(GF_EBIL_SCHULDENRENDITE, null)                                                                                as GF_EBIL_SCHULDENRENDITE,
        NULLIF(GF_EBIL_GRP_SCHULDENRENDITE, null)                                                                            as GF_EBIL_GRP_SCHULDENRENDITE,
        NULLIF(GF_EBIL_ANZAHL_MITARBEITER, null)                                                                             as GF_EBIL_ANZAHL_MITARBEITER,
        NULLIF(GF_EBIL_GRP_ANZAHL_MITARBEITER, null)                                                                         as GF_EBIL_GRP_ANZAHL_MITARBEITER,
        NULLIF(GF_EBIL_BETRIEBSERGEBNIS, null)                                                                               as GF_EBIL_BETRIEBSERGEBNIS,
        NULLIF(GF_EBIL_GRP_BETRIEBSERGEBNIS, null)                                                                           as GF_EBIL_GRP_BETRIEBSERGEBNIS,
        NULLIF(GF_EBIL_BILANZSUMME, null)                                                                                    as GF_EBIL_BILANZSUMME,
        NULLIF(GF_EBIL_GRP_BILANZSUMME, null)                                                                                as GF_EBIL_GRP_BILANZSUMME,
        NULLIF(GF_EBIL_BRUTTOVERSCHULDUNGSGRAD, null)                                                                        as GF_EBIL_BRUTTOVERSCHULDUNGSGRAD,
        NULLIF(GF_EBIL_GRP_BRUTTOVERSCHULDUNGSGRAD, null)                                                                    as GF_EBIL_GRP_BRUTTOVERSCHULDUNGSGRAD,
        NULLIF(GF_EBIL_EBIT, null)                                                                                           as GF_EBIL_EBIT,
        NULLIF(GF_EBIL_GRP_EBIT, null)                                                                                       as GF_EBIL_GRP_EBIT,
        NULLIF(GF_EBIL_LEVERAGE_RATIO, null)                                                                                 as GF_EBIL_LEVERAGE_RATIO,
        NULLIF(GF_EBIL_GRP_LEVERAGE_RATIO, null)                                                                             as GF_EBIL_GRP_LEVERAGE_RATIO,
        NULLIF(GF_EBIL_EIGENKAPITAL_QUOTE, null)                                                                             as GF_EBIL_EIGENKAPITAL_QUOTE,
        NULLIF(GF_EBIL_GRP_EIGENKAPITAL_QUOTE, null)                                                                         as GF_EBIL_GRP_EIGENKAPITAL_QUOTE,
        NULLIF(GF_EBIL_EKRENTABILITAET, null)                                                                                as GF_EBIL_EKRENTABILITAET,
        NULLIF(GF_EBIL_GRP_EKRENTABILITAET, null)                                                                            as GF_EBIL_GRP_EKRENTABILITAET,
        NULLIF(GF_EBIL_EVENTUALVERBINDLICHKEITEN, null)                                                                      as GF_EBIL_EVENTUALVERBINDLICHKEITEN,
        NULLIF(GF_EBIL_GRP_EVENTUALVERBINDLICHKEITEN, null)                                                                  as GF_EBIL_GRP_EVENTUALVERBINDLICHKEITEN,
        NULLIF(GF_EBIL_GESAMTFINANZSCHULDEN, null)                                                                           as GF_EBIL_GESAMTFINANZSCHULDEN,
        NULLIF(GF_EBIL_GRP_GESAMTFINANZSCHULDEN, null)                                                                       as GF_EBIL_GRP_GESAMTFINANZSCHULDEN,
        NULLIF(GF_EBIL_GESAMTKAPITALRENDITE_VOR_STEUERN, null)                                                               as GF_EBIL_GESAMTKAPITALRENDITE_VOR_STEUERN,
        NULLIF(GF_EBIL_GRP_GESAMTKAPITALRENDITE_VOR_STEUERN, null)                                                           as GF_EBIL_GRP_GESAMTKAPITALRENDITE_VOR_STEUERN,
        NULLIF(GF_EBIL_SACHANLAGEVERMOEGEN_UMSATZ, null)                                                                     as GF_EBIL_SACHANLAGEVERMOEGEN_UMSATZ,
        NULLIF(GF_EBIL_GRP_SACHANLAGEVERMOEGEN_UMSATZ, null)                                                                 as GF_EBIL_GRP_SACHANLAGEVERMOEGEN_UMSATZ,
        NULLIF(GF_EBIL_NETTO_HAFTKAPITAL_QUOTE, null)                                                                        as GF_EBIL_NETTO_HAFTKAPITAL_QUOTE,
        NULLIF(GF_EBIL_GRP_NETTO_HAFTKAPITAL_QUOTE, null)                                                                    as GF_EBIL_GRP_NETTO_HAFTKAPITAL_QUOTE,
        NULLIF(GF_EBIL_UMSATZRENTABILITAET, null)                                                                            as GF_EBIL_UMSATZRENTABILITAET,
        NULLIF(GF_EBIL_GRP_UMSATZRENTABILITAET, null)                                                                        as GF_EBIL_GRP_UMSATZRENTABILITAET,
        NULLIF(GF_EBIL_NETTO_VERSCHULDUNGSGRAD, null)                                                                        as GF_EBIL_NETTO_VERSCHULDUNGSGRAD,
        NULLIF(GF_EBIL_GRP_NETTO_VERSCHULDUNGSGRAD, null)                                                                    as GF_EBIL_GRP_NETTO_VERSCHULDUNGSGRAD,
        NULLIF(GF_EBIL_SUMME_MFR_LFR_FREMDKAPITAL, null)                                                                     as GF_EBIL_SUMME_MFR_LFR_FREMDKAPITAL,
        NULLIF(GF_EBIL_GRP_SUMME_MFR_LFR_FREMDKAPITAL, null)                                                                 as GF_EBIL_GRP_SUMME_MFR_LFR_FREMDKAPITAL,
        NULLIF(GF_EBIL_UMSATZENTWICKLUNG, null)                                                                              as GF_EBIL_UMSATZENTWICKLUNG,
        NULLIF(GF_EBIL_GRP_UMSATZENTWICKLUNG, null)                                                                          as GF_EBIL_GRP_UMSATZENTWICKLUNG,
        NULLIF(GF_EBIL_ZINSDECKUNGSQUOTE, null)                                                                              as GF_EBIL_ZINSDECKUNGSQUOTE,
        NULLIF(GF_EBIL_GRP_ZINSDECKUNGSQUOTE, null)                                                                          as GF_EBIL_GRP_ZINSDECKUNGSQUOTE,
        NULLIF(GF_EBIL_AUSSCHUETTUNG, null)                                                                                  as GF_EBIL_AUSSCHUETTUNG,
        NULLIF(GF_EBIL_GRP_AUSSCHUETTUNG, null)                                                                              as GF_EBIL_GRP_AUSSCHUETTUNG,
        NULLIF(GF_EBIL_NETTO_FINANZSCHULDEN, null)                                                                           as GF_EBIL_NETTO_FINANZSCHULDEN,
        NULLIF(GF_EBIL_GRP_NETTO_FINANZSCHULDEN, null)                                                                       as GF_EBIL_GRP_NETTO_FINANZSCHULDEN,
        NULLIF(GF_EBIL_CASHFLOWKENNZAHL1, null)                                                                              as GF_EBIL_CASHFLOWKENNZAHL1,
        NULLIF(GF_EBIL_GRP_CASHFLOWKENNZAHL1, null)                                                                          as GF_EBIL_GRP_CASHFLOWKENNZAHL1,
        NULLIF(GF_EBIL_CASHFLOWERFOLGSWIRKSERWEITERT, null)                                                                  as GF_EBIL_CASHFLOWERFOLGSWIRKSERWEITERT,
        NULLIF(GF_EBIL_GRP_CASHFLOWERFOLGSWIRKSERWEITERT, null)                                                              as GF_EBIL_GRP_CASHFLOWERFOLGSWIRKSERWEITERT,
        NULLIF(GF_EBIL_SENSITIVIERTGESAMTSCHULDENDIENSTDECKUNGSQUOTE, null)                                                  as GF_EBIL_SENSITIVIERTGESAMTSCHULDENDIENSTDECKUNGSQUOTE,
        NULLIF(GF_EBIL_GRP_SENSITIVIERTGESAMTSCHULDENDIENSTDECKUNGSQUOTE, null)                                              as GF_EBIL_GRP_SENSITIVIERTGESAMTSCHULDENDIENSTDECKUNGSQUOTE,
        NULLIF(GF_EBIL_KAPITALDIENSTGRENZEVORERSATZINVEST, null)                                                             as GF_EBIL_KAPITALDIENSTGRENZEVORERSATZINVEST,
        NULLIF(GF_EBIL_GRP_KAPITALDIENSTGRENZEVORERSATZINVEST, null)                                                         as GF_EBIL_GRP_KAPITALDIENSTGRENZEVORERSATZINVEST,
        NULLIF(GF_EBIL_TESTATART, null)                                                                                      as GF_EBIL_TESTATART,
        NULLIF(GF_EBIL_GRP_TESTATART, null)                                                                                  as GF_EBIL_GRP_TESTATART,
        NULLIF(GF_EBIL_RETURNONCAPITALEMPLOYED, null)                                                                        as GF_EBIL_RETURNONCAPITALEMPLOYED,
        NULLIF(GF_EBIL_GRP_RETURNONCAPITALEMPLOYED, null)                                                                    as GF_EBIL_GRP_RETURNONCAPITALEMPLOYED,
        NULLIF(LBRATING_RAT_BUS_ID, null)                                                                                    as LBRATING_RAT_BUS_ID,
        NULLIF(LBRATING_SOURCE, null)                                                                                        as LBRATING_SOURCE,
        NULLIF(LBRATING_PRESUM_STRAT_TXT, null)                                                                              as LBRATING_PRESUM_STRAT_TXT,
        NULLIF(LBRATING_PRESUM_STRAT_STATE, null)                                                                            as LBRATING_PRESUM_STRAT_STATE,
        NULLIF(LBRATING_NEG_DIV_TXT, null)                                                                                   as LBRATING_NEG_DIV_TXT,
        NULLIF(LBRATING_NEG_DIV_STATE, null)                                                                                 as LBRATING_NEG_DIV_STATE,
        NULLIF(LBRATING_COMP_EXPECT_TXT, null)                                                                               as LBRATING_COMP_EXPECT_TXT,
        NULLIF(LBRATING_EXPECT_STATE, null)                                                                                  as LBRATING_EXPECT_STATE,
        NULLIF(LBRATING_BANK_EXPECT_TXT, null)                                                                               as LBRATING_BANK_EXPECT_TXT,
        NULLIF(LBRATING_INFLUENCE_TXT, null)                                                                                 as LBRATING_INFLUENCE_TXT,
        NULLIF(LBRATING_INFLUENCE_STATE, null)                                                                               as LBRATING_INFLUENCE_STATE,
        NULLIF(LBRATING_SENSITIV_TXT, null)                                                                                  as LBRATING_SENSITIV_TXT,
        NULLIF(LBRATING_SENSITIV_STATE, null)                                                                                as LBRATING_SENSITIV_STATE,
        NULLIF(LBRATING_INFO_TXT, null)                                                                                      as LBRATING_INFO_TXT,
        NULLIF(LBRATING_INFO_STATE, null)                                                                                    as LBRATING_INFO_STATE,
        NULLIF(LBRATING_DEPENDENCY_TXT, null)                                                                                as LBRATING_DEPENDENCY_TXT,
        NULLIF(LBRATING_DEPENDENCY_STATE, null)                                                                              as LBRATING_DEPENDENCY_STATE,
        NULLIF(LBRATING_CURRENCYRISK_TXT, null)                                                                              as LBRATING_CURRENCYRISK_TXT,
        NULLIF(LBRATING_CURRENCYRISK_STATE, null)                                                                            as LBRATING_CURRENCYRISK_STATE,
        NULLIF(LBRATING_ORIENTATION_TXT, null)                                                                               as LBRATING_ORIENTATION_TXT,
        NULLIF(LBRATING_ORIENTATION_STATE, null)                                                                             as LBRATING_ORIENTATION_STATE,
        NULLIF(LBRATING_IN_PROFESSIONALISM_TXT, null)                                                                        as LBRATING_IN_PROFESSIONALISM_TXT,
        NULLIF(LBRATING_DEBTOR_ASSETS_TXT, null)                                                                             as LBRATING_DEBTOR_ASSETS_TXT,
        NULLIF(LBRATING_FINANCE_SITUATION_TXT, null)                                                                         as LBRATING_FINANCE_SITUATION_TXT,
        NULLIF(LBRATING_INVEST_ACTIVITY_TXT, null)                                                                           as LBRATING_INVEST_ACTIVITY_TXT,
        NULLIF(LBRATING_LIQUID_SITUATION_TXT, null)                                                                          as LBRATING_LIQUID_SITUATION_TXT,
        NULLIF(LBRATING_SUPPORT_PROVIDED_TXT, null)                                                                          as LBRATING_SUPPORT_PROVIDED_TXT,
        NULLIF(LBRATING_DEBTOR_SUPPORT_TXT, null)                                                                            as LBRATING_DEBTOR_SUPPORT_TXT,
        NULLIF(LBRATING_CUST_QUAL_STATE, null)                                                                               as LBRATING_CUST_QUAL_STATE,
        NULLIF(LBRATING_HQF_DAUKUNBEZ_695, null)                                                                             as LBRATING_HQF_DAUKUNBEZ_695,
        NULLIF(LBRATING_WQF_ZUVERLAESSIGKEIT_2763_TXT, null)                                                                 as LBRATING_WQF_ZUVERLAESSIGKEIT_2763_TXT,
        NULLIF(LBRATING_WQF_INFOBEREITSCH_2758_TXT, null)                                                                    as LBRATING_WQF_INFOBEREITSCH_2758_TXT,
        NULLIF(LBRATING_WQF_UNTERNEHMENTW_2748_TXT, null)                                                                    as LBRATING_WQF_UNTERNEHMENTW_2748_TXT,
        NULLIF(LBRATING_WQF_MANAGEMENT_SIR_2743_TXT, null)                                                                   as LBRATING_WQF_MANAGEMENT_SIR_2743_TXT,
        NULLIF(LBRATING_HQF_VERKAUFSSTAND_2792_TXT, null)                                                                    as LBRATING_HQF_VERKAUFSSTAND_2792_TXT,
        NULLIF(LBRATING_WQF_FINANZBEREICH_2778_TXT, null)                                                                    as LBRATING_WQF_FINANZBEREICH_2778_TXT,
        NULLIF(LBRATING_WQF_VRTRBVRMRKTNG_2773_TXT, null)                                                                    as LBRATING_WQF_VRTRBVRMRKTNG_2773_TXT,
        NULLIF(LBRATING_WQF_BAUQUALITAET_2768_TXT, null)                                                                     as LBRATING_WQF_BAUQUALITAET_2768_TXT,
        NULLIF(LBRATING_WQF_LIQUIDITAET_5511_TXT, null)                                                                      as LBRATING_WQF_LIQUIDITAET_5511_TXT,
        NULLIF(IWHS_ORG_RECHTSFORM, null)                                                                                    as IWHS_ORG_RECHTSFORM,
        NULLIF(IWHS_PERSONEN_ART, null)                                                                                      as IWHS_PERSONEN_ART,
        NULLIF(IWHS_WIRTSCH_ZWEIG, null)                                                                                     as IWHS_WIRTSCH_ZWEIG,
        NULLIF(IWHS_MWSN_NACE_CODE, null)                                                                                    as IWHS_MWSN_NACE_CODE,
        NULLIF(IWHS_KUSY_DSGV_NEU, null)                                                                                     as IWHS_KUSY_DSGV_NEU,
        NULLIF(IWHS_GEBURTS_GRUENDUNGS_DAT, null)                                                                            as IWHS_GEBURTS_GRUENDUNGS_DAT,
        NULLIF(IWHS_BERUFL_STELLUNG, null)                                                                                   as IWHS_BERUFL_STELLUNG,
        NULLIF(IWHS_BERUF_BRANCHE, null)                                                                                     as IWHS_BERUF_BRANCHE,
        NULLIF(IWHS_STRASSE, null)                                                                                           as IWHS_STRASSE,
        NULLIF(IWHS_HAUSNR, null)                                                                                            as IWHS_HAUSNR,
        NULLIF(IWHS_POSTLEITZAHL, null)                                                                                      as IWHS_POSTLEITZAHL,
        NULLIF(IWHS_ORT, null)                                                                                               as IWHS_ORT,
        NULLIF(IWHS_LAND, null)                                                                                              as IWHS_LAND,
        NULLIF(IWHS_FUEHRENDE_BONITAET, null)                                                                                as IWHS_FUEHRENDE_BONITAET,
        NULLIF(IWHS_SCHUFA_AUSKUNFT, null)                                                                                   as IWHS_SCHUFA_AUSKUNFT,
        NULLIF(IWHS_SCHUFA_NEGATIVMERKMAL, null)                                                                             as IWHS_SCHUFA_NEGATIVMERKMAL,
        NULLIF(IWHS_SCHUFA_SCORING_WERT, null)                                                                               as IWHS_SCHUFA_SCORING_WERT,
        NULLIF(IWHS_LETZTE_AENDERUNG, null)                                                                                  as IWHS_LETZTE_AENDERUNG,
        NULLIF(IWHS_TREIBHAUSGASEMISSIONEN_KUNDEN_SCORE, null)                                                               as IWHS_TREIBHAUSGASEMISSIONEN_KUNDEN_SCORE,
        NULLIF(IWHS_TREIBHAUSGASEMISSIONEN_BRANCHEN_SCORE, null)                                                             as IWHS_TREIBHAUSGASEMISSIONEN_BRANCHEN_SCORE,
        NULLIF(IWHS_WASSEREINSATZ_KUNDEN_SCORE, null)                                                                        as IWHS_WASSEREINSATZ_KUNDEN_SCORE,
        NULLIF(IWHS_WASSEREINSATZ_BRANCHEN_SCORE, null)                                                                      as IWHS_WASSEREINSATZ_BRANCHEN_SCORE,
        NULLIF(IWHS_GERINGFUEGIGE_BESCHAEFTIGUNG_KUNDEN_SCORE, null)                                                         as IWHS_GERINGFUEGIGE_BESCHAEFTIGUNG_KUNDEN_SCORE,
        NULLIF(IWHS_GERINGFUEGIGE_BESCHAEFTIGUNG_BRANCHEN_SCORE, null)                                                       as IWHS_GERINGFUEGIGE_BESCHAEFTIGUNG_BRANCHEN_SCORE,
        NULLIF(IWHS_LEIHARBEIT_KUNDEN_SCORE, null)                                                                           as IWHS_LEIHARBEIT_KUNDEN_SCORE,
        NULLIF(IWHS_LEIHARBEIT_BRANCHEN_SCORE, null)                                                                         as IWHS_LEIHARBEIT_BRANCHEN_SCORE,
        NULLIF(IWHS_GENDER_PAY_GAP_KUNDEN_SCORE, null)                                                                       as IWHS_GENDER_PAY_GAP_KUNDEN_SCORE,
        NULLIF(IWHS_GENDER_PAY_GAP_BRANCHEN_SCORE, null)                                                                     as IWHS_GENDER_PAY_GAP_BRANCHEN_SCORE,
        NULLIF(IWHS_AKUTE_PHYSISCHE_RISIKEN_HOCHWASSER_KUNDEN_SCORE, null)                                                   as IWHS_AKUTE_PHYSISCHE_RISIKEN_HOCHWASSER_KUNDEN_SCORE,
        NULLIF(IWHS_AKUTE_PHYSISCHE_RISIKEN_HOCHWASSER_BRANCHEN_SCORE, null)                                                 as IWHS_AKUTE_PHYSISCHE_RISIKEN_HOCHWASSER_BRANCHEN_SCORE,
        NULLIF(IWHS_CHRONISCHE_PHYSISCHE_RISIKEN_BIODIVERSITAET_KUNDEN_SCORE, null)                                          as IWHS_CHRONISCHE_PHYSISCHE_RISIKEN_BIODIVERSITAET_KUNDEN_SCORE,
        NULLIF(IWHS_CHRONISCHE_PHYSISCHE_RISIKEN_BIODIVERSITAET_BRANCHEN_SCORE, null)                                        as IWHS_CHRONISCHE_PHYSISCHE_RISIKEN_BIODIVERSITAET_BRANCHEN_SCORE,
        NULLIF(IWHS_WANDLUNGSFAEHIGKEIT_KLIMANEUTRALITAET_KUNDEN_SCORE, null)                                                as IWHS_WANDLUNGSFAEHIGKEIT_KLIMANEUTRALITAET_KUNDEN_SCORE,
        NULLIF(IWHS_WANDLUNGSFAEHIGKEIT_KLIMANEUTRALITAET_BRANCHEN_SCORE, null)                                              as IWHS_WANDLUNGSFAEHIGKEIT_KLIMANEUTRALITAET_BRANCHEN_SCORE,
        NULLIF(IWHS_SOZIALE_STANDARDS_VERSTOESSE_GEGEN_MENSCHENRECHTE_ENTLANG_DER_WERTSCHOEPFUNGSKETTE_KUNDEN_SCORE,
               null)                                                                                                         as IWHS_SOZIALE_STANDARDS_VERSTOESSE_GEGEN_MENSCHENRECHTE_ENTLANG_DER_WERTSCHOEPFUNGSKETTE_KUNDEN_SCORE,
        NULLIF(IWHS_SOZIALE_STANDARDS_VERSTOESSE_GEGEN_MENSCHENRECHTE_ENTLANG_DER_WERTSCHOEPFUNGSKETTE_BRANCHEN_SCORE,
               null)                                                                                                         as IWHS_SOZIALE_STANDARDS_VERSTOESSE_GEGEN_MENSCHENRECHTE_ENTLANG_DER_WERTSCHOEPFUNGSKETTE_BRANCHEN_SCORE,
        NULLIF(IWHS_ORGANISATORISCHE_INTEGRATION_VON_NACHHALTIGKEIT_KUNDEN_SCORE, null)                                      as IWHS_ORGANISATORISCHE_INTEGRATION_VON_NACHHALTIGKEIT_KUNDEN_SCORE,
        NULLIF(IWHS_ORGANISATORISCHE_INTEGRATION_VON_NACHHALTIGKEIT_BRANCHEN_SCORE, null)                                    as IWHS_ORGANISATORISCHE_INTEGRATION_VON_NACHHALTIGKEIT_BRANCHEN_SCORE,
        NULLIF(IWHS_GEFAEHRLICHER_ABFALL_KUNDEN_SCORE, null)                                                                 as IWHS_GEFAEHRLICHER_ABFALL_KUNDEN_SCORE,
        NULLIF(IWHS_GEFAEHRLICHER_ABFALL_BRANCHEN_SCORE, null)                                                               as IWHS_GEFAEHRLICHER_ABFALL_BRANCHEN_SCORE,
        NULLIF(IWHS_VERSTOESSE_GEGEN_EINE_ORDNUNGSGEMAESSE_UNTERNEHMENSFUEHRUNG_KUNDEN_SCORE, null)                          as IWHS_VERSTOESSE_GEGEN_EINE_ORDNUNGSGEMAESSE_UNTERNEHMENSFUEHRUNG_KUNDEN_SCORE,
        NULLIF(IWHS_VERSTOESSE_GEGEN_EINE_ORDNUNGSGEMAESSE_UNTERNEHMENSFUEHRUNG_BRANCHEN_SCORE, null)                        as IWHS_VERSTOESSE_GEGEN_EINE_ORDNUNGSGEMAESSE_UNTERNEHMENSFUEHRUNG_BRANCHEN_SCORE,
        NULLIF(IWHS_HAUPTLEGIMITATION, null)                                                                                 as IWHS_HAUPTLEGIMITATION,
        NULLIF(IWHS_LEGITIMIERUNGSART, null)                                                                                 as IWHS_LEGITIMIERUNGSART,
        NULLIF(IWHS_AUSSTELLUNGSDATUM, null)                                                                                 as IWHS_AUSSTELLUNGSDATUM,
        NULLIF(IWHS_EINTRAGEDATUM_IN_OEFFENTL_REGISTER, null)                                                                as IWHS_EINTRAGEDATUM_IN_OEFFENTL_REGISTER,
        NULLIF(IWHS_ABLAUFDATUM_DER_LEGITIMATION, null)                                                                      as IWHS_ABLAUFDATUM_DER_LEGITIMATION,
        NULLIF(IWHS_LEGITIMATIONSNUMMER, null)                                                                               as IWHS_LEGITIMATIONSNUMMER,
        NULLIF(IWHS_AUSSTELLENDE_BEHOERDE, null)                                                                             as IWHS_AUSSTELLENDE_BEHOERDE,
        NULLIF(IWHS_AUSSTELLUNGSORT, null)                                                                                   as IWHS_AUSSTELLUNGSORT,
        NULLIF(IWHS_STEUERLICH_ALS_AUSLAENDER_ZU_BEHANDELN, null)                                                            as IWHS_STEUERLICH_ALS_AUSLAENDER_ZU_BEHANDELN,
        NULLIF(IWHS_ROLLE_FINANZSSANKTIONEN, null)                                                                           as IWHS_ROLLE_FINANZSSANKTIONEN,
        NULLIF(IWHS_GWG_FALL, null)                                                                                          as IWHS_GWG_FALL,
        NULLIF(IWHS_ABW_WIRT_BERECHTIGTER, null)                                                                             as IWHS_ABW_WIRT_BERECHTIGTER,
        -- Defaults
        CURRENT_USER                                                                                                         as USER,
        CURRENT_TIMESTAMP                                                                                                    as TIMESTAMP_LOAD
    from FINAL
)
select *
from FINAL_FILTERED;

-- CI START FOR ALL TAPES

-- Current-Tabelle erstellen
------------------------------------------------------------------------------------------------------------------------
call STG.TEST_PROC_BACKUP_AND_DROP('AMC', 'TABLE_CUSTOMER_EBA_CURRENT');
create table AMC.TABLE_CUSTOMER_EBA_CURRENT like CALC.VIEW_CUSTOMER_EBA distribute by hash (GNI_KUNDE) in SPACE_AMC_A,SPACE_AMC_B,SPACE_AMC_C,SPACE_AMC_D,SPACE_AMC_E,SPACE_AMC_F;
create index AMC.INDEX_CUSTOMER_EBA_CURRENT_GNI_KUNDE on AMC.TABLE_CUSTOMER_EBA_CURRENT (GNI_KUNDE);
call STG.TEST_PROC_LOAD_AND_DROP_BACKUP_FOR('AMC', 'TABLE_CUSTOMER_EBA_CURRENT');
------------------------------------------------------------------------------------------------------------------------

-- Archiv-Tabelle erstellen
------------------------------------------------------------------------------------------------------------------------
call STG.TEST_PROC_BACKUP_AND_DROP('AMC', 'TABLE_CUSTOMER_EBA_ARCHIVE');
create table AMC.TABLE_CUSTOMER_EBA_ARCHIVE like CALC.VIEW_CUSTOMER_EBA distribute by hash (GNI_KUNDE) partition by RANGE (CUT_OFF_DATE) (starting '1.1.2015' ending '31.12.2030' EVERY 1 Month) in SPACE_AMC_A,SPACE_AMC_B,SPACE_AMC_C,SPACE_AMC_D,SPACE_AMC_E,SPACE_AMC_F;
create index AMC.INDEX_CUSTOMER_EBA_ARCHIVE_GNI_KUNDE on AMC.TABLE_CUSTOMER_EBA_ARCHIVE (GNI_KUNDE);
call STG.TEST_PROC_LOAD_AND_DROP_BACKUP_FOR('AMC', 'TABLE_CUSTOMER_EBA_ARCHIVE');
------------------------------------------------------------------------------------------------------------------------

-- CI END FOR ALL TAPES

-- SWITCH Views erstellen
------------------------------------------------------------------------------------------------------------------------
call STG.TEST_PROC_DROP_AND_CREATE_SWITCH('AMC', 'TABLE_CUSTOMER_EBA_CURRENT');
call STG.TEST_PROC_DROP_AND_CREATE_SWITCH('AMC', 'TABLE_CUSTOMER_EBA_ARCHIVE');
------------------------------------------------------------------------------------------------------------------------

