--------------------------
-- CLIENT_ACCOUNTHOLDER --
--------------------------
-- CI START FOR ALL TAPES
-- Drop View
drop view AMC.TAPE_CLIENT_ACCOUNTHOLDER_PWC;
-- View erstellen
create or replace view AMC.TAPE_CLIENT_ACCOUNTHOLDER_PWC as
select distinct
    TAPE.CUT_OFF_DATE,                                 -- Stichtag
    CLIENT_ID      as GNI_KUNDE,
    CLIENT_ID_LEADING as GNI_KUNDE_LEADING,            -- Führende Kundennummer aus dem Ergebnis der Institutsfusion
    CLIENT_TYPE as GNI_TYP,
    BRANCH as GNI_ZUORDNUNG,                           -- Institut des Kunden (führendes Institut bevorzugt)
    CLIENT_NAME_ANONYMIZED as GNI_NAME,
    KONZERN_ID as GNI_KONZERNID,
    KONZERN_BEZEICHNUNG_ANONYMIZED as GNI_KONZERN,
    GVK_BUNDESBANKNUMMER as GNI_BUNDESBANKNR,
    NACE as GNI_NACE,                                  -- statistische Systematik der Wirtschaftszweige in der EU [abbr.: NACE]
    COUNTRY_APLHA2 as GNI_KUNDELAND,                   -- Land Alpha2 Wert
    RATING_ID as GNI_KUNDERATING,
    RATING_MODUL as GNI_KUNDEMODUL,
    SAP_EAD_SUMME,
    SAP_EL_SUMME,
    SAP_INANSPRUCHNAHME_SUMME,
    SAP_INANSPRUCHNAHME_AZ6_SUMME,
    SAP_INANSPRUCHNAHME_AVAL_SUMME,
    SAP_BLANKO_SUMME,
    SAP_FREILINIE_SUMME as SAP_FREIELINIE_SUMME,
    FORDERUNG_SUMME as GNI_FORDERUNG_SUMME,
    FORDERUNGAVAL_SUMME as GNI_FORDERUNGAVAL_SUMME,
    FORDERUNG_K028_SUMME as GNI_FORDERUNG_K028_SUMME,
    FORDERUNG_RSMMARKETS_SUMME as GNI_FORDERUNG_RSMMARKETS_SUMME,
    GUTHABEN_SUMME as GNI_GUTHABEN_SUMME,
    TILGUNGSRUECKSTAND_SUMME as GNI_TILGUNGSRUECKSTAND_SUMME,
    ZINSRUECKSTAND_SUMME as GNI_ZINSRUECKSTAND_SUMME,
    PROVISIONSRUECKSTAND_SUMME as GNI_PROVISIONSRUECKSTAND_SUMME,
    OFFBALANCE_SUMME as GNI_OFFBALANCE_SUMME,
    SAP_EWBTES_SUMME,
    FVA_SUMME as GNI_FVA_SUMME,
    ABIT_EWB_EUR_SUMME,
    ABIT_RST_EUR_SUMME,
    ZEB_EWB_EUR_ONBALANCE_SUMME,
    ZEB_EWB_EUR_OFFBALANCE_SUMME
from AMC.TABLE_CLIENT_ACCOUNTHOLDER_CURRENT as TAPE
;
-- CI END FOR ALL TAPES
