----------------
-- COLLATERAL --
----------------
-- CI START FOR ALL TAPES
-- Drop View
drop view AMC.TAPE_COLLATERAL_PWC;
-- View erstellen
create or replace view AMC.TAPE_COLLATERAL_PWC as
select   CUT_OFF_DATE,
         COLLATERAL_ID,
         COLLATERAL_ID_ORACLE,
         COLLATERAL_TYPE as GNI_TYP,
         COLLATERAL_SUBTYPE as GNI_SUBTYP,
         COLLATERAL_DESCRIPTION as GNI_BESCHREIBUNG,
         NOMINAL_VALUE_EUR as GNI_NOMINALWERT,
         --NOMINAL_VALUE_OC, nicht gefordert
         NOMINAL_VALUE_ORIGINAL_CURRENCY as GNI_NOMINALWERTWAEHRUNG,
         NOMINAL_EXCHANGE_RATE as GNI_NOMINALFX,
         COLLATERAL_VALUE_EUR as GNI_SICHERHEITENWERT,
         --COLLATERAL_VALUE_OC, nicht gefordert
         COLLATERAL_VALUE_ORIGINAL_CURRENCY as GNI_SICHERHEITENWERTWAEHRUNG,
         COLLATERAL_EXCHANGE_RATE as GNI_SICHERHEITENWERTFX,
         CLAIM_AMOUNT as GNI_FORDERUNGSBETRAG,
         LTV_RATIO as GNI_LTV,
         LTV_RATIO_NUMERATOR as GNI_LTV_ZAEHLER,
         NORDLB_SHARE_PERCENT as GNI_NORDLBANTEIL_PROZENT,
         NORDLB_SHARE_EUR as GNI_NORDLBANTEIL,
         --NORDLB_SHARE_OC, nicht gefordert
         --NORDLB_SHARE_ORIGINAL_CURRENCY, nicht gefordert
         --NORDLB_SHARE_EXCHANGE_RATE, nicht gefordert
         LUX_SHARE_EUR as GNI_LUXANTEIL,
         --LUX_SHARE_OC, nicht gefordert
         DEBIT_MAX_REAL as GNI_BELASTUNG_MAX_REAL,
         DEBIT_MAX_PERS as GNI_BELASTUNG_MAX_PERS,
         DEBIT_MAX_ECON as GNI_BELASTUNG_MAX_WIRT,
         MAX_RISK_SV_ZUR_VERT_IN_EUR as GNI_MAX_RISK_SV_ZUR_VERT_IN_EUR,
         SV_AUSFBUERGSCHAFT as GNI_AUSFBUERGSCHAFT,
         SV_AUSFALLBUERG_PROZ as GNI_AUSFALLBUERG_PROZ,
         SV_HOECHSTBETRBUERG as GNI_HOECHSTBETRBUERG,
         SV_VERBUERGUNGSSATZ_PROZ GNI_VERBUERGUNGSSATZ_PROZ,
         SV_BUERG_BELEIHSATZ_PROZ as GNI_BUERG_BELEIHSATZ_PROZ,
         SV_ANWENDBARES_RECHT as GNI_ANWENDBARES_RECHT,
         SV_GESAMTGRUNDSCHULD as GNI_GESAMTGRUNDSCHULD,
         SV_KUST as GNI_KUST,
         SV_VERWALT_OE as GNI_VERWALTOE,
         --SV_PAS, nicht gefordert
         SV_CRR_KZ as GNI_CRRKZ,
         BRANCH as GNI_NIEDERLASSUNG,
         SOURCE as GNI_QUELLE,
         CREATED_USER,
         CREATED_TIMESTAMP
from AMC.TABLE_COLLATERAL_CURRENT;
-- CI END FOR ALL TAPES