----------------
-- COLLATERAL --
----------------
-- CI START FOR ALL TAPES
-- Drop View
drop view AMC.TAPE_COLLATERAL_FINISH;
-- View erstellen
create or replace view AMC.TAPE_COLLATERAL_FINISH as
select CUT_OFF_DATE, COLLATERAL_ID, COLLATERAL_TYPE, COLLATERAL_DESCRIPTION,
       NOMINAL_VALUE_EUR, NOMINAL_VALUE_OC, NOMINAL_VALUE_ORIGINAL_CURRENCY, NOMINAL_EXCHANGE_RATE as NOMINAL_EXCANGE_RATE,
       COLLATERAL_VALUE_EUR, COLLATERAL_VALUE_OC, COLLATERAL_VALUE_ORIGINAL_CURRENCY, COLLATERAL_EXCHANGE_RATE as COLLATERAL_EXCANGE_RATE,
       NORDLB_SHARE_EUR, NORDLB_SHARE_OC, NORDLB_SHARE_ORIGINAL_CURRENCY, NORDLB_SHARE_EXCHANGE_RATE as NORDLB_SHARE_EXCANGE_RATE,
       MAX_RISK_SV_ZUR_VERT_IN_EUR, SV_AUSFBUERGSCHAFT, SV_AUSFALLBUERG_PROZ, SV_HOECHSTBETRBUERG,
       SV_VERBUERGUNGSSATZ_PROZ, SV_BUERG_BELEIHSATZ_PROZ, SV_ANWENDBARES_RECHT, SV_GESAMTGRUNDSCHULD,
       SV_KUST, SV_VERWALT_OE, SV_PAS, SV_CRR_KZ, LUX_SHARE_EUR, LUX_SHARE_OC,
       BRANCH, CREATED_USER, CREATED_TIMESTAMP
from AMC.TABLE_COLLATERAL_CURRENT;
-- CI END FOR ALL TAPES