-----------
-- ASSET --
-----------
-- CI START FOR ALL TAPES
-- Drop View
drop view AMC.TAPE_ASSET_PWC;
-- View erstellen
create or replace view AMC.TAPE_ASSET_PWC as
select  CUT_OFF_DATE,
        ASSET_ID,
        ASSET_TYPE as GNI_TYP,
        ASSET_DESCRIPTION as GNI_BESCHREIBUNG,
        BRANCH as GNI_NIEDERLASSUNG,
        NOMINAL_VALUE_EUR GNI_SICHERHEITENWERT,
        --NOMINAL_VALUE_OC, nicht gefordert
        NOMINAL_VALUE_CURRENCY GNI_SICHERHEITENWERTWAEHRUNG,
        ASSET_VALUE_EUR GNI_BELEIHUNGSWERT,
        --ASSET_VALUE_OC, nicht gefordert
        ASSET_VALUE_CURRENCY as GNI_BELEIHUNGSWERTWAEHRUNG,
        LTV_RATIO_DENOMINATOR as GNI_LTV_NENNER,
        LTV_LIMIT_1_PERCENT as GNI_LTV_LIMIT_1_PROZENT,
        LTV_LIMIT_1 as GNI_LTV_LIMIT_1,
        LTV_LIMIT_REAL_PERCENT as GNI_LTV_LIMIT_REAL_PROZENT,
        LTV_LIMIT_REAL as GNI_LTV_LIMIT_REAL,
        LTV_LIMIT_PERS_PERCENT as GNI_LTV_LIMIT_PERS_PROZENT,
        LTV_LIMIT_PERS as GNI_LTV_LIMIT_PERS,
        LTV_LIMIT_ECON_PERCENT as GNI_LTV_LIMIT_WIRT_PROZENT,
        LTV_LIMIT_ECON as GNI_LTV_LIMIT_WIRT,
        VO_KUST as GNI_KUST,
        VO_VOE as GNI_VOE,
        VO_CRR_KZ as GNI_CRRKZ,
        BUILDING_TYPE as GNI_GEBAEUDETYP,
        COVER_STOCK_RELEVANCE as GNI_DECKUNGSKZ,
        SOURCE as GNI_QUELLE,
        CREATED_USER,
        CREATED_TIMESTAMP
    from AMC.TABLE_ASSET_CURRENT;

call stg.TEST_PROC_GRANT_PERMISSION_TO('AMC','TAPE_ASSET_PWC');
-- CI END FOR ALL TAPES