--------------------
-- AVIATION_ASSET --
--------------------
-- CI START FOR ALL TAPES
-- Drop View
drop view AMC.TAPE_AVIATION_ASSET_FINISH;
-- View erstellen
create or replace view AMC.TAPE_AVIATION_ASSET_FINISH as
select CUT_OFF_DATE,   -- hier ist die Reihenfolge der ersten 11 Spalten auf Wunsch von EY angepasst um eine Spaltengleichheit zwischen den Asset Tapes zu erhalten
       ASSET_ID,
       ASSET_TYPE,
       ASSET_DESCRIPTION,
       BRANCH,
       AIRCRAFT_APPRAISAL_BASE_VALUE_CMS,
       NULL as AIRCRAFT_APPRAISAL_BASE_VALUE_CMS_OC,
       NULL as AIRCRAFT_APPRAISAL_BASE_VALUE_CURRENCY,
       AIRCRAFT_APPRAISAL_MARKET_VALUE_CMS,
       NULL as AIRCRAFT_APPRAISAL_MARKET_VALUE_CMS_OC,
       NULL as AIRCRAFT_APPRAISAL_MARKET_VALUE_CURRENCY,
       VO_STATUS, AIRCRAFT_MSN_NUMBER, AIRCRAFT_REGISTRATION_ID,
       AIRCRAFT_APPRAISAL_MARKET_VALUE_HALF_LIFE_EUR, AIRCRAFT_APPRAISAL_MARKET_VALUE_FULL_LIFE_EUR,
       AIRCRAFT_APPRAISAL_BASE_VALUE_HALF_LIFE_EUR, AIRCRAFT_APPRAISAL_BASE_VALUE_FULL_LIFE_EUR,
       AIRCRAFT_MAINTENANCE_RESERVES, AIRCRAFT_RETURN_CONDITION, AIRCRAFT_TYPE_CLASS, AIRCRAFT_MANUFACTURER_MODEL, AIRCRAFT_VARIANT,
       AIRCRAFT_REGISTRATION_COUNTRY, AIRCRAFT_BUILD_YEAR, AIRCAFT_AGE_IN_YEARS, AIRCRAFT_AVAC_RATING, AIRCRAFT_FINANCE_TYPE, AIRCRAFT_OWNER,
       AIRCRAFT_OWNER_CLIENT_ID, AIRCRAFT_MANAGER, AIRCRAFT_MANAGER_CLIENT_ID, AIRCRAFT_OPERATOR, AIRCRAFT_OPERATOR_CLIENT_ID, AIRCRAFT_APPRAISER,
       AIRCRAFT_APPRAISER_CLIENT_ID, AIRCRAFT_APRAISER_DATA_ISTAT_GUIEDELINES, AIRCRAFT_VALUATION_DATE, AIRCRAFT_MAINTENANCE_CERTIFICATE,
       AIRCRAFT_THIRD_PARTY_USABILITY, AIRCRAFT_RATING_DATE, AIRCRAFT_RATING, AIRCRAFT_LESSEE_NAME, AIRCRAFT_LESSEE_RATING, AIRCRAFT_LESSEE_RATING_KR,
       AIRCRAFT_LESSEE_LEASE_END_DATE, AIRCRAFT_SUB_LESSEE_NAME, AIRCRAFT_SUB_LESSEE_RATING, AIRCRAFT_SUB_LESSEE_RATING_KR, AIRCRAFT_SUB_LESSEE_LEASE_END_DATE,
       AIRCRAFT_PLEDGED_LIQUIDITY_RESERVE, AIRCRAFT_PLEDGED_LIQUIDITY_RESERVE_CURRENCY, AIRCRAFT_LEASE_RATE, AIRCRAFT_LEASE_RATE_CURRENCY,
       AIRCRAFT_LEASE_RATE_PERIOD, AIRCRAFT_LEASED_RATE_CURRENT_LEASE_CURRENT_YEAR, REGION_OPERATOR, MARKET_CLASS, MARKET_CLASS_DETAIL, MARKTWERT_BM_IN_USD,
       DATUM_MARKTWERT_BM, WERTINDIKATION_IN_USD, AIRCRAFT_STATUS, DATUM_AIRCRAFT_STATUS, CREATED_USER, CREATED_TIMESTAMP
from AMC.TABLE_AVIATION_ASSET_CURRENT as BASE_TAPE
;
-- CI END FOR ALL TAPES