--------------------
-- MARITIME_ASSET --
--------------------
-- CI START FOR ALL TAPES
-- Drop View
drop view AMC.TAPE_MARITIME_ASSET_FINISH;
-- View erstellen
create or replace view AMC.TAPE_MARITIME_ASSET_FINISH as
select CUT_OFF_DATE,   -- hier ist die Reihenfolge der ersten 11 Spalten auf Wunsch von EY angepasst um eine Spaltengleichheit zwischen den Asset Tapes zu erhalten
       ASSET_ID,
       ASSET_TYPE,
       ASSET_DESCRIPTION,
       BRANCH,
       NULL as SHIP_BASE_VALUE_EUR,
       NULL as SHIP_BASE_VALUE_OC,
       NULL as SHIP_BASE_VALUE_CURRENCY,
       SHIP_MARKET_VALUE_EUR,
       NULL as SHIP_MARKET_VALUE_OC,
       NULL as SHIP_MARKET_VALUE_CURRENCY,
       APPRAISER_DATA_CUT_OFF_DATE,SHIP_IMO_NUMBER, SHIP_TYPE_CLASS, SHIP_HANDOVER_DATE,
       SHIP_AGE, SHIP_VESSEL_NAME, SHIP_TYPE_OF_VESSEL_SEGMENT, SHIP_TYPE_OF_VESSEL_SUB_SEGMENT, SHIP_HAS_GEAR, TYPE_OF_GEAR, SHIP_ICE_CLASS, SHIP_VESSEL_DELIVERED, SHIP_SHIPYARD,
       SHIP_COUNTRY_OF_YARD, SHIP_REGISTRY_JURISDICTION_OF_THE_VESSEL, EMPTY_WEIGHT_IN_LWT, SHIP_CAPACITY, SHIP_CAPACITY_UNIT, SHIP_IN_CONSTRUCTIPON, SHIP_ADDITIONAL_FEATURES,
       CLASS_CERTIFICATE_UNTILL, SHIP_OPEX_USD, SHIP_THE_LATEST_TECHNICAL_INSPECTION_INSTRUCTED_BY_THE_BANK, SHIP_LATEST_VALUATION_DATE, SHIP_APPRAISER, SHIP_VALUE_OF_LATEST_VALUATION_USD,
       SHIP_CHARTERER, SHIP_CHARTERERS_EXTERNAL_RATING, SHIP_CHARTER_BEGIN, SHIP_CHARTER_END, SHIP_CHARTER_RATE_USD, SHIP_ONE_YEAR_TC_RATE_MARKET_QUOTE_USD, CHARTER_TYPE, SHIP_LAY_UP,
       SHIP_LAY_UP_SINCE, IMO_ODER_KUNDENNUMMER, BESICHTIGUNGSDATUM, ABSCHLAG, MARKTWERT_GUELTIG, CURRENCY, SHIP_APPRAISER_1, SHIP_APPRAISER_TYPE_1, SHIP_APPRAISER_VALUE_1,
       SHIP_APPRAISER_QUOTA_1, SHIP_APPRAISER_GEWICHTUNG_1, SHIP_APPRAISER_INDEXIERUNG_1, SHIP_APPRAISER_2, SHIP_APPRAISER_TYPE_2, SHIP_APPRAISER_VALUE_2, SHIP_APPRAISER_QUOTA_2,
       SHIP_APPRAISER_GEWICHTUNG_2, SHIP_APPRAISER_INDEXIERUNG_2, SHIP_APPRAISER_3, SHIP_APPRAISER_TYPE_3, SHIP_APPRAISER_VALUE_3, SHIP_APPRAISER_QUOTA_3, SHIP_APPRAISER_GEWICHTUNG_3,
       SHIP_APPRAISER_INDEXIERUNG_3, SHIP_APPRAISER_4, SHIP_APPRAISER_TYPE_4, SHIP_APPRAISER_VALUE_4, SHIP_APPRAISER_QUOTA_4, SHIP_APPRAISER_GEWICHTUNG_4, SHIP_APPRAISER_INDEXIERUNG_4,
       SHIP_APPRAISER_5, SHIP_APPRAISER_TYPE_5, SHIP_APPRAISER_VALUE_5, SHIP_APPRAISER_QUOTA_5, SHIP_APPRAISER_GEWICHTUNG_5, SHIP_APPRAISER_INDEXIERUNG_5, SHIP_APPRAISER_6,
       SHIP_APPRAISER_TYPE_6, SHIP_APPRAISER_VALUE_6, SHIP_APPRAISER_QUOTA_6, SHIP_APPRAISER_GEWICHTUNG_6, SHIP_APPRAISER_INDEXIERUNG_6, CREATED_USER, CREATED_TIMESTAMP
from AMC.TABLE_MARITIME_ASSET_CURRENT as BASE_TAPE
;
-- CI END FOR ALL TAPES