--------------------------------------------------
-- PROTECTION_TO_INSTRUMENT TAPE EZB DICTIONARY --
--------------------------------------------------
-- CI START FOR ALL TAPES
-- Drop View
drop view AMC.TAPE_COLLATERALIZATION_PROTECTION_TO_INSTRUMENT_EZB;
-- View erstellen
create or replace view AMC.TAPE_COLLATERALIZATION_PROTECTION_TO_INSTRUMENT_EZB as
select distinct
    -- GENERAL
    varchar_format(CUT_OFF_DATE,'YYYY-MM-DD') as DT_RFRNC,
    cast(FACILITY_ID as VARCHAR(60)) as INSTRMNT_ID,
    cast(PROTECTION_ID as VARCHAR(60)) as PRTCTN_ID,
    -- FINANCIAL INFORMATION
    stg.NUMBER2STRECB(coalesce(PROTECTION_ALLOCATED_VALUE,0),2) as PRTCTN_ALLCTD_VL,
    stg.NUMBER2STRECB(THIRD_PARTY_PRIORITY_CLAIMS,2) as THRD_PRTY_PRRTY_CLMS,
    -- OPTIONAL
    cast(ADD_NMRC1 as FLOAT) as ADD_NMRC1,
    cast(ADD_NMRC2 as FLOAT) as ADD_NMRC2,
    varchar_format(ADD_DT1,'YYYY-MM-DD') as ADD_DT1,
    cast(ADD_TXT1 as VARCHAR(255)) as ADD_TXT1,
    cast(ADD_TXT2 as VARCHAR(255)) as ADD_TXT2
from AMC.TABLE_COLLATERALIZATION_PROTECTION_TO_INSTRUMENT_CURRENT as TAPE
;
call stg.TEST_PROC_GRANT_PERMISSION_TO('AMC','TAPE_COLLATERALIZATION_PROTECTION_TO_INSTRUMENT_EZB');

-- CI END FOR ALL TAPES
