---------------------------------------------------------
-- PROTECTION_TO_INSTRUMENT TAPE EZB DICTIONARY OUTPUT --
---------------------------------------------------------
-- CI START FOR ALL TAPES
-- Drop View
drop view AMC.TAPE_COLLATERALIZATION_PROTECTION_TO_INSTRUMENT_TASSLER;
-- View erstellen
create or replace view AMC.TAPE_COLLATERALIZATION_PROTECTION_TO_INSTRUMENT_TASSLER as
select distinct
    -- GENERAL
    CUT_OFF_DATE as DT_RFRNC,
    FACILITY_ID as INSTRMNT_ID,
    PROTECTION_ID as PRTCTN_ID,
    -- FINANCIAL INFORMATION
    PROTECTION_ALLOCATED_VALUE as PRTCTN_ALLCTD_VL,
    THIRD_PARTY_PRIORITY_CLAIMS as THRD_PRTY_PRRTY_CLMS,
    -- OPTIONAL
    ADD_NMRC1,
    ADD_NMRC2,
    ADD_DT1,
    ADD_TXT1,
    ADD_TXT2
from AMC.TABLE_COLLATERALIZATION_PROTECTION_TO_INSTRUMENT_CURRENT as TAPE
;
call stg.TEST_PROC_GRANT_PERMISSION_TO('AMC','TAPE_COLLATERALIZATION_PROTECTION_TO_INSTRUMENT_TASSLER');

-- CI END FOR ALL TAPES
