-------------------------------------------
-- PROTECTION TAPE EZB DICTIONARY OUTPUT --
-------------------------------------------
-- CI START FOR ALL TAPES
-- Drop View
drop view AMC.TAPE_COLLATERALIZATION_PROTECTION_TASSLER;
-- View erstellen
create or replace view AMC.TAPE_COLLATERALIZATION_PROTECTION_TASSLER as
select distinct
    -- General
    MATURITY_DATE as DT_MTRTY_PRTCTN,
    CUT_OFF_DATE as DT_RFRNC,
    NATIONAL_ID as NTNL_ID,
    PROTECTION_ID as PRTCTN_ID,
    PROTECTION_PROVIDER_ID as PRTCTN_PRVDR_ID,
    ADDRESS as RL_ESTT_ADDRSS,
    COLLATERAL_LOCATION as RL_ESTT_CLLTRL_LCTN,
    ASSET_LOCATION as RL_ESTT_CLLTRL_LCTN_INT,
    CITY as RL_ESTT_CTY,
    POST_CODE as RL_ESTT_PST_CD,
    -- Classification
    MARKET_VALUE_HAIRCUT as HRCT_MV,
    PROTECTION_IS_CALLED as PRTCTN_CLLD,
    PROTECTION_TYPE as TYP_PRTCTN,
    PROTECTION_TYPE_INTERNAL as TYP_PRTCTN_INTRNL,
    PROTECTION_VALUE_TYPE as TYP_PRTCTN_VL,
    -- Appraisal
    APPRAISAL_CURRENCY as APPRSL_CRRNCY,
    APPRAISER as APPRSR,
    LAST_FULL_APPRAISAL_DATE as DT_LST_FLL_APPRSL,
    ORIGINAL_PROTECTION_VALUE_DATE as DT_ORGNL_PRTCTN_VL,
    PROTECTION_VALUE_DATE as DT_PRTCTN_VL,
    ORIGINAL_PROTECTION_VALUE as ORGNL_PRTCTN_VL,
    FORCED_SALE_VALUE as PRTCTN_FRCD_SL_VL,
    APPRAISED_MARKET_VALUE as PRTCTN_VL,
    APPRAISED_MARKET_VALUE_NONPERFORMING as PRTCTN_VL_NPE,
    VALUATION_APPROACH as PRTCTN_VLTN_APPRCH,
    APPRAISAL_DATE_PREVIOUS as DT_APPRSL_PRVS,
    APPRAISED_MARKET_VALUE_PREVIOUS as PRTCTN_VL_PRVS,
    -- Collateral Features
    CONSTRUCTION_STATUS as CNSTRCTN_STTS,
    CONSTRUCTION_STATUS_DATE as DT_CNSTRCTN_STTS,
    FIRST_USAGE_DATE as DT_FRST_USG,
    DEVELOPMENT_STATUS as DVLPMNT_STTS,
    MAIN_PURPOSE as MN_PRPS,
    IS_PRIME_LOCATION as PRM_LCTN,
    -- Financial Information
    INCOME_CURRENCY as CRE_INCM_CRRNCY,
    OPERATING_EXPENSES_YEARLY as CRE_YRLY_EXPNSS,
    INCOME_YEARLY as CRE_YRLY_INCM,
    -- Optional
    ADD_NMRC1,
    ADD_NMRC2,
    ADD_NMRC3,
    ADD_NMRC4,
    ADD_DT1,
    ADD_DT2,
    ADD_DT3,
    ADD_TXT1,
    ADD_TXT2,
    ADD_TXT3
from AMC.TABLE_COLLATERALIZATION_PROTECTION_CURRENT as TAPE
;
call stg.TEST_PROC_GRANT_PERMISSION_TO('AMC','TAPE_COLLATERALIZATION_PROTECTION_TASSLER');

-- CI END FOR ALL TAPES