--------------------------------------------------
-- INSTRUMENT_TO_ENTITY TAPE EZB DICTIONARY OUTPUT --
--------------------------------------------------
-- CI START FOR ALL TAPES
-- Drop View
drop view AMC.TAPE_PORTFOLIO_INSTRUMENT_TO_ENTITY_TASSLER;
-- View erstellen
create or replace view AMC.TAPE_PORTFOLIO_INSTRUMENT_TO_ENTITY_TASSLER as
select distinct
    CUT_OFF_DATE as DT_RFRNC,
    CLIENT_ID as ENTTY_ID,
    FACILITY_ID  as INSTRMNT_ID,
    JOINT_LIABILITY_AMOUNT as JNT_LBLTY_AMNT,
    ADD_NMRC1,
    ADD_NMRC2,
    ADD_DT1,
    ADD_TXT1,
    ADD_TXT2
from AMC.TABLE_PORTFOLIO_INSTRUMENT_TO_ENTITY_CURRENT as TAPE
;

call stg.TEST_PROC_GRANT_PERMISSION_TO('AMC','TAPE_PORTFOLIO_INSTRUMENT_TO_ENTITY_TASSLER');
-- CI END FOR ALL TAPES