
-- VIEW erstellen
------------------------------------------------------------------------------------------------------------------------
drop view CALC.VIEW_CASH_FLOW_PAST_PRE;
create or replace view CALC.VIEW_CASH_FLOW_PAST_PRE(CUT_OFF_DATE, FACILITY_ID,CASH_FLOW_TYPE,TRANSACTION_VALUE_TRADECURRENCY,TRANSACTION_TRADECURRENCY_ISO,VALUTA_DATE,PAYMENT_DATE,ERFOLGSART,SOURCE_SYSTEM,PAST_DUE_ALIAS,TRANSACTION_ID,CANCELLATION_TRANSACTION_ID,IS_BAD_DEBT_LOSS,COMMENT,CREATED_USER,CREATED_TIMESTAMP) as
with ALL_CFS as (
    select *
    from CALC.VIEW_CASH_FLOW_PAST_AOER
    union all
    select *
    from CALC.VIEW_CASH_FLOW_PAST_CBB
    union all
    select *
    from CALC.VIEW_CASH_FLOW_PAST_MANUAL_CORRECTIONS
    union all
    select *
    from CALC.VIEW_CASH_FLOW_PAST_COMPENSATION_CORRECTION
)
select CUT_OFF_DATE,
       FACILITY_ID, CASH_FLOW_TYPE,
       TRANSACTION_VALUE_TRADECURRENCY, TRANSACTION_TRADECURRENCY_ISO,
       VALUTA_DATE, PAYMENT_DATE, ERFOLGSART, SOURCE_SYSTEM,
       PAST_DUE_ALIAS,
       TRANSACTION_ID, CANCELLATION_TRANSACTION_ID, IS_BAD_DEBT_LOSS, COMMENT,
       CREATED_USER, CREATED_TIMESTAMP
from ALL_CFS
;
------------------------------------------------------------------------------------------------------------------------

-- CI START FOR ALL TAPES
-- Current-Tabelle erstellen
call STG.TEST_PROC_BACKUP_AND_DROP('AMC','TABLE_CASH_FLOW_PAST_PRE_CURRENT');
create table AMC.TABLE_CASH_FLOW_PAST_PRE_CURRENT like CALC.VIEW_CASH_FLOW_PAST_PRE distribute by hash(FACILITY_ID) in SPACE_AMC_A,SPACE_AMC_B,SPACE_AMC_C,SPACE_AMC_D,SPACE_AMC_E,SPACE_AMC_F;
create index AMC.INDEX_CASH_FLOW_PAST_PRE_CURRENT_FACILITY_ID on AMC.TABLE_CASH_FLOW_PAST_PRE_CURRENT (FACILITY_ID);
call STG.TEST_PROC_LOAD_AND_DROP_BACKUP_FOR('AMC','TABLE_CASH_FLOW_PAST_PRE_CURRENT');
-- Archiv-Tabelle erstellen
call STG.TEST_PROC_BACKUP_AND_DROP('AMC','TABLE_CASH_FLOW_PAST_PRE_ARCHIVE');
create table AMC.TABLE_CASH_FLOW_PAST_PRE_ARCHIVE like CALC.VIEW_CASH_FLOW_PAST_PRE distribute by hash(FACILITY_ID) partition by RANGE (CUT_OFF_DATE) (starting '1.1.2015' ending '31.12.2030' EVERY 1 Month) in SPACE_AMC_A,SPACE_AMC_B,SPACE_AMC_C,SPACE_AMC_D,SPACE_AMC_E,SPACE_AMC_F;
create index AMC.INDEX_CASH_FLOW_PAST_PRE_ARCHIVE_FACILITY_ID on AMC.TABLE_CASH_FLOW_PAST_PRE_ARCHIVE (FACILITY_ID);
call STG.TEST_PROC_LOAD_AND_DROP_BACKUP_FOR('AMC','TABLE_CASH_FLOW_PAST_PRE_ARCHIVE');
-- CI END FOR ALL TAPES

-- SWITCH Views erstellen
call STG.TEST_PROC_DROP_AND_CREATE_SWITCH('AMC','TABLE_CASH_FLOW_PAST_PRE_CURRENT');
call STG.TEST_PROC_DROP_AND_CREATE_SWITCH('AMC','TABLE_CASH_FLOW_PAST_PRE_ARCHIVE');