
drop view CALC.VIEW_CASH_FLOW_PAST_GIRO_TASSLER;
create or replace view CALC.VIEW_CASH_FLOW_PAST_GIRO_TASSLER as
    select
        FACILITY_ID,
        UMSATZ_ART,
        TRANSAKTION_WERT_WHRG,
        TRANSAKTION_WHRG_SCHL,
        VALUTA_DATUM,
        BUCHUNGS_DATUM,
        ERFOLGSART,
        CUT_OFF_DATE,
        BUCHUNGS_ID,
        STORNO_BUCHUNGS_ID,
        CURRENT_USER as TAPE_CREATED_USER,
        CURRENT_TIMESTAMP as TAPE_CREATED_TIMESTAMP
    from CALC.SWITCH_CASH_FLOW_PAST_GIRO_CURRENT
;

-- CI START FOR ALL TAPES

-- Current-Tabelle erstellen
call STG.TEST_PROC_BACKUP_AND_DROP('AMC','TABLE_CASH_FLOW_PAST_GIRO_TASSLER_CURRENT');
create table AMC.TABLE_CASH_FLOW_PAST_GIRO_TASSLER_CURRENT like CALC.VIEW_CASH_FLOW_PAST_GIRO_TASSLER distribute by hash(FACILITY_ID) in SPACE_AMC_A,SPACE_AMC_B,SPACE_AMC_C,SPACE_AMC_D,SPACE_AMC_E,SPACE_AMC_F;
create index AMC.INDEX_CASH_FLOW_PAST_GIRO_TASSLER_CURRENT_FACILITY_ID on AMC.TABLE_CASH_FLOW_PAST_GIRO_TASSLER_CURRENT (FACILITY_ID);
call STG.TEST_PROC_LOAD_AND_DROP_BACKUP_FOR('AMC','TABLE_CASH_FLOW_PAST_GIRO_TASSLER_CURRENT');

-- CI END FOR ALL TAPES
