----------------------
-- FACILITY für PWC --
----------------------
-- CI START FOR ALL TAPES
-- Drop View
drop view AMC.TAPE_FACILITY_TASSLER;
-- View erstellen
create or replace view AMC.TAPE_FACILITY_TASSLER as
select FACILITY_ID                                       as FACILITY_ID,
       SYSTEM_SATZART                                    as SYSTEM,
       PRODUCT_GROUP                                     as SYSTEM_PRODUKTGRUPPE,
       IS_PWC_FOCUS                                      as FOKUSSYSTEM,
       IN_SPOT                                           as GNI,
       IN_BW                                             as SAP,
       CLIENT_TYPE                                       as GNI_TYP,       --?
       BRANCH_FACILITY                                   as GNI_ZUORDNUNG, --?
       LEADING_FACILITY_ID                               as GNI_LEITKONTO, -- FOCS
       PARENT_FACILITY_ID                                as GNI_PARENTFACILITY,
       CORRESPONDING_LIMIT_ID                            as GNI_RAHMEN,
       CLIENT_ID                                         as GNI_KUNDE,
       CLIENT_ID_LEADING                                 as GNI_KUNDE_LEADING,
       CLIENT_NO_BW                                      as SAP_KUNDE,
       CLIENT_NAME_ANONYMIZED                            as GNI_NAME,
       GROUP_ID                                          as GNI_KONZERNID,
       GROUP_NAME                                        as GNI_KONZERN,
       GVK_BUNDESBANKNUMMER                              as GNI_BUNDESBANKNR,
       CLIENT_COUNTRY_ALPHA2                             as GNI_KUNDELAND,
       PORTFOLIO_CLIENT_PERSON_IWHS                      as GNI_KUBE_OE,
       KUSY                                              as SAP_KUSY,
       CLIENT_NACE                                       as GNI_NACE,
       SEGMENT                                           as SAP_SEGMENT,
       PRODUCTTYPE                                       as GNI_PRODUKTTYP,
       PRODUCT_BW                                        as SAP_PRODUKT,
       PRODUCT_BW_TEXT                                   as SAP_PRODUKTTEXT,
       CURRENCY                                          as GNI_WAEHRUNG,
       CURRENCY_BW                                       as SAP_WAEHRUNG,
       RATING_NUMERIC_FVC                                as GNI_FVC_RATING,
       RATING_BW                                         as SAP_RATING,
       RATING_ID_KUNDE                                   as GNI_KUNDERATING,
       PROBABILITY_OF_DEFAULT_RATE_ZEB                   as GNI_ZEB_PD,
       PROBABILITY_OF_DEFAULT_RATE_BW                    as SAP_PD,
       RATING_MODULE_ZEB                                 as GNI_ZEB_RATINGMODUL,
       RATING_MODULE_BW                                  as SAP_RATINGMODUL,
       RATING_MODULE_NAME_BW                             as SAP_MODULNAME,
       RATING_SUBMODULE_BW                               as SAP_SUBMODUL,
       RATING_MODULE_DESCRIPTION_BW                      as SAP_MODULBESCHREIBUNG,
       RATING_BW_TYPE                                    as SAP_IRBA_KSA,
       RATING_MODULE_CLIENT                              as GNI_KUNDEMODUL,
       RATING_DATE_FVC                                   as GNI_FVC_RATINGDATUM,
       DEFAULT_BW                                        as SAP_AUSFALL,
       PRJ_IS_FINREP_FORBORNE                            as GNI_ZEB_FORBORNE,
       LGD_DEFAULT_RATE_ZEB                              as GNI_ZEB_LGD,
       LGD_DEFAULT_RATE_BW                               as SAP_LGD,
       CREDIT_CONVERSION_FACTOR_BW                       as SAP_CCF,
       EAD_BW                                            as SAP_EAD,
       EL_BW                                             as SAP_EL,
       OWN_SYNDICATE_QUOTA                               as GNI_KONSORTIALANTEIL,
       PRINCIPAL_TYPE                                    as GNI_PRINCIPALTYP,
       PRINCIPAL_OUTSTANDING_EUR_SPOT                    as GNI_PRINCIPAL,
       PRINCIPAL_OUTSTANDING_EUR_COMPENSATION            as GNI_PRINCIPAL_BEI_KOMPENSATION,
       PRINCIPAL_OUTSTANDING_EUR_AVAL                    as GNI_PRINCIPALAVAL,
       PRINCIPAL_OUTSTANDING_EUR_SPOT_RAW                as GNI_PRINCIPAL_RAW,
       PRINCIPAL_OUTSTANDING_EUR_SEGUE                   as GNI_INANSPRUCHNAHME_UEBERGELEITET,
       PRINCIPAL_OUTSTANDING_EUR_BW                      as SAP_INANSPRUCHNAHME,
       BLANKO_BW                                         as SAP_BLANKO,
       OFFBALANCE_EUR                                    as GNI_OFFBALANCE,
       FREIE_LINIE                                       as SAP_FREIELINIE,
       AUSZAHLUNGSPLICHT_EUR                             as GNI_AUSZAHLUNGSPFLICHT,
       AMORTIZATION_IN_ARREARS_EUR_SPOT                  as GNI_TILGUNGSRUECKSTAND,
       AMORTIZATION_IN_ARREARS_FOR_COMPENSATION          as GNI_TILGUNGSRUECKSTAND_BEI_KOMPENSATION,
       AMORTIZATION_IN_ARREARS_EUR_SPOT_RAW              as GNI_TILGUNGSRUECKSTAND_RAW,
       INTEREST_IN_ARREARS_EUR_SPOT                      as GNI_ZINSRUECKSTAND,
       INTEREST_IN_ARREARS_FOR_COMPENSATION              as GNI_ZINSRUECKSTAND_BEI_KOMPENSATION,
       INTEREST_IN_ARREARS_EUR_SPOT_RAW                  as GNI_ZINSRUECKSTAND_RAW,
       FEES_IN_ARREARS_EUR_SPOT                          as GNI_PROVISIONSRUECKSTAND,
       FEES_IN_ARREARS_EUR_SPOT_RAW                      as GNI_PROVISIONSRUECKSTAND_RAW,
       STUECKZINSEN_BW                                   as SAP_STUECKZINSEN,
       RIVO_STAGE                                        as GNI_RIVO_STAGE,
       SAP_EWBTES                                        as SAP_EWBTES,
       FAIR_VALUE_ADJUSTMENT_EUR                         as GNI_FVA,
       DAYS_PAST_DUE_BW                                  as GNI_DAYS_PAST_DUE,
       HEDGING_FLAG_BW                                   as SAP_HEDGING_FLAG,
       IS_AVAL                                           as AVAL,
       -- RIVO
       SPECIFIC_PROVISION_AMOUNT_EUR                     as ABIT_EWB_EUR,
       SPECIFIC_PROVISION_AMOUNT_OC                      as ABIT_EWB_OC,
       RISK_PROVISION_ABIT_EXCHANGE_RATE_EUR2OC          as ABIT_FX_EWB,
       LOAN_LOSS_PROVISION_AMOUNT_EUR                    as ABIT_RST_EUR,
       LOAN_LOSS_PROVISION_AMOUNT_OC                     as ABIT_RST_OC,
       RISK_PROVISION_ABIT_EXCHANGE_RATE_EUR2OC          as ABIT_FX_RST,
       ZEB_STAGE_ONBALANCE as ZEB_STAGE_ONBALANCE,
       ZEB_EWB_EUR_ONBALANCE as ZEB_EWB_EUR_ONBALANCE,
       ZEB_EWB_OC_ONBALANCE as ZEB_EWB_OC_ONBALANCE,
       RISK_PROVISION_ZEB_EXCHANGE_RATE_EUR2OC           as ZEB_FX_EWB_ONBALANCE,
       ZEB_STAGE_OFFBALANCE as ZEB_STAGE_OFFBALANCE,
       ZEB_EWB_EUR_OFFBALANCE as ZEB_EWB_EUR_OFFBALANCE,
       ZEB_EWB_OC_OFFBALANCE as ZEB_EWB_OC_OFFBALANCE,
       RISK_PROVISION_ZEB_EXCHANGE_RATE_EUR2OC           as ZEB_FX_EWB_OFFBALANCE,
       -- Additional Info
       PRODUCTTYPE_DETAIL,
       PORTFOLIO_CLIENT_SIMPLIFIED,
       AMORTIZATION_TYPE,
       CURRENT_CONTRACTUAL_MATURITY_DATE,
       NEXT_AMORTIZATION_TO_BE_PAID,
       LOANSTATE_SPOT,
       LOANSTATE_LIQ,
       IS_IN_GUARANTEE,
       PRINCIPAL_OUTSTANDING_EUR_KR as FAIR_VALUE_ADJUSTED_KR,
       -- Defaults
       CUT_OFF_DATE,
       CREATED_USER,
       CREATED_TIMESTAMP
from AMC.TABLE_FACILITY_CURRENT
where CUT_OFF_DATE = DATA_CUT_OFF_DATE
;

grant select on AMC.TAPE_FACILITY_TASSLER to group NLB_MW_ADAP_S_GNI_TROOPER;
-- CI END FOR ALL TAPES