-- ZEB Control Off-Balance Daten

--  VIEW erstellen
drop view CALC.VIEW_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE;
create or replace view CALC.VIEW_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE as
    with ZEB_NLB as (
        select
        PORTFOLIO.FACILITY_ID,
        PORTFOLIO.CUT_OFF_DATE,
        PORTFOLIO.FACILITY_ID_NLB,
        PORTFOLIO.FACILITY_ID_BLB,
        PORTFOLIO.FACILITY_ID_CBB,
        ZEB_NLB.R_CURRENCY_ID,
        ZEB_NLB.R_EXCHANGE_RATE,
        ZEB_NLB.R_EXPOSURE_AT_DEFAULT_AMT,
        ZEB_NLB.E_LGD_COLL_RATE,
        ZEB_NLB.R_LGD_NET_RATE,
        ZEB_NLB.R_LOSS_GIVEN_DEFAULT_RATE,
        ZEB_NLB.R_EAD_TOTAL_AMT,
        ZEB_NLB.R_EXP_LOSS_AMT,
        ZEB_NLB.E_DAYS_PAST_DUE_NO,
        ZEB_NLB.R_RATING_ID,
        ZEB_NLB.R_INIT_RATING_MODULE,
        ZEB_NLB.R_INIT_RATING_SECTOR,
        ZEB_NLB.R_RATING_SUB_MODULE,
        ZEB_NLB.E_BOOK_VALUE_AC_AMT,
        ZEB_NLB.E_CONTRACT_SIGNING_DATE,
        ZEB_NLB.E_BALANCE_AMT,
        ZEB_NLB.E_NOMINAL_VALUE_AMT,
        ZEB_NLB.PRJ_IS_FINREP_FORBORNE,
        ZEB_NLB.R_CREDIT_CONVERSION_FACTOR_RATE,
        ZEB_NLB.R_ONE_YEAR_PROB_OF_DEFAULT_RATE,
        ZEB_NLB.R_LIFETIME_PROB_DEF_RATE,
        ZEB_NLB.R_EXP_LIFETIME_LOSS_AMT, -- EWB
        ZEB_NLB.E_END_OF_CONTRACT_DATE,
        ZEB_NLB.R_IS_POCI,
        ZEB_NLB.R_INIT_RATING_ID,
        ZEB_NLB.R_LOAN_LOSS_PROVISION_AMT,
        ZEB_NLB.R_RATING_MODULE,
        ZEB_NLB.R_STAGE_LLP_ID,
        ZEB_NLB.R_STAGE_LLP_REASON_DESC,
        ZEB_NLB.E_PROLONGATION_DATE,
        ZEB_NLB.R_ON_BALANCE_ID
        from NLB.ZEB_CONTROL_CURRENT as ZEB_NLB
        inner join CALC.SWITCH_PORTFOLIO_CURRENT as PORTFOLIO on PORTFOLIO.CUT_OFF_DATE= ZEB_NLB.CUTOFFDATE and PORTFOLIO.FACILITY_ID_NLB||'_KK'=ZEB_NLB.FACILITY_ID
    ),
    ZEB_BLB as (
        select
        PORTFOLIO.FACILITY_ID,
        PORTFOLIO.CUT_OFF_DATE,
        PORTFOLIO.FACILITY_ID_NLB,
        PORTFOLIO.FACILITY_ID_BLB,
        PORTFOLIO.FACILITY_ID_CBB,
        ZEB_BLB.R_CURRENCY_ID,
        ZEB_BLB.R_EXCHANGE_RATE,
        ZEB_BLB.R_EXPOSURE_AT_DEFAULT_AMT,
        ZEB_BLB.E_LGD_COLL_RATE,
        ZEB_BLB.R_LGD_NET_RATE,
        ZEB_BLB.R_LOSS_GIVEN_DEFAULT_RATE,
        ZEB_BLB.R_EAD_TOTAL_AMT,
        ZEB_BLB.R_EXP_LOSS_AMT,
        ZEB_BLB.E_DAYS_PAST_DUE_NO,
        ZEB_BLB.R_RATING_ID,
        ZEB_BLB.R_INIT_RATING_MODULE,
        ZEB_BLB.R_INIT_RATING_SECTOR,
        ZEB_BLB.R_RATING_SUB_MODULE,
        ZEB_BLB.E_BOOK_VALUE_AC_AMT,
        ZEB_BLB.E_CONTRACT_SIGNING_DATE,
        ZEB_BLB.E_BALANCE_AMT,
        ZEB_BLB.E_NOMINAL_VALUE_AMT,
        ZEB_BLB.PRJ_IS_FINREP_FORBORNE,
        ZEB_BLB.R_CREDIT_CONVERSION_FACTOR_RATE,
        ZEB_BLB.R_ONE_YEAR_PROB_OF_DEFAULT_RATE,
        ZEB_BLB.R_LIFETIME_PROB_DEF_RATE,
        ZEB_BLB.R_EXP_LIFETIME_LOSS_AMT,
        ZEB_BLB.E_END_OF_CONTRACT_DATE,
        ZEB_BLB.R_IS_POCI,
        ZEB_BLB.R_INIT_RATING_ID,
        ZEB_BLB.R_LOAN_LOSS_PROVISION_AMT, -- EWB
        ZEB_BLB.R_RATING_MODULE,
        ZEB_BLB.R_STAGE_LLP_ID,
        ZEB_BLB.R_STAGE_LLP_REASON_DESC,
        ZEB_BLB.E_PROLONGATION_DATE,
        ZEB_BLB.R_ON_BALANCE_ID
        from BLB.ZEB_CONTROL_CURRENT as ZEB_BLB
        inner join CALC.SWITCH_PORTFOLIO_CURRENT as PORTFOLIO on PORTFOLIO.CUT_OFF_DATE=ZEB_BLB.CUTOFFDATE and PORTFOLIO.FACILITY_ID_NLB||'_KK'=ZEB_BLB.FACILITY_ID
     ),
    ZEB_ANL as (
        select
        PORTFOLIO.FACILITY_ID,
        PORTFOLIO.CUT_OFF_DATE,
        PORTFOLIO.FACILITY_ID_NLB,
        PORTFOLIO.FACILITY_ID_BLB,
        PORTFOLIO.FACILITY_ID_CBB,
        ZEB_ANL.R_CURRENCY_ID,
        ZEB_ANL.R_EXCHANGE_RATE,
        ZEB_ANL.R_EXPOSURE_AT_DEFAULT_AMT,
        ZEB_ANL.E_LGD_COLL_RATE,
        ZEB_ANL.R_LGD_NET_RATE,
        ZEB_ANL.R_LOSS_GIVEN_DEFAULT_RATE,
        ZEB_ANL.R_EAD_TOTAL_AMT,
        ZEB_ANL.R_EXP_LOSS_AMT,
        ZEB_ANL.E_DAYS_PAST_DUE_NO,
        ZEB_ANL.R_RATING_ID,
        ZEB_ANL.R_INIT_RATING_MODULE,
        ZEB_ANL.R_INIT_RATING_SECTOR,
        ZEB_ANL.R_RATING_SUB_MODULE,
        ZEB_ANL.E_BOOK_VALUE_AC_AMT,
        ZEB_ANL.E_CONTRACT_SIGNING_DATE,
        ZEB_ANL.E_BALANCE_AMT,
        ZEB_ANL.E_NOMINAL_VALUE_AMT,
        ZEB_ANL.PRJ_IS_FINREP_FORBORNE,
        ZEB_ANL.R_CREDIT_CONVERSION_FACTOR_RATE,
        ZEB_ANL.R_ONE_YEAR_PROB_OF_DEFAULT_RATE,
        ZEB_ANL.R_LIFETIME_PROB_DEF_RATE,
        ZEB_ANL.R_EXP_LIFETIME_LOSS_AMT,
        ZEB_ANL.E_END_OF_CONTRACT_DATE,
        ZEB_ANL.R_IS_POCI,
        ZEB_ANL.R_INIT_RATING_ID,
        ZEB_ANL.R_LOAN_LOSS_PROVISION_AMT, -- EWB
        ZEB_ANL.R_RATING_MODULE,
        ZEB_ANL.R_STAGE_LLP_ID,
        ZEB_ANL.R_STAGE_LLP_REASON_DESC,
        ZEB_ANL.E_PROLONGATION_DATE,
        ZEB_ANL.R_ON_BALANCE_ID
        from ANL.ZEB_CONTROL_CURRENT as ZEB_ANL
        inner join CALC.SWITCH_PORTFOLIO_CURRENT as PORTFOLIO on PORTFOLIO.CUT_OFF_DATE=ZEB_ANL.CUTOFFDATE and PORTFOLIO.FACILITY_ID_NLB||'_KK'=ZEB_ANL.FACILITY_ID
    ),
    ZEB as (
        select * from ZEB_NLB
        union all
        select * from ZEB_BLB
        union all
        select * from ZEB_ANL
    )
    select distinct
        PORTFOLIO.FACILITY_ID,
        PORTFOLIO.CUT_OFF_DATE,
        PORTFOLIO.FACILITY_ID_CBB,
        RATING.RATING_ID                            as RATING_ID_FVC,
        RATING.LGD_IN_PROZENT                       as LGD_IN_PROZENT_FVC,
        RATING.RISIKOGEWICHT_IN_PROZENT             as RISIKOGEWICHT_IN_PROZENT_FVC,
        RATING.RATING_DATE                          as RATING_DATE
        , ZEB.R_CURRENCY_ID
        , ZEB.R_EXCHANGE_RATE
        , ZEB.R_EXPOSURE_AT_DEFAULT_AMT
        , ZEB.E_LGD_COLL_RATE
        , ZEB.R_LGD_NET_RATE
        , ZEB.R_LOSS_GIVEN_DEFAULT_RATE
        , ZEB.R_EAD_TOTAL_AMT
        , ZEB.R_EXP_LOSS_AMT
        , ZEB.E_DAYS_PAST_DUE_NO
        , ZEB.R_RATING_ID
        , ZEB.R_INIT_RATING_MODULE
        , ZEB.R_INIT_RATING_SECTOR
        , ZEB.R_RATING_SUB_MODULE
        , ZEB.E_BOOK_VALUE_AC_AMT
        , ZEB.E_CONTRACT_SIGNING_DATE
        , ZEB.E_BALANCE_AMT
        , ZEB.E_NOMINAL_VALUE_AMT
        , ZEB.PRJ_IS_FINREP_FORBORNE
        , ZEB.R_CREDIT_CONVERSION_FACTOR_RATE
        , ZEB.R_ONE_YEAR_PROB_OF_DEFAULT_RATE
        , ZEB.R_LIFETIME_PROB_DEF_RATE,
        -- neue Spalten nach Issue #487
        ZEB.R_EXP_LIFETIME_LOSS_AMT,
        ZEB.E_END_OF_CONTRACT_DATE,
        ZEB.R_IS_POCI,
        ZEB.R_INIT_RATING_ID,
        ZEB.R_LOAN_LOSS_PROVISION_AMT,
        ZEB.R_RATING_MODULE,
        ZEB.R_STAGE_LLP_ID,
        ZEB.R_STAGE_LLP_REASON_DESC,
        ZEB.E_PROLONGATION_DATE,
        -- neue Spalte nach off-Balance Match
        ZEB.R_ON_BALANCE_ID,
        -- Tape Defaults
        Current_USER                                                                            as CREATED_USER,       -- Letzter Nutzer, der diese Tabelle gebaut hat.
        Current_TIMESTAMP                                                                       as CREATED_TIMESTAMP   -- Neuester Zeitstempel, wann diese Tabelle zuletzt gebaut wurde.
    from CALC.SWITCH_PORTFOLIO_CURRENT as PORTFOLIO
    left join ZEB on ZEB.CUT_OFF_DATE = PORTFOLIO.CUT_OFF_DATE and ZEB.FACILITY_ID = PORTFOLIO.FACILITY_ID
    left join CALC.VIEW_FACILITY_RATING_FVC as RATING on PORTFOLIO.CUT_OFF_DATE= RATING.CUT_OFF_DATE and PORTFOLIO.FACILITY_ID = RATING.FACILITY_ID
;

-- CI START FOR ALL TAPES
-- Current-Tabelle erstellen
call STG.TEST_PROC_BACKUP_AND_DROP('AMC','TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE_CURRENT');
create table AMC.TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE_CURRENT like CALC.VIEW_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE distribute by hash(FACILITY_ID) in SPACE_AMC_A,SPACE_AMC_B,SPACE_AMC_C,SPACE_AMC_D,SPACE_AMC_E,SPACE_AMC_F;
create index AMC.INDEX_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE_CURRENT_FACILITY_ID on AMC.TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE_CURRENT (FACILITY_ID);
call STG.TEST_PROC_LOAD_AND_DROP_BACKUP_FOR('AMC','TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE_CURRENT');
-- Current-Tabelle erstellen
call STG.TEST_PROC_BACKUP_AND_DROP('AMC','TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE_ARCHIVE');
create table AMC.TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE_ARCHIVE like CALC.VIEW_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE distribute by hash(FACILITY_ID) partition by RANGE (CUT_OFF_DATE) (starting '1.1.2015' ending '31.12.2030' EVERY 1 Month) in SPACE_AMC_A,SPACE_AMC_B,SPACE_AMC_C,SPACE_AMC_D,SPACE_AMC_E,SPACE_AMC_F;
create index AMC.INDEX_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE_ARCHIVE_FACILITY_ID on AMC.TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE_ARCHIVE (FACILITY_ID);
call STG.TEST_PROC_LOAD_AND_DROP_BACKUP_FOR('AMC','TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE_ARCHIVE');
-- CI END FOR ALL TAPES

-- SWITCH Views erstellen
call STG.TEST_PROC_DROP_AND_CREATE_SWITCH('AMC','TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE_CURRENT');
call STG.TEST_PROC_DROP_AND_CREATE_SWITCH('AMC','TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_OFFBALANCE_ARCHIVE');