-- ZEB Control On-Balance Daten

-- VIEW erstellen
drop view CALC.VIEW_FACILITY_KREDITRISIKO_KENNZAHLEN;
create or replace view CALC.VIEW_FACILITY_KREDITRISIKO_KENNZAHLEN as
    with
    ZEB_NLB_PRE as (
        select CUTOFFDATE, R_DET_SCENARIO_ID, R_RUN_ID, R_KEY_DATE, R_CLIENT_ID, R_BANK_ID,
               case
                   when SUBSTR(FACILITY_ID,6,2) <> '30' then
                       FACILITY_ID
                   when LENGTH(FACILITY_ID) < 20 then
                       FACILITY_SUB_ID
                   else LEFT(FACILITY_ID,20)||'-31-'||SUBSTR(FACILITY_ID,25,LENGTH(FACILITY_ID)-24)
               end as FACILITY_ID,
               FACILITY_SUB_ID,
               R_STATUS, R_EFFECT_STATUS, E_BUSINESS_STATUS_ID, E_DELETION_STATUS_ID, R_CURRENCY_ID, R_EXCHANGE_RATE, R_EXPOSURE_AT_DEFAULT_AMT, R_LOAN_LOSS_PROVISION_AMT, R_LOAN_LOSS_PROVISION_PREV_AMT, R_DELTA_LOAN_LOSS_PROVISION_AMT, R_INC_LOSS_SLLP_AMT, R_STAGE_LLP_CALCULATED_ID, R_STAGE_LLP_REASON_DESC, R_STAGE_LLP_P_ID, R_ASSET_LIAB_ID, R_BOOK_VALUE_NET_AMT, R_CALC_SCENARIO_LLP_ID, R_CREDIT_ADJUSTED_INT_LLP_RATE, R_CREDIT_CONVERSION_FACTOR_RATE, R_DELTA_LOAN_LOSS_PROV_PY_AMT, R_EAD_TOTAL_AMT, R_EDIT_LLP_COMMENT_DESC, R_EDIT_LLP_DATE, R_EDIT_LLP_USER, R_EXPOSURE_METHOD_ID, R_EXP_LIFETIME_LOSS_AMT, R_EXP_LOSS_AMT, R_FORWARD_LPD_RATE, R_FORWARD_PROB_OF_DEFAULT_RATE, R_HYPOTHETICAL_RATING_ID, R_IFRS_EFF_INTEREST_RATE, R_INIT_RATING_COUNTRY_CODE, R_INIT_RATING_ID, R_INIT_RATING_MODULE, R_INIT_RATING_SECTOR, R_INIT_RATING_SUB_MODULE, R_INIT_STAGE_LLP_ID, R_IS_IMPAIRMENT_LLP, R_IS_MIGRATED, R_IS_POCI, R_IS_SIGNIFICANT_SLLP, R_IS_SIGNIFICANT_SLLP_PY, R_LGD_NET_RATE, R_LIFETIME_EFFECT_AMT, R_LIFETIME_PROB_DEF_RATE, R_LIP_EFFECT_AMT, R_LLP_IAS39_CALC_ID, R_LLP_IFRS9_CALC_ID, R_LOAN_LOSS_PROVISION_PY_AMT, R_LOAN_LOSS_PROV_IMP_AMT, R_LOAN_LOSS_PROV_PERF_AMT, R_LOAN_LOSS_PROV_UNDER_PERF_AMT, R_LOSS_GIVEN_DEFAULT_RATE, R_LOSS_IDENT_PERIOD_RATE, R_MIGRATION_SCENARIO_ID, R_NOF_AGREE_NO_PD_CHANGE, R_NOF_AGREE_PD_CHANGE, R_NOF_COLL_NO_PD_CHANGE, R_NOF_COLL_PD_CHANGE, R_NOF_PERIODS_STAGE_1, R_NOF_PERIODS_STAGE_2, R_ONE_YEAR_PROB_OF_DEFAULT_RATE, R_ON_BALANCE_ID, R_POCI_DELTA_RISK_PROV_LLP_AMT, R_POCI_EXTRA_INCOME_LLP_AMT, R_POCI_GR_BOOK_VALUE_LLP_AMT, R_POCI_INTEREST_INCOME_LLP_AMT, R_POCI_NET_BOOK_VALUE_LLP_AMT, R_POCI_PURCHASE_PRICE_LLP_AMT, R_POCI_RISK_PROVISION_LLP_AMT, R_POCI_RP_INT_COSTS_LLP_AMT, R_POCI_UNWINDING_LLP_AMT, R_PORTFOLIO_LLP_ID, R_PORTFOLIO_LLP_P_ID, R_PORTFOLIO_SCENARIO_ID, R_POS_COMPONENT_ID, R_PROB_OF_DEFAULT_RATE, R_PY_EXCHANGE_RATE, R_RATING_BY_MASTER_ID, R_RATING_COUNTRY_CODE, R_RATING_ID, R_RATING_MODULE, R_RATING_SECTOR, R_RATING_STATUS_ID, R_RATING_SUB_MODULE, R_RISK_PROV_INTEREST_LLP_AMT, R_STAGE_LLP_ID, R_STAGE_LLP_PY_ID, R_STAGE_RULE_SET_ID, R_UNWINDING_IFRS_AMT, R_UNWINDING_SLLP_AMT, R_VIRTUAL_COND_VALID_UNTIL_DATE, R_WRITE_OFF_PROL_BV_LLP_AMT, E_AVERAGE_VOLUME_AMT, E_BALANCE_AMT, E_BASIC_MCM_ID, E_BOOKED_EFF_INTEREST_AMT, E_BOOK_VALUE_AC_AMT, E_CALL_PUT_ID, E_CFLW_ALG_ID, E_CF_CHANGE_SLLP_AMT, E_COLLATERAL_AMT, E_CONDITION_VALID_FROM_DATE, E_CONDITION_VALID_UNTIL_DATE, E_CONTRACT_SIGNING_DATE, E_CREDIT_ADJUSTED_INT_RATE, E_CREDIT_ADJUSTED_INT_SLLP_RATE, E_CUSTOMER_ID, E_CUSTOMER_NAME, E_CUSTOMER_SURNAME, E_DAYS_PAST_DUE_NO, E_DIRECT_WRITE_OFF_AMT, E_DISCOUNT_AMT, E_EAD_FROM_SLLP_AMT, E_ELA_OFFSET_RATE, E_ELA_RATE, E_END_OF_CONTRACT_DATE, E_FIRST_INTEREST_ADJUSTMENT_DATE, E_FIRST_INTEREST_PAYM_DATE, E_FIRST_REGULAR_REPAYM_DATE, E_FUNDING_MCM_ID, E_IFRS_CATEGORY_ID, E_IMPAIRMENT_TRIGGER_ID, E_IS_CONS_REQUIRED, E_IS_CREATE_BT_IFRS9, E_IS_IMPAIRMENT_INDICATED, E_IS_PERSIST_COLL_PROFILE, E_IS_PERSIST_RISK_PROFILE, E_IS_SIGNIFICANT_WORSE, E_IS_SIMPLIFIED_APPROACH, E_IS_USE_CONVEXITY_ADJUSTMENT, E_IS_WATCHLIST_STAGE_2, E_LGD_COLL_RATE, E_LLP_CF_CHANGE_TYPE_ID, E_MATURITY_SHORTENING_GRID, E_MAT_REF_INT_RATE_GRID, E_M_BLOCK_ID, E_M_SEL_BLOCK_ID, E_NOMINAL_INTEREST_RATE, E_NOMINAL_VALUE_AMT, E_OPTION_DATE, E_OPTION_STRIKE_PRICE, E_PERSIST_CASHFLOW_ID, E_POCI_GR_BOOK_VALUE_SLLP_AMT, E_POCI_PURCHASE_PRICE_AMT, E_POS_COMPOSITION_TYPE_ID, E_POS_COMP_PARENT_ID, E_PROB_DEF_GROUP_ID, E_PRODUCT_ID, E_PROLONGATION_DATE, E_REF_MCM_ID, E_REG_REPAYM_GRID, E_REPAYMENT_AMT, E_REPAYM_GROUP_ID, E_RISK_PROV_INTEREST_ID, E_RISK_PROV_INTEREST_SLLP_AMT, E_SLLP_STATUS_ID, E_SUBSET_ID, E_UTILIZATION_AMT, E_VALUATION_MCM_ID, E_VOLA_REF_FORWARD_RATE, PRJ_ACOR_TYPE_ID, PRJ_NOF_ACOR_PERIODS, PRJ_CLAIM_AMT, PRJ_DBE_ID, PRJ_DBE_NAME, PRJ_ENG_ID, PRJ_ENG_NAME, PRJ_ISIN, PRJ_IS_EX_ABIT, PRJ_IS_FINREP_FORBORNE, PRJ_KUST_ID, PRJ_KUSY_ID, PRJ_OE_ID, PRJ_OE_NAME, PRJ_ORIG_IFRS_CATEGORY_ID, PRJ_POSITION_SPOT_ID, PRJ_PRODUCT_TYPE_ID, PRJ_SEGMENT_ID, PRJ_SEGMENT_NAME, PRJ_SLLP_TYPE_ID, PRJ_SOURCE_SYSTEM_ID, PRJ_WATCHLIST_ID, PRJ_POS_SOURCE_INFO, PRJ_SLLP_SOURCE_INFO, PRJ_LAST_DCL_CORR_PKG_ID, PRJ_NOF_REBOOKING_SRC, PRJ_NOF_REBOOKING_TGT, QUELLE, BRANCH
        from NLB.ZEB_CONTROL_CURRENT
        where FACILITY_ID not like '%_KK'
    ) ,

    ZEB_NLB as (
        select
        PORTFOLIO.FACILITY_ID,
        PORTFOLIO.CUT_OFF_DATE,
        PORTFOLIO.FACILITY_ID_NLB,
        PORTFOLIO.FACILITY_ID_BLB,
        PORTFOLIO.FACILITY_ID_CBB,
        ZEB_NLB.R_CURRENCY_ID,
        ZEB_NLB.R_EXCHANGE_RATE,
        ZEB_NLB.R_EXPOSURE_AT_DEFAULT_AMT,
        ZEB_NLB.E_LGD_COLL_RATE,
        ZEB_NLB.R_LGD_NET_RATE,
        ZEB_NLB.R_LOSS_GIVEN_DEFAULT_RATE,
        ZEB_NLB.R_EAD_TOTAL_AMT,
        ZEB_NLB.R_EXP_LOSS_AMT,
        ZEB_NLB.E_DAYS_PAST_DUE_NO,
        ZEB_NLB.R_RATING_ID,
        ZEB_NLB.R_INIT_RATING_MODULE,
        ZEB_NLB.R_INIT_RATING_SECTOR,
        ZEB_NLB.R_RATING_SUB_MODULE,
        ZEB_NLB.E_BOOK_VALUE_AC_AMT,
        ZEB_NLB.E_CONTRACT_SIGNING_DATE,
        ZEB_NLB.E_BALANCE_AMT,
        ZEB_NLB.E_NOMINAL_VALUE_AMT,
        ZEB_NLB.PRJ_IS_FINREP_FORBORNE,
        ZEB_NLB.R_CREDIT_CONVERSION_FACTOR_RATE,
        ZEB_NLB.R_ONE_YEAR_PROB_OF_DEFAULT_RATE,
        ZEB_NLB.R_LIFETIME_PROB_DEF_RATE,
        ZEB_NLB.R_EXP_LIFETIME_LOSS_AMT,
        ZEB_NLB.E_END_OF_CONTRACT_DATE,
        ZEB_NLB.R_IS_POCI,
        ZEB_NLB.R_INIT_RATING_ID,
        ZEB_NLB.R_LOAN_LOSS_PROVISION_AMT, -- EWB
        ZEB_NLB.R_RATING_MODULE,
        ZEB_NLB.R_STAGE_LLP_ID,
        ZEB_NLB.R_STAGE_LLP_REASON_DESC,
        ZEB_NLB.E_PROLONGATION_DATE,
        ZEB_NLB.R_ON_BALANCE_ID,
        --ECB
        ZEB_NLB.PRJ_CLAIM_AMT,
        ZEB_NLB.R_STAGE_LLP_CALCULATED_ID,
        ZEB_NLB.R_FORWARD_PROB_OF_DEFAULT_RATE
        from ZEB_NLB_PRE as ZEB_NLB
        inner join CALC.SWITCH_PORTFOLIO_CURRENT as PORTFOLIO on PORTFOLIO.CUT_OFF_DATE= ZEB_NLB.CUTOFFDATE and PORTFOLIO.FACILITY_ID_NLB = ZEB_NLB.FACILITY_ID
    ),
    ZEB_BLB as (
        select
        PORTFOLIO.FACILITY_ID,
        PORTFOLIO.CUT_OFF_DATE,
        PORTFOLIO.FACILITY_ID_NLB,
        PORTFOLIO.FACILITY_ID_BLB,
        PORTFOLIO.FACILITY_ID_CBB,
        ZEB_BLB.R_CURRENCY_ID,
        ZEB_BLB.R_EXCHANGE_RATE,
        ZEB_BLB.R_EXPOSURE_AT_DEFAULT_AMT,
        ZEB_BLB.E_LGD_COLL_RATE,
        ZEB_BLB.R_LGD_NET_RATE,
        ZEB_BLB.R_LOSS_GIVEN_DEFAULT_RATE,
        ZEB_BLB.R_EAD_TOTAL_AMT,
        ZEB_BLB.R_EXP_LOSS_AMT,
        ZEB_BLB.E_DAYS_PAST_DUE_NO,
        ZEB_BLB.R_RATING_ID,
        ZEB_BLB.R_INIT_RATING_MODULE,
        ZEB_BLB.R_INIT_RATING_SECTOR,
        ZEB_BLB.R_RATING_SUB_MODULE,
        ZEB_BLB.E_BOOK_VALUE_AC_AMT,
        ZEB_BLB.E_CONTRACT_SIGNING_DATE,
        ZEB_BLB.E_BALANCE_AMT,
        ZEB_BLB.E_NOMINAL_VALUE_AMT,
        ZEB_BLB.PRJ_IS_FINREP_FORBORNE,
        ZEB_BLB.R_CREDIT_CONVERSION_FACTOR_RATE,
        ZEB_BLB.R_ONE_YEAR_PROB_OF_DEFAULT_RATE,
        ZEB_BLB.R_LIFETIME_PROB_DEF_RATE,
        ZEB_BLB.R_EXP_LIFETIME_LOSS_AMT,
        ZEB_BLB.E_END_OF_CONTRACT_DATE,
        ZEB_BLB.R_IS_POCI,
        ZEB_BLB.R_INIT_RATING_ID,
        ZEB_BLB.R_LOAN_LOSS_PROVISION_AMT, -- EWB
        ZEB_BLB.R_RATING_MODULE,
        ZEB_BLB.R_STAGE_LLP_ID,
        ZEB_BLB.R_STAGE_LLP_REASON_DESC,
        ZEB_BLB.E_PROLONGATION_DATE,
        ZEB_BLB.R_ON_BALANCE_ID,
         --ECB
        ZEB_BLB.PRJ_CLAIM_AMT,
        ZEB_BLB.R_STAGE_LLP_CALCULATED_ID,
        ZEB_BLB.R_FORWARD_PROB_OF_DEFAULT_RATE
        from BLB.ZEB_CONTROL_CURRENT as ZEB_BLB
        inner join CALC.SWITCH_PORTFOLIO_CURRENT as PORTFOLIO on PORTFOLIO.CUT_OFF_DATE=ZEB_BLB.CUTOFFDATE and PORTFOLIO.FACILITY_ID_BLB=ZEB_BLB.FACILITY_ID
     ),
    ZEB_ANL as (
        select
        PORTFOLIO.FACILITY_ID,
        PORTFOLIO.CUT_OFF_DATE,
        PORTFOLIO.FACILITY_ID_NLB,
        PORTFOLIO.FACILITY_ID_BLB,
        PORTFOLIO.FACILITY_ID_CBB,
        ZEB_ANL.R_CURRENCY_ID,
        ZEB_ANL.R_EXCHANGE_RATE,
        ZEB_ANL.R_EXPOSURE_AT_DEFAULT_AMT,
        ZEB_ANL.E_LGD_COLL_RATE,
        ZEB_ANL.R_LGD_NET_RATE,
        ZEB_ANL.R_LOSS_GIVEN_DEFAULT_RATE,
        ZEB_ANL.R_EAD_TOTAL_AMT,
        ZEB_ANL.R_EXP_LOSS_AMT,
        ZEB_ANL.E_DAYS_PAST_DUE_NO,
        ZEB_ANL.R_RATING_ID,
        ZEB_ANL.R_INIT_RATING_MODULE,
        ZEB_ANL.R_INIT_RATING_SECTOR,
        ZEB_ANL.R_RATING_SUB_MODULE,
        ZEB_ANL.E_BOOK_VALUE_AC_AMT,
        ZEB_ANL.E_CONTRACT_SIGNING_DATE,
        ZEB_ANL.E_BALANCE_AMT,
        ZEB_ANL.E_NOMINAL_VALUE_AMT,
        ZEB_ANL.PRJ_IS_FINREP_FORBORNE,
        ZEB_ANL.R_CREDIT_CONVERSION_FACTOR_RATE,
        ZEB_ANL.R_ONE_YEAR_PROB_OF_DEFAULT_RATE,
        ZEB_ANL.R_LIFETIME_PROB_DEF_RATE,
        ZEB_ANL.R_EXP_LIFETIME_LOSS_AMT,
        ZEB_ANL.E_END_OF_CONTRACT_DATE,
        ZEB_ANL.R_IS_POCI,
        ZEB_ANL.R_INIT_RATING_ID,
        ZEB_ANL.R_LOAN_LOSS_PROVISION_AMT, -- EWB
        ZEB_ANL.R_RATING_MODULE,
        ZEB_ANL.R_STAGE_LLP_ID,
        ZEB_ANL.R_STAGE_LLP_REASON_DESC,
        ZEB_ANL.E_PROLONGATION_DATE,
        ZEB_ANL.R_ON_BALANCE_ID,
         --ECB
        ZEB_ANL.PRJ_CLAIM_AMT,
        ZEB_ANL.R_STAGE_LLP_CALCULATED_ID,
        ZEB_ANL.R_FORWARD_PROB_OF_DEFAULT_RATE
        from ANL.ZEB_CONTROL_CURRENT as ZEB_ANL
        inner join CALC.SWITCH_PORTFOLIO_CURRENT as PORTFOLIO on PORTFOLIO.CUT_OFF_DATE=ZEB_ANL.CUTOFFDATE and PORTFOLIO.FACILITY_ID_NLB=ZEB_ANL.FACILITY_ID
    ),
    ZEB as (
        select * from ZEB_NLB
        union all
        select * from ZEB_BLB
        union all
        select * from ZEB_ANL
    )
    select distinct
        PORTFOLIO.FACILITY_ID,
        PORTFOLIO.CUT_OFF_DATE,
        PORTFOLIO.FACILITY_ID_CBB,
        RATING.RATING_ID                            as RATING_ID_FVC,
        RATING.LGD_IN_PROZENT                       as LGD_IN_PROZENT_FVC,
        RATING.RISIKOGEWICHT_IN_PROZENT             as RISIKOGEWICHT_IN_PROZENT_FVC,
        RATING.RATING_DATE                          as RATING_DATE
        , ZEB.R_CURRENCY_ID
        , ZEB.R_EXCHANGE_RATE
        , ZEB.R_EXPOSURE_AT_DEFAULT_AMT
        , ZEB.E_LGD_COLL_RATE
        , ZEB.R_LGD_NET_RATE
        , ZEB.R_LOSS_GIVEN_DEFAULT_RATE
        , ZEB.R_EAD_TOTAL_AMT
        , ZEB.R_EXP_LOSS_AMT
        , ZEB.E_DAYS_PAST_DUE_NO
        , ZEB.R_RATING_ID
        , ZEB.R_INIT_RATING_MODULE
        , ZEB.R_INIT_RATING_SECTOR
        , ZEB.R_RATING_SUB_MODULE
        , ZEB.E_BOOK_VALUE_AC_AMT
        , ZEB.E_CONTRACT_SIGNING_DATE
        , ZEB.E_BALANCE_AMT
        , ZEB.E_NOMINAL_VALUE_AMT
        , ZEB.PRJ_IS_FINREP_FORBORNE
        , ZEB.R_CREDIT_CONVERSION_FACTOR_RATE
        , ZEB.R_ONE_YEAR_PROB_OF_DEFAULT_RATE
        , ZEB.R_LIFETIME_PROB_DEF_RATE,
        -- neue Spalten nach Issue #487
        ZEB.R_EXP_LIFETIME_LOSS_AMT,
        ZEB.E_END_OF_CONTRACT_DATE,
        ZEB.R_IS_POCI,
        ZEB.R_INIT_RATING_ID,
        ZEB.R_LOAN_LOSS_PROVISION_AMT,
        ZEB.R_RATING_MODULE,
        ZEB.R_STAGE_LLP_ID,
        ZEB.R_STAGE_LLP_REASON_DESC,
        ZEB.E_PROLONGATION_DATE,
        -- neue Spalte nach off-Balance Match
        ZEB.R_ON_BALANCE_ID,
         --ECB
        ZEB.PRJ_CLAIM_AMT,
        ZEB.R_STAGE_LLP_CALCULATED_ID,
        ZEB.R_FORWARD_PROB_OF_DEFAULT_RATE,
        -- Tape Defaults
        Current_USER                                                                            as CREATED_USER,       -- Letzter Nutzer, der diese Tabelle gebaut hat.
        Current_TIMESTAMP                                                                       as CREATED_TIMESTAMP   -- Neuester Zeitstempel, wann diese Tabelle zuletzt gebaut wurde.
    from CALC.SWITCH_PORTFOLIO_CURRENT as PORTFOLIO
    left join ZEB on ZEB.CUT_OFF_DATE = PORTFOLIO.CUT_OFF_DATE and ZEB.FACILITY_ID = PORTFOLIO.FACILITY_ID
    left join CALC.VIEW_FACILITY_RATING_FVC as RATING on PORTFOLIO.CUT_OFF_DATE= RATING.CUT_OFF_DATE and PORTFOLIO.FACILITY_ID = RATING.FACILITY_ID
;

-- CI START FOR ALL TAPES
-- Current-Tabelle erstellen
call STG.TEST_PROC_BACKUP_AND_DROP('AMC','TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_CURRENT');
create table AMC.TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_CURRENT like CALC.VIEW_FACILITY_KREDITRISIKO_KENNZAHLEN distribute by hash(FACILITY_ID) in SPACE_AMC_A,SPACE_AMC_B,SPACE_AMC_C,SPACE_AMC_D,SPACE_AMC_E,SPACE_AMC_F;
create index AMC.INDEX_FACILITY_KREDITRISIKO_KENNZAHLEN_CURRENT_FACILITY_ID on AMC.TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_CURRENT (FACILITY_ID);
call STG.TEST_PROC_LOAD_AND_DROP_BACKUP_FOR('AMC','TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_CURRENT');
-- Current-Tabelle erstellen
call STG.TEST_PROC_BACKUP_AND_DROP('AMC','TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_ARCHIVE');
create table AMC.TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_ARCHIVE like CALC.VIEW_FACILITY_KREDITRISIKO_KENNZAHLEN distribute by hash(FACILITY_ID) partition by RANGE (CUT_OFF_DATE) (starting '1.1.2015' ending '31.12.2030' EVERY 1 Month) in SPACE_AMC_A,SPACE_AMC_B,SPACE_AMC_C,SPACE_AMC_D,SPACE_AMC_E,SPACE_AMC_F;
create index AMC.INDEX_FACILITY_KREDITRISIKO_KENNZAHLEN_ARCHIVE_FACILITY_ID on AMC.TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_ARCHIVE (FACILITY_ID);
call STG.TEST_PROC_LOAD_AND_DROP_BACKUP_FOR('AMC','TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_ARCHIVE');
-- CI END FOR ALL TAPES

-- SWITCH Views erstellen
call STG.TEST_PROC_DROP_AND_CREATE_SWITCH('AMC','TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_CURRENT');
call STG.TEST_PROC_DROP_AND_CREATE_SWITCH('AMC','TABLE_FACILITY_KREDITRISIKO_KENNZAHLEN_ARCHIVE');