-- ZEB Risikovorsorge Daten

-- View erstellen
drop view CALC.VIEW_FACILITY_ZEB_RISK_PROVISION;
create or replace view CALC.VIEW_FACILITY_ZEB_RISK_PROVISION as
with
    ZEB_RIVO_GESAMT as (
        select ASSET_LIAB_ID, BANK_ID, CLIENT_ID, POS_COMPONENT_ID, DET_SCENARIO_ID, KEY_DATE,
               case when LENGTH(POSITION_ID) = 12 and LENGTH(POSITION_SUB_ID) = 34 then
                    POSITION_SUB_ID
                when SUBSTR(POSITION_ID,6,2) <> '30' or LENGTH(POSITION_ID) <> 34 then
                    POSITION_ID
                else
                    LEFT(POSITION_ID,20)||'-31-'||SUBSTR(POSITION_ID,25,LENGTH(POSITION_ID)-24)
               end as POSITION_ID,
               POSITION_SUB_ID, RUN_ID, STATUS, VIRTUAL_COND_VALID_UNTIL_DATE, CURRENCY_ID, EXCHANGE_RATE, CALC_SCENARIO_LLP_ID, RATING_COUNTRY_CODE, CREDIT_CONVERSION_FACTOR_RATE, EDIT_LLP_COMMENT_DESC, EDIT_LLP_DATE, EDIT_LLP_USER, IFRS_EFF_INTEREST_RATE, EFF_PROB_OF_DEFAULT_GLLP_RATE, EFF_PROB_OF_DEFAULT_PLLP_RATE, EXP_LIFETIME_LOSS_AMT, EXP_LOSS_AMT, EXPOSURE_AT_DEFAULT_AMT, EXPOSURE_METHOD_ID, FORWARD_LPD_RATE, FORWARD_PROB_OF_DEFAULT_RATE, HYPOTHETICAL_RATING_ID, IBNR_LOSS_DIFF_EXIST_PLLP_AMT, IBNR_LOSS_DIFF_EXPIRE_PLLP_AMT, IBNR_LOSS_DIFF_GLLP_PLLP_AMT, IBNR_LOSS_DIFF_NEW_PLLP_AMT, IBNR_LOSS_DIFF_PREV_PLLP_AMT, IBNR_LOSS_PLLP_AMT, INC_LOSS_DIFF_EXIST_GLLP_AMT, INC_LOSS_DIFF_EXPIRE_GLLP_AMT, INC_LOSS_DIFF_NEW_GLLP_AMT, INC_LOSS_DIFF_PLLP_GLLP_AMT, INC_LOSS_DIFF_WO_UNW_GLLP_AMT, INC_LOSS_GLLP_AMT, INC_LOSS_SLLP_AMT, INIT_RATING_COUNTRY_CODE, INIT_RATING_MODULE, IS_SIGNIFICANT_SLLP, PY_EXCHANGE_RATE, INIT_RATING_ID, INIT_RATING_SUB_MODULE, INIT_RATING_SECTOR, INIT_STAGE_LLP_ID, IS_IMPAIRMENT_LLP, IS_MIGRATED, IS_GLLP, IS_PLLP, LIFETIME_EFFECT_AMT, LIFETIME_PROB_DEF_RATE, LIP_EFFECT_AMT, LLP_IAS39_CALC_ID, LLP_IFRS9_CALC_ID, DELTA_LOAN_LOSS_PROVISION_AMT, DELTA_LOAN_LOSS_PROV_PY_AMT, LOAN_LOSS_PROVISION_AMT, LOAN_LOSS_PROV_IMP_AMT, LOAN_LOSS_PROV_PERF_AMT, LOAN_LOSS_PROVISION_PREV_AMT, LOAN_LOSS_PROVISION_PY_AMT, LOAN_LOSS_PROV_UNDER_PERF_AMT, LOSS_GIVEN_DEFAULT_RATE, LGD_NET_RATE, LOSS_IDENT_PERIOD_RATE, MIGRATION_SCENARIO_ID, NOF_AGREE_PD_CHANGE, NOF_AGREE_NO_PD_CHANGE, NOF_COLL_PD_CHANGE, NOF_COLL_NO_PD_CHANGE, ON_BALANCE_ID, IS_ON_BALANCE, ONE_YEAR_PROB_OF_DEFAULT_RATE, PL_EFFECT_DIFF_PREV_GLLP_AMT, PL_EFFECT_GLLP_AMT, PORTFOLIO_LLP_P_ID, PORTFOLIO_SCENARIO_ID, PORTFOLIO_LLP_ID, PROB_OF_DEFAULT_RATE, RATING_BY_MASTER_ID, RATING_MODULE, RATING_ID, RATING_STATUS_ID, RATING_SUB_MODULE, RATING_SECTOR, STAGE_LLP_P_ID, STAGE_LLP_PY_ID, STAGE_LLP_REASON_DESC, STAGE_LLP_CALCULATED_ID, STAGE_LLP_ID, STAGE_RULE_SET_ID, UNWINDING_GLLP_AMT, UNWINDING_IFRS_AMT, UNWINDING_SLLP_AMT, EAD_TOTAL_AMT, LLP_CC_EFF_INTEREST_RATE, EXP_LOSS_CC_AMT, EXPOSURE_AT_DEFAULT_CC_AMT, EAD_TOTAL_CC_AMT, EXPOSURE_METHOD_CC_ID, DELTA_GLLP_CC_AMT, GLLP_CC_AMT, IS_GLLP_CC, IS_PLLP_CC, LLP_CC_CALC_ID, LOSS_GIVEN_DEFAULT_CC_RATE, DELTA_PLLP_CC_AMT, PLLP_CC_AMT, UNWINDING_LLP_CC_AMT, CREDIT_ADJUSTED_INT_LLP_RATE, IS_POCI, POCI_GR_BOOK_VALUE_LLP_AMT, POCI_INTEREST_INCOME_LLP_AMT, POCI_NET_BOOK_VALUE_LLP_AMT, POCI_PURCHASE_PRICE_LLP_AMT, POCI_RP_INT_COSTS_LLP_AMT, RISK_PROV_INTEREST_CC_LLP_AMT, RISK_PROV_INTEREST_LLP_AMT, POCI_EXTRA_INCOME_LLP_AMT, WRITE_OFF_PROL_BV_LLP_AMT, POCI_DELTA_RISK_PROV_LLP_AMT, POCI_RISK_PROVISION_LLP_AMT, POCI_UNWINDING_LLP_AMT, BOOK_VALUE_NET_AMT, IS_SIGNIFICANT_SLLP_PY, NOF_PERIODS_STAGE_1, NOF_PERIODS_STAGE_2, CUT_OFF_DATE, QUELLE, BRANCH
        from NLB.ZEB_POSITION_CURRENT
        union all
        select ASSET_LIAB_ID, BANK_ID, CLIENT_ID, POS_COMPONENT_ID, DET_SCENARIO_ID, KEY_DATE, POSITION_ID, POSITION_SUB_ID, RUN_ID, STATUS, VIRTUAL_COND_VALID_UNTIL_DATE, CURRENCY_ID, EXCHANGE_RATE, CALC_SCENARIO_LLP_ID, RATING_COUNTRY_CODE, CREDIT_CONVERSION_FACTOR_RATE, EDIT_LLP_COMMENT_DESC, EDIT_LLP_DATE, EDIT_LLP_USER, IFRS_EFF_INTEREST_RATE, EFF_PROB_OF_DEFAULT_GLLP_RATE, EFF_PROB_OF_DEFAULT_PLLP_RATE, EXP_LIFETIME_LOSS_AMT, EXP_LOSS_AMT, EXPOSURE_AT_DEFAULT_AMT, EXPOSURE_METHOD_ID, FORWARD_LPD_RATE, FORWARD_PROB_OF_DEFAULT_RATE, HYPOTHETICAL_RATING_ID, IBNR_LOSS_DIFF_EXIST_PLLP_AMT, IBNR_LOSS_DIFF_EXPIRE_PLLP_AMT, IBNR_LOSS_DIFF_GLLP_PLLP_AMT, IBNR_LOSS_DIFF_NEW_PLLP_AMT, IBNR_LOSS_DIFF_PREV_PLLP_AMT, IBNR_LOSS_PLLP_AMT, INC_LOSS_DIFF_EXIST_GLLP_AMT, INC_LOSS_DIFF_EXPIRE_GLLP_AMT, INC_LOSS_DIFF_NEW_GLLP_AMT, INC_LOSS_DIFF_PLLP_GLLP_AMT, INC_LOSS_DIFF_WO_UNW_GLLP_AMT, INC_LOSS_GLLP_AMT, INC_LOSS_SLLP_AMT, INIT_RATING_COUNTRY_CODE, INIT_RATING_MODULE, IS_SIGNIFICANT_SLLP, PY_EXCHANGE_RATE, INIT_RATING_ID, INIT_RATING_SUB_MODULE, INIT_RATING_SECTOR, INIT_STAGE_LLP_ID, IS_IMPAIRMENT_LLP, IS_MIGRATED, IS_GLLP, IS_PLLP, LIFETIME_EFFECT_AMT, LIFETIME_PROB_DEF_RATE, LIP_EFFECT_AMT, LLP_IAS39_CALC_ID, LLP_IFRS9_CALC_ID, DELTA_LOAN_LOSS_PROVISION_AMT, DELTA_LOAN_LOSS_PROV_PY_AMT, LOAN_LOSS_PROVISION_AMT, LOAN_LOSS_PROV_IMP_AMT, LOAN_LOSS_PROV_PERF_AMT, LOAN_LOSS_PROVISION_PREV_AMT, LOAN_LOSS_PROVISION_PY_AMT, LOAN_LOSS_PROV_UNDER_PERF_AMT, LOSS_GIVEN_DEFAULT_RATE, LGD_NET_RATE, LOSS_IDENT_PERIOD_RATE, MIGRATION_SCENARIO_ID, NOF_AGREE_PD_CHANGE, NOF_AGREE_NO_PD_CHANGE, NOF_COLL_PD_CHANGE, NOF_COLL_NO_PD_CHANGE, ON_BALANCE_ID, IS_ON_BALANCE, ONE_YEAR_PROB_OF_DEFAULT_RATE, PL_EFFECT_DIFF_PREV_GLLP_AMT, PL_EFFECT_GLLP_AMT, PORTFOLIO_LLP_P_ID, PORTFOLIO_SCENARIO_ID, PORTFOLIO_LLP_ID, PROB_OF_DEFAULT_RATE, RATING_BY_MASTER_ID, RATING_MODULE, RATING_ID, RATING_STATUS_ID, RATING_SUB_MODULE, RATING_SECTOR, STAGE_LLP_P_ID, STAGE_LLP_PY_ID, STAGE_LLP_REASON_DESC, STAGE_LLP_CALCULATED_ID, STAGE_LLP_ID, STAGE_RULE_SET_ID, UNWINDING_GLLP_AMT, UNWINDING_IFRS_AMT, UNWINDING_SLLP_AMT, EAD_TOTAL_AMT, LLP_CC_EFF_INTEREST_RATE, EXP_LOSS_CC_AMT, EXPOSURE_AT_DEFAULT_CC_AMT, EAD_TOTAL_CC_AMT, EXPOSURE_METHOD_CC_ID, DELTA_GLLP_CC_AMT, GLLP_CC_AMT, IS_GLLP_CC, IS_PLLP_CC, LLP_CC_CALC_ID, LOSS_GIVEN_DEFAULT_CC_RATE, DELTA_PLLP_CC_AMT, PLLP_CC_AMT, UNWINDING_LLP_CC_AMT, CREDIT_ADJUSTED_INT_LLP_RATE, IS_POCI, POCI_GR_BOOK_VALUE_LLP_AMT, POCI_INTEREST_INCOME_LLP_AMT, POCI_NET_BOOK_VALUE_LLP_AMT, POCI_PURCHASE_PRICE_LLP_AMT, POCI_RP_INT_COSTS_LLP_AMT, RISK_PROV_INTEREST_CC_LLP_AMT, RISK_PROV_INTEREST_LLP_AMT, POCI_EXTRA_INCOME_LLP_AMT, WRITE_OFF_PROL_BV_LLP_AMT, POCI_DELTA_RISK_PROV_LLP_AMT, POCI_RISK_PROVISION_LLP_AMT, POCI_UNWINDING_LLP_AMT, BOOK_VALUE_NET_AMT, IS_SIGNIFICANT_SLLP_PY, NOF_PERIODS_STAGE_1, NOF_PERIODS_STAGE_2, CUT_OFF_DATE, QUELLE, BRANCH
        from ANL.ZEB_POSITION_CURRENT
        union all
        select ASSET_LIAB_ID, BANK_ID, CLIENT_ID, POS_COMPONENT_ID, DET_SCENARIO_ID, KEY_DATE, POSITION_ID, POSITION_SUB_ID, RUN_ID, STATUS, VIRTUAL_COND_VALID_UNTIL_DATE, CURRENCY_ID, EXCHANGE_RATE, CALC_SCENARIO_LLP_ID, RATING_COUNTRY_CODE, CREDIT_CONVERSION_FACTOR_RATE, EDIT_LLP_COMMENT_DESC, EDIT_LLP_DATE, EDIT_LLP_USER, IFRS_EFF_INTEREST_RATE, EFF_PROB_OF_DEFAULT_GLLP_RATE, EFF_PROB_OF_DEFAULT_PLLP_RATE, EXP_LIFETIME_LOSS_AMT, EXP_LOSS_AMT, EXPOSURE_AT_DEFAULT_AMT, EXPOSURE_METHOD_ID, FORWARD_LPD_RATE, FORWARD_PROB_OF_DEFAULT_RATE, HYPOTHETICAL_RATING_ID, IBNR_LOSS_DIFF_EXIST_PLLP_AMT, IBNR_LOSS_DIFF_EXPIRE_PLLP_AMT, IBNR_LOSS_DIFF_GLLP_PLLP_AMT, IBNR_LOSS_DIFF_NEW_PLLP_AMT, IBNR_LOSS_DIFF_PREV_PLLP_AMT, IBNR_LOSS_PLLP_AMT, INC_LOSS_DIFF_EXIST_GLLP_AMT, INC_LOSS_DIFF_EXPIRE_GLLP_AMT, INC_LOSS_DIFF_NEW_GLLP_AMT, INC_LOSS_DIFF_PLLP_GLLP_AMT, INC_LOSS_DIFF_WO_UNW_GLLP_AMT, INC_LOSS_GLLP_AMT, INC_LOSS_SLLP_AMT, INIT_RATING_COUNTRY_CODE, INIT_RATING_MODULE, IS_SIGNIFICANT_SLLP, PY_EXCHANGE_RATE, INIT_RATING_ID, INIT_RATING_SUB_MODULE, INIT_RATING_SECTOR, INIT_STAGE_LLP_ID, IS_IMPAIRMENT_LLP, IS_MIGRATED, IS_GLLP, IS_PLLP, LIFETIME_EFFECT_AMT, LIFETIME_PROB_DEF_RATE, LIP_EFFECT_AMT, LLP_IAS39_CALC_ID, LLP_IFRS9_CALC_ID, DELTA_LOAN_LOSS_PROVISION_AMT, DELTA_LOAN_LOSS_PROV_PY_AMT, LOAN_LOSS_PROVISION_AMT, LOAN_LOSS_PROV_IMP_AMT, LOAN_LOSS_PROV_PERF_AMT, LOAN_LOSS_PROVISION_PREV_AMT, LOAN_LOSS_PROVISION_PY_AMT, LOAN_LOSS_PROV_UNDER_PERF_AMT, LOSS_GIVEN_DEFAULT_RATE, LGD_NET_RATE, LOSS_IDENT_PERIOD_RATE, MIGRATION_SCENARIO_ID, NOF_AGREE_PD_CHANGE, NOF_AGREE_NO_PD_CHANGE, NOF_COLL_PD_CHANGE, NOF_COLL_NO_PD_CHANGE, ON_BALANCE_ID, IS_ON_BALANCE, ONE_YEAR_PROB_OF_DEFAULT_RATE, PL_EFFECT_DIFF_PREV_GLLP_AMT, PL_EFFECT_GLLP_AMT, PORTFOLIO_LLP_P_ID, PORTFOLIO_SCENARIO_ID, PORTFOLIO_LLP_ID, PROB_OF_DEFAULT_RATE, RATING_BY_MASTER_ID, RATING_MODULE, RATING_ID, RATING_STATUS_ID, RATING_SUB_MODULE, RATING_SECTOR, STAGE_LLP_P_ID, STAGE_LLP_PY_ID, STAGE_LLP_REASON_DESC, STAGE_LLP_CALCULATED_ID, STAGE_LLP_ID, STAGE_RULE_SET_ID, UNWINDING_GLLP_AMT, UNWINDING_IFRS_AMT, UNWINDING_SLLP_AMT, EAD_TOTAL_AMT, LLP_CC_EFF_INTEREST_RATE, EXP_LOSS_CC_AMT, EXPOSURE_AT_DEFAULT_CC_AMT, EAD_TOTAL_CC_AMT, EXPOSURE_METHOD_CC_ID, DELTA_GLLP_CC_AMT, GLLP_CC_AMT, IS_GLLP_CC, IS_PLLP_CC, LLP_CC_CALC_ID, LOSS_GIVEN_DEFAULT_CC_RATE, DELTA_PLLP_CC_AMT, PLLP_CC_AMT, UNWINDING_LLP_CC_AMT, CREDIT_ADJUSTED_INT_LLP_RATE, IS_POCI, POCI_GR_BOOK_VALUE_LLP_AMT, POCI_INTEREST_INCOME_LLP_AMT, POCI_NET_BOOK_VALUE_LLP_AMT, POCI_PURCHASE_PRICE_LLP_AMT, POCI_RP_INT_COSTS_LLP_AMT, RISK_PROV_INTEREST_CC_LLP_AMT, RISK_PROV_INTEREST_LLP_AMT, POCI_EXTRA_INCOME_LLP_AMT, WRITE_OFF_PROL_BV_LLP_AMT, POCI_DELTA_RISK_PROV_LLP_AMT, POCI_RISK_PROVISION_LLP_AMT, POCI_UNWINDING_LLP_AMT, BOOK_VALUE_NET_AMT, IS_SIGNIFICANT_SLLP_PY, NOF_PERIODS_STAGE_1, NOF_PERIODS_STAGE_2, CUT_OFF_DATE, QUELLE, BRANCH
        from BLB.ZEB_POSITION_CURRENT
    ),
    ZEB_RIVO as (
        select ZEB.CUT_OFF_DATE,
               PORTFOLIO.CLIENT_ID_ORIG,
               PORTFOLIO.FACILITY_ID,
               LEFT(ZEB.POSITION_ID, 34) as POSITION_ID_TRUNCATED,
               ZEB.STAGE_LLP_CALCULATED_ID,
               ZEB.IFRS_EFF_INTEREST_RATE,
               -1*ZEB.LOAN_LOSS_PROVISION_AMT * EXCHANGE.RATE_TARGET_TO_EUR as ZEB_EWB_EUR_AMT,
               -1*ZEB.LOAN_LOSS_PROVISION_AMT AS ZEB_EWB_OC_AMT,
               ZEB.ON_BALANCE_ID,
               EXCHANGE.RATE_EUR_TO_TARGET as EXCHANGE_RATE_EUR2OC,
               ZEB.BRANCH,
               ZEB.QUELLE as SOURCE
        from ZEB_RIVO_GESAMT as ZEB
        inner join CALC.SWITCH_PORTFOLIO_CURRENT as PORTFOLIO
        on PORTFOLIO.FACILITY_ID=(LEFT(ZEB.POSITION_ID, 34)) and PORTFOLIO.CUT_OFF_DATE = ZEB.CUT_OFF_DATE
        left join IMAP.CURRENCY_MAP as EXCHANGE on (ZEB.CURRENCY_ID,ZEB.CUT_OFF_DATE) = (EXCHANGE.ZIEL_WHRG,EXCHANGE.CUT_OFF_DATE)
    ),
    ZEB_GRUNDGESAMTHEIT as (
      select distinct CUT_OFF_DATE,
                      FACILITY_ID,
                      CLIENT_ID_ORIG,
                      max(IFRS_EFF_INTEREST_RATE) as IFRS_EFF_INTEREST_RATE,
                      EXCHANGE_RATE_EUR2OC,
                      BRANCH,
                      SOURCE
        FROM ZEB_RIVO
        group by CUT_OFF_DATE, FACILITY_ID, CLIENT_ID_ORIG, EXCHANGE_RATE_EUR2OC, BRANCH, SOURCE
    ),
    ZEB_ONB as ( -- ZEB Onbalance
        select ZEB_RIVO.CUT_OFF_DATE,
               ZEB_RIVO.POSITION_ID_TRUNCATED,
               ZEB_RIVO.STAGE_LLP_CALCULATED_ID as ZEB_STAGE_ONBALANCE,
               ZEB_RIVO.ZEB_EWB_EUR_AMT AS ZEB_EWB_EUR_ONBALANCE,
               ZEB_RIVO.ZEB_EWB_OC_AMT AS ZEB_EWB_OC_ONBALANCE
        from ZEB_RIVO
        where ON_BALANCE_ID = 'onBalance'
    ),
    ZEB_OFFB as ( -- ZEB Offbalance
       select ZEB_RIVO.CUT_OFF_DATE,
               ZEB_RIVO.POSITION_ID_TRUNCATED,
               ZEB_RIVO.STAGE_LLP_CALCULATED_ID as ZEB_STAGE_OFFBALANCE,
               ZEB_RIVO.ZEB_EWB_EUR_AMT AS ZEB_EWB_EUR_OFFBALANCE,
               ZEB_RIVO.ZEB_EWB_OC_AMT AS ZEB_EWB_OC_OFFBALANCE
        from ZEB_RIVO
        where ON_BALANCE_ID = 'offBalance'
        --  and STAGE_LLP_CALCULATED_ID <> 'undefinedLLPStage'
    ),
    RISK_PROVISION as (
        select
            ZEB_RIVO.CUT_OFF_DATE,
            ZEB_RIVO.CLIENT_ID_ORIG,
            ZEB_RIVO.FACILITY_ID,
            max(ZEB_RIVO.IFRS_EFF_INTEREST_RATE) as IFRS_EFF_INTEREST_RATE,
            nullif(ZEB_RIVO.EXCHANGE_RATE_EUR2OC, null) as EXCHANGE_RATE_EUR2OC,
            -- Onbalance
            nullif(listagg(distinct ZEB_ONB.ZEB_STAGE_ONBALANCE, ', ') within group (order by ZEB_ONB.ZEB_STAGE_ONBALANCE),null) as ZEB_STAGE_ONBALANCE,
            nullif(sum(ZEB_ONB.ZEB_EWB_EUR_ONBALANCE),null) as ZEB_EWB_EUR_ONBALANCE,
            nullif(sum(ZEB_ONB.ZEB_EWB_OC_ONBALANCE),null) as ZEB_EWB_OC_ONBALANCE,
            -- Offbalance
            nullif(listagg(distinct ZEB_OFFB.ZEB_STAGE_OFFBALANCE,', ') within group (order by ZEB_OFFB.ZEB_STAGE_OFFBALANCE),null) as ZEB_STAGE_OFFBALANCE,
            nullif(sum(ZEB_OFFB.ZEB_EWB_EUR_OFFBALANCE),null) as ZEB_EWB_EUR_OFFBALANCE,
            nullif(sum(ZEB_OFFB.ZEB_EWB_OC_OFFBALANCE),null) as ZEB_EWB_OC_OFFBALANCE,
            ZEB_RIVO.BRANCH,
            ZEB_RIVO.SOURCE
        from ZEB_GRUNDGESAMTHEIT as ZEB_RIVO
        left join ZEB_ONB on (ZEB_ONB.POSITION_ID_TRUNCATED, ZEB_ONB.CUT_OFF_DATE) = (ZEB_RIVO.FACILITY_ID, ZEB_RIVO.CUT_OFF_DATE)
        left join ZEB_OFFB on (ZEB_OFFB.POSITION_ID_TRUNCATED, ZEB_OFFB.CUT_OFF_DATE) = (ZEB_RIVO.FACILITY_ID, ZEB_RIVO.CUT_OFF_DATE)
        group by ZEB_RIVO.CUT_OFF_DATE, ZEB_RIVO.CLIENT_ID_ORIG, ZEB_RIVO.FACILITY_ID, ZEB_RIVO.EXCHANGE_RATE_EUR2OC, ZEB_RIVO.BRANCH, ZEB_RIVO.SOURCE
    )
select
      *,
    Current_USER        as CREATED_USER,      -- Letzter Nutzer, der diese Tabelle gebaut hat.
    Current_TIMESTAMP   as CREATED_TIMESTAMP  -- Neuester Zeitstempel, wann diese Tabelle zuletzt gebaut wurde.
from RISK_PROVISION
;

-- CI START FOR ALL TAPES
-- Current-Tabelle erstellen
call STG.TEST_PROC_BACKUP_AND_DROP('AMC','TABLE_FACILITY_ZEB_RISK_PROVISION_CURRENT');
create table AMC.TABLE_FACILITY_ZEB_RISK_PROVISION_CURRENT like CALC.VIEW_FACILITY_ZEB_RISK_PROVISION distribute by hash(FACILITY_ID) in SPACE_AMC_A,SPACE_AMC_B,SPACE_AMC_C,SPACE_AMC_D,SPACE_AMC_E,SPACE_AMC_F;
create index AMC.INDEX_FACILITY_ZEB_RISK_PROVISION_CURRENT_FACILITY_ID on AMC.TABLE_FACILITY_ZEB_RISK_PROVISION_CURRENT (FACILITY_ID);
call STG.TEST_PROC_LOAD_AND_DROP_BACKUP_FOR('AMC','TABLE_FACILITY_ZEB_RISK_PROVISION_CURRENT');
-- Archiv-Tabelle erstellen
call STG.TEST_PROC_BACKUP_AND_DROP('AMC','TABLE_FACILITY_ZEB_RISK_PROVISION_ARCHIVE');
create table AMC.TABLE_FACILITY_ZEB_RISK_PROVISION_ARCHIVE like AMC.TABLE_FACILITY_ZEB_RISK_PROVISION_CURRENT distribute by hash(FACILITY_ID) partition by RANGE (CUT_OFF_DATE) (starting '1.1.2020' ending '31.12.2030' EVERY 1 Month) in SPACE_AMC_A,SPACE_AMC_B,SPACE_AMC_C,SPACE_AMC_D,SPACE_AMC_E,SPACE_AMC_F;
create index AMC.INDEX_FACILITY_ZEB_RISK_PROVISION_ARCHIVE_FACILITY_ID on AMC.TABLE_FACILITY_ZEB_RISK_PROVISION_ARCHIVE (FACILITY_ID);
call STG.TEST_PROC_LOAD_AND_DROP_BACKUP_FOR('AMC','TABLE_FACILITY_ZEB_RISK_PROVISION_ARCHIVE');
-- CI END FOR ALL TAPES

-- SWITCH View erstellen
call STG.TEST_PROC_DROP_AND_CREATE_SWITCH('AMC','TABLE_FACILITY_ZEB_RISK_PROVISION_CURRENT');
call STG.TEST_PROC_DROP_AND_CREATE_SWITCH('AMC','TABLE_FACILITY_ZEB_RISK_PROVISION_ARCHIVE');

