-------------------
-- FACILITY_CORE --
-------------------
-- CI START FOR ALL TAPES
-- Drop View
drop view AMC.TAPE_FACILITY_CORE_FINISH;
-- View erstellen
create or replace view AMC.TAPE_FACILITY_CORE_FINISH as
        select
               CUT_OFF_DATE as CUT_OFF_DATE, DATA_CUT_OFF_DATE as DATA_CUT_OFF_DATE, BRANCH, FACILITY_ID,  FACILITY_ID_LEADING, FACILITY_ID_ALTERNATIVE, Trade_ID, INITIAL_TRADE_ID, CLIENT_ID,
               CLIENT_ID_NLB, CLIENT_ID_LUX, KUNDENBETREUER_OE_BEZEICHNUNG, PORTFOLIO, PRODUCTTYPE, PRODUCTGROUP_AVIATION, GUARANTEE_FLAG, ORIGINAL_CURRENCY,
               FVC_RISIKOGEWICHT_IN_PROZENT, FVC_LGD_IN_PROZENT, FVC_RATING_NOTE, FVC_RATING_DATE,ZEB_R_EXPOSURE_AT_DEFAULT_AMT_EUR, ZEB_R_EXPOSURE_AT_DEFAULT_AMT_TC,
               ZEB_E_LGD_COLL_RATE, ZEB_R_LGD_NET_RATE, ZEB_R_LOSS_GIVEN_DEFAULT_RATE, ZEB_R_EAD_TOTAL_AMT_EUR, ZEB_R_EAD_TOTAL_AMT_TC, ZEB_R_EXP_LOSS_AMT,
               ZEB_R_EXP_LIFETIME_LOSS_AMT, ZEB_E_DAYS_PAST_DUE_NO, ZEB_R_RATING_ID, ZEB_R_INIT_RATING_MODULE, ZEB_R_INIT_RATING_SECTOR, ZEB_R_RATING_SUB_MODULE,
               ZEB_E_BOOK_VALUE_AC_AMT, ZEB_E_CONTRACT_SIGNING_DATE, ZEB_E_BALANCE_AMT, ZEB_E_NOMINAL_VALUE_AMT, ZEB_PRJ_IS_FINREP_FORBORNE,
               ZEB_R_CREDIT_CONVERSION_FACTOR_RATE, ZEB_R_ONE_YEAR_PROB_OF_DEFAULT_RATE, ZEB_R_LIFETIME_PROB_DEF_RATE, SYNDICATION_ROLE, OWN_SYNDICATE_QUOTA,
               ORIGINATION_DATE, CURRENT_CONTRACTUAL_MATURITY_DATE, AMORTIZATION_TYPE, AMORTIZATION_FREQUENCY_DAYS, NEXT_AMORTIZATION_TO_BE_PAID,
               AMOUNT_DUE_AT_MATURITY_EUR, INTEREST_RATE_TYPE, INTEREST_RATE, FIXED_INTEREST_RATE, INTEREST_RATE_FREQUENCY, FIXED_INTEREST_RATE_END_DATE,
               INTEREST_RATE_INDEX, INTEREST_RATE_MARGIN, NEXT_INTEREST_PAYMENT_DATE, COMMITMENT_FEE_RATE, COMMITMENT_FEE_FREQUENCY, COMMITMENT_FEE_NEXT_PAYMENT_DATE,
               COMMITMENT_FEE_RATE_END_DATE, ELIGIBILITY_FOR_COVERSTOCK, COVERSTOCK_NAME, EFFECTIVE_COVER_AMOUNT_EUR, HALTEKATEGORIE, DERIVATIVES_FAIR_VALUE_DIRTY_EUR,
               DERIVATIVES_FAIR_VALUE_DIRTY_TC, DERIVATE_FAIR_VALUE_EUR, CVA_EUR, DVA_EUR, FCA_EUR, FBA_EUR, round(BILANZWERT_BRUTTO_EUR,2) as BILANZWERT_BRUTTO,
               round(BILANZWERT_BRUTTO_TC,2) as BILANZWERT_BRUTTO_TC, ACCRUED_INTEREST_EUR, ACCRUED_INTEREST_TC, round(BILANZWERT_IFRS9_EUR,2) as BILANZWERT_IFRS9,
               round(BILANZWERT_IFRS9_TC,2) as BILANZWERT_IFRS9_TC, RISK_PROVISION_EUR, RISK_PROVISION_TC, PD_ALL_IN_RATE_TILG, LIQ_GLOBAL_CURRENT_AMOUNT_ORIGINAL_CURRENCY,
               LIQ_HOST_BANK_SHARE, LOAN_PAST_DUE_ZINS_ORIGINAL_CURRENCY, LOAN_PAST_DUE_TILG_ORIGINAL_CURRENCY, IFRS_STAGE, LOANSTATE_SPOT, TOTAL_PAST_DUE, LOANSTATE_LIQ,
               round(PRICIPAL_OST_EUR_SPOT,2) as PRICIPAL_OST_EUR_SPOT, -- Principal Outstanding in Euro (Achtung: Diese Spalte muss mit dem Konsortialanteil multipliziert werden und enthält Guthaben mit positivem Vorzeichen)
               round(PRICIPAL_OST_TC_SPOT,2) as PRICIPAL_OST_TC_SPOT,  -- Principal Outstanding in Originalwährung (Achtung: Diese Spalte muss mit dem Konsortialanteil multipliziert werden und enthält Guthaben mit positivem Vorzeichen)
               round(PRICIPAL_OST_EUR_BW,2) as PRICIPAL_OST_EUR_BW, -- Principal Outstanding in Euro
               round(PRICIPAL_OST_TC_BW,2) as PRICIPAL_OST_TC_BW, -- Principal Outstanding in Originalwährung
               round(PRICIPAL_OST_EUR_AUS_TC_MIT_KURS_ERRECHNET,2) as PRICIPAL_OST_EUR_AUS_TC_MIT_KURS_ERRECHNET,
               round(OFFBALANCE_EUR,2) as OFFBALANCE_EUR, round(OFFBALANCE_TC,2) as OFFBALANCE_TC,
               round(HGB_EUR,2) as HGB_EUR,
               round(HGB_TC,2) as HGB_TC, -- Bilanzwert HGB in Originalwährung
               AMORTIZATION_IN_ARREARS_EUR_SPOT, -- Tilgungsrückstände in Euro
               AMORTIZATION_IN_ARREARS_TC_SPOT,AMORTIZATION_IN_ARREARS_EUR_BW, AMORTIZATION_IN_ARREARS_TC_BW,
               INTEREST_IN_ARREARS_EUR_SPOT, -- Zinsrückstände in Originalwährung
               INTEREST_IN_ARREARS_TC_SPOT, INTEREST_IN_ARREARS_EUR_BW, INTEREST_IN_ARREARS_TC_BW,
               FEES_IN_ARREARS_EUR_SPOT, -- Rückständige Gebühren in Euro
               FEES_IN_ARREARS_TC_SPOT,
               FVA_EUR, -- Fair Value Adjustment
               FVA_TC,
               AUSZAHLUNGSPLICHT_EUR,
               ZUSAGE_AKTIV,PARENT_FACILITY_ID,
               RIVO_STAGE,
               RIVO_STAGE_1_EUR, RIVO_STAGE_1_TC, RIVO_STAGE_2_EUR,RIVO_STAGE_2_TC,RIVO_STAGE_3_EUR, RIVO_STAGE_3_TC, RIVO_STAGE_POCI_EUR,
               RIVO_STAGE_POCI_TC, NICHT_IM_BW_REWE, INAKTIV, FACILITY_ID_CBB, CBB_GESCHAEFTS_ID, ZUGEHOERIGER_RAHMEN, DAYS_PAST_DUE
        from AMC.TABLE_FACILITY_CORE_CURRENT
;
-- CI END FOR ALL TAPES