-- View erstellen
drop view CALC.VIEW_FACILITY_TASSLER;
create or replace view CALC.VIEW_FACILITY_TASSLER as
    select
           CUT_OFF_DATE, DATA_CUT_OFF_DATE, BRANCH, FACILITY_ID, TRADE_ID,
           CLIENT_ID, CLIENT_ID_NLB, CLIENT_ID_LUX, PRODUCTTYPE,
           --PRODUCTGROUP_AVIATION,
           --GUARANTEE_FLAG,
           ORIGINAL_CURRENCY,
           FVC_RISIKOGEWICHT_IN_PROZENT, FVC_LGD_IN_PROZENT, FVC_RATING_NOTE,
           ZEB_R_EXPOSURE_AT_DEFAULT_AMT_EUR, ZEB_R_EXPOSURE_AT_DEFAULT_AMT_TC, ZEB_E_LGD_COLL_RATE, ZEB_R_LGD_NET_RATE,
           ZEB_R_LOSS_GIVEN_DEFAULT_RATE, ZEB_R_EAD_TOTAL_AMT_EUR, ZEB_R_EAD_TOTAL_AMT_TC, ZEB_R_EXP_LOSS_AMT,
           ZEB_E_DAYS_PAST_DUE_NO, ZEB_R_RATING_ID, ZEB_R_INIT_RATING_MODULE, ZEB_R_INIT_RATING_SECTOR,
           ZEB_R_RATING_SUB_MODULE, ZEB_E_BOOK_VALUE_AC_AMT, ZEB_E_CONTRACT_SIGNING_DATE, ZEB_E_BALANCE_AMT,
           ZEB_E_NOMINAL_VALUE_AMT, ZEB_PRJ_IS_FINREP_FORBORNE, ZEB_R_CREDIT_CONVERSION_FACTOR_RATE,
           ZEB_R_ONE_YEAR_PROB_OF_DEFAULT_RATE, ZEB_R_LIFETIME_PROB_DEF_RATE,
           SYNDICATION_ROLE, OWN_SYNDICATE_QUOTA, ORIGINATION_DATE, CURRENT_CONTRACTUAL_MATURITY_DATE,
           AMORTIZATION_TYPE, AMORTIZATION_FREQUENCY_DAYS, NEXT_AMORTIZATION_TO_BE_PAID, AMOUNT_DUE_AT_MATURITY_EUR,
           INTEREST_RATE_TYPE, INTEREST_RATE, FIXED_INTEREST_RATE, INTEREST_RATE_FREQUENCY, FIXED_INTEREST_RATE_END_DATE,
           INTEREST_RATE_INDEX, INTEREST_RATE_MARGIN, NEXT_INTEREST_PAYMENT_DATE,
           COMMITMENT_FEE_RATE, COMMITMENT_FEE_FREQUENCY, COMMITMENT_FEE_NEXT_PAYMENT_DATE, COMMITMENT_FEE_RATE_END_DATE,
           ELIGIBILITY_FOR_COVERSTOCK, COVERSTOCK_NAME, EFFECTIVE_COVER_AMOUNT_EUR, HALTEKATEGORIE,
           DERIVATIVES_FAIR_VALUE_DIRTY_EUR, DERIVATIVES_FAIR_VALUE_DIRTY_TC,
           BILANZWERT_BRUTTO_EUR, BILANZWERT_BRUTTO_TC, ACCRUED_INTEREST_EUR, ACCRUED_INTEREST_TC, BILANZWERT_IFRS9_EUR, BILANZWERT_IFRS9_TC,
           RISK_PROVISION_EUR, RISK_PROVISION_TC, PD_ALL_IN_RATE_TILG,
           LIQ_GLOBAL_CURRENT_AMOUNT_ORIGINAL_CURRENCY, LIQ_HOST_BANK_SHARE, LOAN_PAST_DUE_ZINS_ORIGINAL_CURRENCY, LOAN_PAST_DUE_TILG_ORIGINAL_CURRENCY,
           IFRS_STAGE, LOANSTATE_SPOT, TOTAL_PAST_DUE, LOANSTATE_LIQ,
           PRICIPAL_OST_EUR_SPOT, PRICIPAL_OST_TC_SPOT, PRICIPAL_OST_EUR_BW, PRICIPAL_OST_TC_BW, PRICIPAL_OST_EUR_AUS_TC_MIT_KURS_ERRECHNET,
           OFFBALANCE_EUR, OFFBALANCE_TC, HGB_EUR, HGB_TC, AMORTIZATION_IN_ARREARS_EUR_SPOT, AMORTIZATION_IN_ARREARS_TC_SPOT,AMORTIZATION_IN_ARREARS_EUR_BW,
           AMORTIZATION_IN_ARREARS_TC_BW, INTEREST_IN_ARREARS_EUR_SPOT,
           INTEREST_IN_ARREARS_TC_SPOT, INTEREST_IN_ARREARS_EUR_BW, INTEREST_IN_ARREARS_TC_BW, FVA_EUR, FVA_TC,
           RIVO_STAGE, RIVO_STAGE_1_EUR, RIVO_STAGE_1_TC, RIVO_STAGE_2_EUR, RIVO_STAGE_2_TC, RIVO_STAGE_3_EUR, RIVO_STAGE_3_TC, RIVO_STAGE_POCI_EUR, RIVO_STAGE_POCI_TC,
           NICHT_IM_BW_REWE, INAKTIV, FACILITY_ID_CBB, CBB_GESCHAEFTS_ID, ZUGEHOERIGER_RAHMEN, DAYS_PAST_DUE, PORTFOLIO
    from CALC.SWITCH_FACILITY_CORE_CURRENT
;

-- CI START FOR ALL TAPES
-- Tabelle erstellen
call STG.TEST_PROC_BACKUP_AND_DROP('AMC','TABLE_FACILITY_TASSLER_CURRENT');
create table AMC.TABLE_FACILITY_TASSLER_CURRENT like CALC.VIEW_FACILITY_TASSLER distribute by hash(FACILITY_ID) in SPACE_AMC_A,SPACE_AMC_B,SPACE_AMC_C,SPACE_AMC_D,SPACE_AMC_E,SPACE_AMC_F;
create index AMC.INDEX_FACILITY_TASSLER_CURRENT_FACILITY_ID on AMC.TABLE_FACILITY_TASSLER_CURRENT (FACILITY_ID);
call STG.TEST_PROC_LOAD_AND_DROP_BACKUP_FOR('AMC','TABLE_FACILITY_TASSLER_CURRENT');
-- CI END FOR ALL TAPES

-- SWITCH View erstellen
call STG.TEST_PROC_DROP_AND_CREATE_SWITCH('AMC','TABLE_FACILITY_TASSLER_CURRENT');