-- VIEW erstellen
drop view CALC.VIEW_FACILITY_SPECIFICS_PRODUCTGROUPS;
create or replace view CALC.VIEW_FACILITY_SPECIFICS_PRODUCTGROUPS as
    select distinct CUT_OFF_DATE, FACILITY_ID, PRODUKTGRUPPE as SPECIFICS_PRODUCTGROUP from NLB.SPECIFICS_FLUGZEUG_GESCHAEFTE
    union all
    select distinct CUT_OFF_DATE, CBB_TO_NLB.FACILITY_ID_CBB as FACILITY_ID, PRODUKTGRUPPE as SPECIFICS_PRODUCTGROUP
    from NLB.SPECIFICS_FLUGZEUG_GESCHAEFTE as SPECIFICS
    inner join CALC.VIEW_FACILITY_CBB_TO_NLB as CBB_TO_NLB
    on (SPECIFICS.FACILITY_ID = CBB_TO_NLB.FACILITY_ID_NLB)
;
